SonarSource/SonarJS

javascript-checks/src/main/java/org/sonar/javascript/checks/DuplicateFunctionArgumentCheck.java
javascript-checks/src/test/resources/checks/duplicateFunctionArgument.js

Raise an issue for each duplicated argument

SONARJS-725 Improve DuplicateFunctionArgumentCheck: raise an issue for each duplicated argument

---

javascript-checks/src/main/java/org/sonar/javascript/checks/EqEqEqCheck.java

SONARJS-737 Remove rule EqEqEq from default profile

---

its/ruling/src/test/expected/javascript-EqEqEq.json

Issues disappeared due to commit bc65f27a088d76392e14f1fc6377e91ffdd7e179

SONARJS-738 Fix ruling

---

javascript-frontend/src/main/java/org/sonar/javascript/se/sv/EqualitySymbolicValue.java
javascript-frontend/src/test/resources/se/nullability.js
javascript-frontend/src/test/resources/se/relations.js

on values which are null or undefined

SONARJS-798 Equality relations are not evaluated correctly

---

its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/BigProjectTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/DefaultProfileTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MetricsTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MinifiedFilesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java

SONAR-8574 Replace usage of api/resources/index by api/measures/component in ITs

---

javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/TestUtils.java
javascript-frontend/src/test/java/org/sonar/javascript/se/LiveVariableAnalysisTest.java
javascript-frontend/src/test/java/org/sonar/javascript/se/SeChecksDispatcherTest.java
javascript-frontend/src/test/java/org/sonar/javascript/se/SymbolicExecutionTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/SymbolModelImplTest.java
pom.xml
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptLanguageTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSquidSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java

Just the minimum changes to compile and pass tests.

Update to sonar.version 6.2

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/BigProjectTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MinifiedFilesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java

This reverts commit de8514be0626000e543d377f9f724ca78a33e984.

Revert "SONAR-8631 Update ITs: minified files are not imported anymore (#458)"

---

its/performancing/src/test/java/JavaScriptPerformanceTest.java

Time increased mostly because of SONARJS-752

Update performance ITs expectations

---

javascript-checks/src/main/java/org/sonar/javascript/checks/ArrayCallbackWithoutReturnCheck.java
javascript-checks/src/test/resources/checks/ArrayCallbackWithoutReturn.js

function is declared outside method call

SONARJS-853 Improve ArrayCallbackWithoutReturnCheck

---

its/performancing/src/test/java/JavaScriptPerformanceTest.java

Update IT perf expectations for SE

---

its/ruling/src/test/expected/javascript-CommentedCode.json
javascript-checks/src/main/java/org/sonar/javascript/checks/CommentedCodeCheck.java
javascript-checks/src/test/resources/checks/commentedCode.js

Ignore single closed curly braces

SONARJS-961 Improve CommentedCodeCheck

---

its/plugin/projects/nosonar/main.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/NoSonarTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java
its/plugin/tests/src/test/resources/nosonar.xml
javascript-frontend/src/main/java/org/sonar/javascript/metrics/MetricsVisitor.java
javascript-frontend/src/main/java/org/sonar/javascript/metrics/NoSonarVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/metrics/MetricsVisitorTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSquidSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSquidSensorTest.java

This is a porting from branch-2.21

SONARJS-986 Support NOSONAR in SonarLint

---

javascript-checks/src/main/java/org/sonar/javascript/checks/SuperInvocationCheck.java
javascript-checks/src/test/resources/checks/superInvocation.js

constructor inside object literal

SONARJS-971 NPE in SuperInvocationCheck

---

javascript-checks/src/main/java/org/sonar/javascript/checks/LoopsShouldNotBeInfiniteCheck.java
javascript-checks/src/test/resources/checks/loopsShouldNotBeInfinite.js

include for-loop update expression into the CFG Loop

SONARJS-989 Fix LoopsShouldNotBeInfinite

---

its/ruling/src/test/expected/javascript-EqEqEq.json
its/ruling/src/test/expected/javascript-S2259.json
its/ruling/src/test/expected/javascript-S2589.json
its/ruling/src/test/expected/javascript-S2873.json
its/ruling/src/test/expected/javascript-S3757.json
its/ruling/src/test/expected/javascript-S3758.json
its/ruling/src/test/expected/javascript-S3759.json
its/ruling/src/test/expected/javascript-S3800.json
javascript-frontend/src/main/java/org/sonar/javascript/se/ExpressionStack.java
javascript-frontend/src/main/java/org/sonar/javascript/se/ProgramState.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SymbolicExecution.java
javascript-frontend/src/main/java/org/sonar/javascript/se/limitations/CrossProceduralLimitation.java
javascript-frontend/src/main/java/org/sonar/javascript/se/sv/LogicalNotSymbolicValue.java
javascript-frontend/src/test/java/org/sonar/javascript/se/SeVerifier.java
javascript-frontend/src/test/java/org/sonar/javascript/se/SymbolicExecutionTest.java
javascript-frontend/src/test/java/org/sonar/javascript/se/limitations/FunctionArgumentsCollectorTest.java
javascript-frontend/src/test/resources/se/drop_arguments_constraints_in_conditions.js
javascript-frontend/src/test/resources/se/limitations/function_argument_collector.js

First implementation with just the basic case covered

SONARJS-980 Drop constraints on condition function parameters

---

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptTest.java

Activation of template rule was fixed (as since SQ 6.4 profile key is generated in different manner). Moreover dependency on internal API "rules/app" is removed.

Fix ruling IT

---

javascript-checks/src/main/java/org/sonar/javascript/checks/TooManyArgumentsCheck.java
javascript-checks/src/test/resources/checks/TooManyArguments.js
javascript-checks/src/test/resources/checks/TooManyArguments2.js

Update message TooManyArgumentsCheck: include declaration line number

---

javascript-checks/src/main/java/org/sonar/javascript/checks/GetterSetterCheck.java
javascript-checks/src/test/resources/checks/GetterSetter.js

GetterSetterCheck should not fail on duplicate getter

---

javascript-checks/src/main/java/org/sonar/javascript/checks/UseOfEmptyReturnValueCheck.java
javascript-checks/src/test/resources/checks/UseOfEmptyReturnValue.js

Improve UseOfEmptyReturnValueCheck: ignore await

---

javascript-checks/src/main/java/org/sonar/javascript/checks/AssignmentWithinConditionCheck.java
javascript-checks/src/test/resources/checks/assignmentWithinCondition.js

Allow parenthesised assignment as arrow function body
Fixes #591

Improve AssignmentWithinCondition

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java

It is possible after upgrade of SSLR to 1.22

Remove duplicated methods from Tree Factory

---

javascript-checks/src/main/java/org/sonar/javascript/checks/EqEqEqCheck.java
javascript-checks/src/main/java/org/sonar/javascript/checks/LoopsShouldNotBeInfiniteCheck.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SeCheck.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SeChecksDispatcher.java
javascript-frontend/src/test/java/org/sonar/javascript/se/SeCheckTest.java

Port bug fix #615 to next minor version 

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/declarations/FunctionDeclarationTest.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/statements/ExpressionStatementTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/FunctionDeclarationTreeModelTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/FunctionExpressionTreeModelTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/statement/BlockTreeModelTest.java
javascript-frontend/src/test/java/org/sonar/javascript/utils/JavaScriptTreeModelTest.java

Incorrect detection of async functions

---

pom.xml
sonar-javascript-plugin/pom.xml

Update issue tracking url and developers list

---

javascript-checks/src/main/javascript/javascript.js
javascript-checks/src/test/java/org/sonar/javascript/checks/TooManyArgumentsCheckTest.java
javascript-checks/src/test/resources/checks/TooManyArguments.js
javascript-frontend/src/main/java/org/sonar/javascript/tree/symbols/type/TypeVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/type/ClassTypeTest.java
javascript-frontend/src/test/resources/ast/resolve/type/classType.js

Fix FP TooManyArgumentsCheck: getter/setter property call

---

javascript-checks/src/test/resources/checks/AlertUse.js
javascript-frontend/src/main/java/org/sonar/javascript/lexer/JavaScriptLexer.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/expressions/jsx/JsxIdentifierTest.java

Fix parsing of JSX identifier

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/main/java/org/sonar/javascript/se/ExpressionStack.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/expression/ImportTreeImpl.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/Tree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/expression/ImportTree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/visitors/DoubleDispatchVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/expressions/CallExpressionTest.java
javascript-frontend/src/test/java/org/sonar/javascript/se/ExpressionStackTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/CallExpressionTreeModelTest.java

Support dynamic imports

---

its/ruling/src/test/expected/javascript-DuplicatePropertyName.json
javascript-checks/src/main/java/org/sonar/javascript/checks/DuplicatePropertyNameCheck.java
javascript-checks/src/test/resources/checks/duplicatePropertyName.js

Improve DuplicatePropertyName: consider static and non-static separately

---

its/ruling/src/test/expected/javascript-S4043.json
javascript-checks/src/main/java/org/sonar/javascript/checks/ArrayReverseCheck.java
javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4043.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4043.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_profile.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_recommended_profile.json
javascript-checks/src/test/java/org/sonar/javascript/checks/ArrayReverseCheckTest.java
javascript-checks/src/test/resources/checks/ArrayReverse.js

 Rule: Array.reverse should not be used misleadingly

---

javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/main/java/org/sonar/javascript/checks/ErrorWithoutThrowCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3984.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3984.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_profile.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_recommended_profile.json
javascript-checks/src/test/java/org/sonar/javascript/checks/ErrorWithoutThrowCheckTest.java
javascript-checks/src/test/resources/checks/ErrorWithoutThrow.js

Rule: Exception should not be created without being thrown

---

javascript-frontend/src/main/java/org/sonar/javascript/cfg/ControlFlowGraphBuilder.java
javascript-frontend/src/main/java/org/sonar/javascript/cfg/JsCfgBlock.java
javascript-frontend/src/test/java/org/sonar/javascript/cfg/CfgBlockTest.java

Fix infinite loop in skipEmptyBlocks

---

its/ruling/pom.xml
pom.xml

That allows to support SonarQube 6.7.

Upgrade Orchestrator to 3.14

---

javascript-checks/src/main/java/org/sonar/javascript/checks/ErrorWithoutThrowCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3984.json

[RSPEC-3984](https://jira.sonarsource.com/browse/RSPEC-3984)

Replace 'exception' with 'error' in ErrorWithoutThrowCheck

---

javascript-checks/src/main/java/org/sonar/javascript/checks/utils/CheckUtils.java
javascript-checks/src/test/java/org/sonar/javascript/checks/NestedConditionalOperatorsCheckTest.java
javascript-checks/src/test/java/org/sonar/javascript/checks/SuperInvocationCheckTest.java
javascript-checks/src/test/java/org/sonar/javascript/checks/SymbolUsedAsConstructorCheckTest.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SymbolicExecution.java
javascript-frontend/src/test/resources/se/expression_stack_size.js

Fix clearing of stack for parenthesised expression in for loop

---

its/ruling/src/test/expected/javascript-S1854.json
javascript-checks/src/main/java/org/sonar/javascript/checks/DeadStoreCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1854.html
javascript-checks/src/test/resources/checks/DeadStore.js

Ignore 'undefined' initializations in DeadStoreCheck

---

its/ruling/src/test/expected/javascript-MissingNewlineAtEndOfFile.json
its/ruling/src/test/expected/javascript-ParsingError.json
its/ruling/src/test/expected/javascript-S1451.json
its/ruling/src/test/expected/javascript-S3504.json
its/ruling/src/test/expected/javascript-S3798.json
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/flow/FlowTupleTypeTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/flow/FlowTupleTypeTreeModelTest.java

Parse Flow syntax for empty tuples

---

its/ruling/src/test/expected/javascript-S4030.json
javascript-checks/src/main/java/org/sonar/javascript/checks/UnusedCollectionCheck.java
javascript-checks/src/test/resources/checks/UnusedCollection.js

UnusedCollectionCheck: exclude buffer view arrays

---

javascript-checks/src/test/resources/checks/ReassignedParameter.js
javascript-checks/src/test/resources/checks/variableDeclarationWithoutVar.js
javascript-frontend/src/main/java/org/sonar/javascript/tree/symbols/HoistedSymbolVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/SymbolModelImplTest.java
javascript-frontend/src/test/resources/ast/resolve/symbolModel.js

Fixes #828 and also some other false negatives from ReassignedParameter

Extract all bindings in variable declarations

---

its/ruling/src/test/expected/javascript-CommentedCode.json
its/ruling/src/test/expected/javascript-ParsingError.json
its/ruling/src/test/expected/javascript-S1451.json
its/ruling/src/test/expected/javascript-SingleQuote.json
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/declaration/ExportClauseTreeImpl.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/declaration/NameSpaceExportDeclarationTreeImpl.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/declaration/ExportClauseTree.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/declarations/module/ExportDeclarationTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/ExportClauseTreeModelTest.java

Parse Flow 'export type' statements

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/declarations/module/ScriptTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/VueScriptTreeModelTest.java

Fix parsing error: attributes in 'script' tag in 'vue' file

---

its/ruling/src/test/expected/javascript-S1854.json
javascript-checks/src/main/java/org/sonar/javascript/checks/DeadStoreCheck.java
javascript-checks/src/test/resources/checks/DeadStore.js
javascript-frontend/src/main/java/org/sonar/javascript/se/LiveVariableAnalysis.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/symbols/Usage.java

Improve DeadStoreCheck: cover '++', '--', '+=' etc

---

javascript-checks/src/main/java/org/sonar/javascript/checks/IndexOfCompareToPositiveNumberCheck.java
javascript-checks/src/test/resources/checks/indexOfCompareToPositiveNumber.js

Improve message S2692: mention 'includes'

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/expressions/ConditionalExpressionTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/ConditionalExpressionTreeModelTest.java

Fix parse error: ternary with arrow function

---

javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Bump up to version 4.0

---

its/ruling/src/test/expected/javascript-S3827.json
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/jsx/JsxElementTreeModelTest.java

Fix parsing of JSX member expressions

---

javascript-checks/src/main/java/org/sonar/javascript/checks/ArrayCallbackWithoutReturnCheck.java
javascript-checks/src/test/resources/checks/ArrayCallbackWithoutReturn.js

S3796: ignore returned Promise on async functions

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/main/java/org/sonar/javascript/se/ExpressionStack.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/expression/jsx/JsxEmptyClosingElementTreeImpl.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/expression/jsx/JsxEmptyOpeningElementTreeImpl.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/impl/expression/jsx/JsxShortFragmentElementTreeImpl.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/Tree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/expression/jsx/JsxEmptyClosingElementTree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/expression/jsx/JsxEmptyOpeningElementTree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/tree/expression/jsx/JsxShortFragmentElementTree.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/visitors/DoubleDispatchVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/expressions/jsx/JsxElementTest.java
javascript-frontend/src/test/java/org/sonar/javascript/se/ExpressionStackTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/jsx/JsxElementTreeModelTest.java
javascript-frontend/src/test/java/org/sonar/plugins/javascript/api/visitors/DoubleDispatchVisitorTest.java

Support JSX short fragment syntax

---

javascript-checks/src/main/java/org/sonar/javascript/checks/SuperInvocationCheck.java
javascript-checks/src/test/resources/checks/superInvocation.js

Fix S3854 when checking argument count on calling super in constructor

---

its/ruling/src/test/java/org/sonar/javascript/it/ProfileGenerator.java

- Fix page size in query for SQ API /api/rules/search
- SQ 7.0 enforces max. page size of 500

Fix broken ruling on SQ 7.0

---

its/ruling/src/test/expected/javascript-FunctionDefinitionInsideLoop.json
javascript-checks/src/main/java/org/sonar/javascript/checks/FunctionDefinitionInsideLoopCheck.java
javascript-checks/src/test/resources/checks/FunctionDefinitionInsideLoop.js

Improve FunctionDefinitionInsideLoop: ignore all safe Array functions

---

javascript-checks/src/main/java/org/sonar/javascript/checks/TooManyArgumentsCheck.java
javascript-checks/src/test/resources/checks/TooManyArguments.js
javascript-frontend/src/main/java/org/sonar/javascript/tree/symbols/type/TypeVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/type/ExpressionTypeTest.java
javascript-frontend/src/test/resources/ast/resolve/type/expressions.js

Stop inferring type from parameter default value

---

its/ruling/src/test/expected/javascript-S905.json
javascript-checks/src/main/java/org/sonar/javascript/checks/UselessExpressionStatementCheck.java
javascript-checks/src/test/resources/checks/UselessExpressionStatement.js

FP S905: Non-empty statements should change control flow

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java

sonar.javascript.exclusions should exclude only JavaScript files

---

javascript-checks/src/main/java/org/sonar/javascript/checks/ArrowFunctionConventionCheck.java
javascript-checks/src/test/resources/checks/ArrowFunctionConvention.js

Improve S3524: ignore when parameter has comment

---

its/ruling/src/test/expected/javascript-S4043.json
javascript-checks/src/main/java/org/sonar/javascript/checks/ArrayMutatingOperationCheck.java
javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/test/java/org/sonar/javascript/checks/ArrayMutatingOperationCheckTest.java
javascript-checks/src/test/resources/checks/ArrayMutatingOperation.js

S4043 add Array.sort() to the detected mutating methods

---

javascript-checks/src/main/java/org/sonar/javascript/checks/GlobalThisCheck.java
javascript-checks/src/test/resources/checks/GlobalThis.js

Fix FP S2990: "this" used inside class body

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/ArrayAndObjectConstructors.html

Extend description of ArrayAndObjectConstructors

---

its/ruling/src/test/expected/javascript-S2814.json
its/ruling/src/test/expected/javascript-S3827.json
javascript-checks/src/test/resources/checks/ReferenceError.js
javascript-frontend/src/main/java/org/sonar/javascript/tree/symbols/HoistedSymbolVisitor.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/SymbolModelImplTest.java
javascript-frontend/src/test/resources/ast/resolve/symbolModel.js

Create symbol for Flow interfaces

---

travis.sh

Enable dogfooding

---

javascript-checks/src/main/java/org/sonar/javascript/checks/SingleQuoteStringLiteralsCheck.java
javascript-checks/src/test/resources/checks/singleQuoteStringLiterals.js

Replace "simple quotes" by "single quotes"

---

docs/DOC.md

Add suffixes property to docs

---

javascript-checks/src/test/resources/checks/ReferenceError.js
javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/ImportDeclarationTreeModelTest.java

Fix parsing of imports when identifier matches flow keywords

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/TreeFactory.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/expressions/destructuring/ObjectBindingPatternTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/statement/VariableStatementTreeModelTest.java

Support trailing comma in object binding pattern

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/NamedExportDeclarationTreeModelTest.java

Fix parsing issue with default in export clause specifier

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/main/java/org/sonar/javascript/parser/JavaScriptGrammar.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/declarations/module/ScriptTest.java
javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/declaration/VueScriptTreeModelTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java
sonar-javascript-plugin/src/test/resources/vue/customSections.vue

Fix parsing on Vue custom tags

---

javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java
javascript-frontend/src/test/java/org/sonar/javascript/parser/declarations/module/ScriptTest.java

Support self-closing custom vue tags

---

its/performancing/src/test/java/JavaScriptPerformanceTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java
its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/EslintReportSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/EslintReportSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java

Fixes #987
**REBASE** when merging!

Add 'onlyWhenConfiguration' to CoverageSensor

---

its/plugin/plugins/javascript-custom-rules-plugin/pom.xml
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/DeprecatedCustomRulesDefinition.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/TestCustomRuleRepository.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/checks/BaseTreeVisitorCheck.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/checks/SubscriptionBaseVisitorCheck.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/checks/WhileStatementCheck.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/checks/package-info.java
its/plugin/plugins/javascript-custom-rules-plugin/src/main/resources/whileCheck.html
its/plugin/projects/custom_rules/src/dir/Person.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CustomRulesTests.java
its/plugin/tests/src/test/resources/profile-javascript-custom-rules.xml
javascript-checks-testkit/pom.xml
javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/CheckMessage.java
javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/CheckMessagesVerifier.java
javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/JavaScriptCheckVerifier.java
javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/TreeCheckTest.java
javascript-checks-testkit/src/test/java/org/sonar/javascript/checks/verifier/CheckMessageTest.java
javascript-checks-testkit/src/test/java/org/sonar/javascript/checks/verifier/CheckMessagesVerifierTest.java
javascript-checks/pom.xml
javascript-checks/src/main/java/org/sonar/javascript/checks/CommentRegularExpressionCheck.java
javascript-frontend/src/main/java/org/sonar/javascript/tree/JavaScriptCommentAnalyser.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomJavaScriptRulesDefinition.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomRuleRepository.java
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptChecks.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/JavaScriptRulesDefinition.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java

Remove dependency on sslr-squid-bridge

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/EslintReportSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/EslintReportSensorTest.java
sonar-javascript-plugin/src/test/resources/externalIssues/eslint-report.json

Support import of ESLint issues with zero length range

---

.cix.yml
its/performancing/src/test/java/JavaScriptPerformanceTest.java

Run performacing test only on LTS version

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MetricsTest.java

ITs: stop testing comment_lines_data

---

its/performancing/src/test/java/JavaScriptPerformanceTest.java

Drop usage of show.profiling api in perf testing

---

javascript-checks-testkit/pom.xml
javascript-frontend/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java

Update dependencies to be JDK9-10-11 compatible

---

nodejs-utils/pom.xml
nodejs-utils/src/main/java/org/sonarsource/nodejs/MockCommandBuilder.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilder.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandException.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/StreamConsumer.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/package-info.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/MockCommandBuilderTest.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
nodejs-utils/src/test/resources/error.js
nodejs-utils/src/test/resources/script.js
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java

Utils to launch NodeJS scripts

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/angular.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/ember.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/flowtype.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/import.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/jsx-a11y.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/promise.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/react.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/vue.json

Fix description of external eslint plugin rules

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSensor.java

Use 'getStringArray' to read value for 'sonar.typescript.eslint.reportPaths'

---

javascript-frontend/src/main/java/org/sonar/javascript/metrics/MetricsVisitor.java

Stop feeding 'comment_lines_data'

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/readme
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/sonarjs.json
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/EslintRulesDefinition.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/EslintRulesDefinitionTest.java

Add external rule descriptions for eslint-plugin-sonarjs

---

README.md

Update Twitter link

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/BigProjectTest.java

Due to drop of modules on SQ 7.6

Update plugin ITs directories expectations

---

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java

Update lits to version 0.8.0.1209

---

eslint-bridge/src/rules/os-command.ts
eslint-bridge/src/rules/utils.ts
eslint-bridge/tests/rules/os-command.test.ts
its/ruling/src/test/expected/javascript-S4721.json
javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/main/java/org/sonar/javascript/checks/OSCommandCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4721.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4721.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_profile.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_recommended_profile.json

Add security hotspot rule S4721 (OS Command)

---

eslint-bridge/src/rules/process-argv.ts
eslint-bridge/src/rules/pseudo-random.ts
eslint-bridge/src/rules/standard-input.ts
eslint-bridge/src/rules/utils.ts

Add #isMemberExpression utility to reduce duplication

---

eslint-bridge/src/rules/cors.ts
eslint-bridge/src/rules/main.ts
eslint-bridge/tests/rules/cors.test.ts
its/ruling/src/test/expected/javascript-S5122.json
javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/main/java/org/sonar/javascript/checks/CorsCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5122.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5122.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_profile.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_recommended_profile.json

Add hotspot rule S5122 (Cors)

---

eslint-bridge/src/rules/http-endpoint.ts
eslint-bridge/tests/rules/http-endpoint.test.ts

http-endpoint/S4529: highlight only 'listen'

---

javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomRuleRepository.java

This will remove the need for users to add them self `@SonarLintSide`

Improve support of SonarLint for custom rules

---

its/plugin/projects/eslint_based_rules/main.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java

Do not throw when ruleKey for eslint-based rule is not found

---

eslint-bridge/src/analyzer.ts
eslint-bridge/src/linter.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/linter.test.ts
eslint-bridge/tests/server.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java

eslint-bridge: decode issue message containing secondary locations and cost

---

eslint-bridge/src/rules/sql-queries.ts
eslint-bridge/src/rules/xpath.ts
eslint-bridge/tests/rules/sql-queries.test.ts
eslint-bridge/tests/rules/xpath.test.ts
its/ruling/src/test/expected/javascript-S4817.json

Improve security hotspot rules (XPath, SQL query)

---

eslint-bridge/package.json
eslint-bridge/yarn.lock

Use espree 5.0.0

---

javascript-checks/src/main/java/org/sonar/javascript/checks/DefaultParametersNotLastCheck.java
javascript-checks/src/test/resources/checks/DefaultParametersNotLast.js

Fix FP DefaultParametersNotLast (S1788): rest parameter

---

eslint-bridge/src/linter.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/server.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java

eslint-bridge: normalize column index in issue locations

---

eslint-bridge/package.json
eslint-bridge/yarn.lock
its/ruling/src/test/expected/javascript-S1488.json

Update version of eslint-plugin-sonarjs (0.3.0-1)

---

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java

See https://jira.sonarsource.com/browse/SONAR-11670

Remove preview mode from Ruling IT

---

eslint-bridge/pom.xml
its/plugin/plugins/custom-rules-plugin/pom.xml
its/plugin/plugins/deprecated-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTestCustomNodeJS.java
its/pom.xml
its/ruling/pom.xml
javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
nodejs-utils/pom.xml
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/ServerAlreadyFailedException.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBasedRulesSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java

In case of failure log only once

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
travis.sh

update travis utils to version 55

---

.cix.yml

QA: test against DOGFOOD SQ instead of DEV

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3523.html

Fix rule key in deprecation section of S3523

---

eslint-bridge/src/rules/sql-queries.ts
eslint-bridge/tests/rules/sql-queries.test.ts
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2077.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2077.json

Rule S2077: Update rule to raise only on formatted strings

---

javascript-checks/src/test/resources/checks/NullDereference.js
javascript-frontend/src/main/java/org/sonar/javascript/se/ExpressionStack.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SeChecksDispatcher.java
javascript-frontend/src/main/java/org/sonar/javascript/se/SymbolicExecution.java

Fix FP on S2259 - SE: async functions return always a Promise

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/BigProjectTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MetricsTest.java
javascript-checks-testkit/src/main/java/org/sonar/javascript/checks/verifier/BulkVerifier.java
javascript-frontend/src/main/java/org/sonar/javascript/metrics/MetricsVisitor.java
javascript-frontend/src/main/java/org/sonar/javascript/visitors/JavaScriptFileImpl.java
javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/visitors/JavaScriptFile.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/LCOVParser.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java

Remove usage of deprecated APIs

---

eslint-bridge/pom.xml
its/plugin/plugins/custom-rules-plugin/pom.xml
its/plugin/plugins/deprecated-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Bump version to v5.3

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptLanguage.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/SonarWayProfile.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/TypeScriptLanguage.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptLanguageTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TypeScriptLanguageTest.java

Declare TypeScript language

---

.travis.yml

CI: skip travis install step

---

Jenkinsfile
eslint-bridge/pom.xml
its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MultiTsconfigTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestUtils.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
pom.xml

Use NodeJS provided via Jenkinsfile

---

.travis.yml

Send travis notifications on_start

---

its/plugin/projects/tsproject/custom.tsconfig.json
its/plugin/projects/tsproject/fileUsedInCustomTsConfig.ts
its/plugin/projects/tsproject/tsconfig.json
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

 Support property to define tsconfig file

---

eslint-bridge/package.json
eslint-bridge/src/analyzer.ts
eslint-bridge/src/parser.ts
eslint-bridge/src/runner/cpd.ts
eslint-bridge/src/runner/metrics.ts
eslint-bridge/src/server.ts
eslint-bridge/src/utils/visitor.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/fixtures/tsx-project/sample.lint.tsx
eslint-bridge/tests/fixtures/tsx-project/tsconfig.json
eslint-bridge/tests/parser.test.ts
eslint-bridge/tests/runner/cpd.test.ts
eslint-bridge/tests/runner/fixtures/executableLines.lint.ts
eslint-bridge/tests/runner/metrics.test.ts
eslint-bridge/tests/server.test.ts
eslint-bridge/tests/utils/visitor.test.ts
eslint-bridge/yarn.lock
its/plugin/projects/tsproject/duplication.lint.ts
its/plugin/projects/tsproject/nosonar.lint.ts
its/plugin/projects/tsproject/tsconfig.json
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Provide copy-paste detection and size metrics for TypeScript

---

eslint-bridge/src/runner/metrics.ts
eslint-bridge/tests/runner/metrics.test.ts
eslint-bridge/tests/server.test.ts
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Provide cyclomatic complexity metrics for TypeScript

---

its/plugin/projects/nested-tsproject/tsproject/package-lock.json
its/plugin/projects/nested-tsproject/tsproject/package.json
its/plugin/projects/nested-tsproject/tsproject/sample.lint.ts
its/plugin/projects/nested-tsproject/tsproject/tsconfig.json
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/LookupTypeScriptTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilder.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java

Lookup typescript from property or filesystem and set NODE_PATH

---

eslint-bridge/src/analyzer.ts
eslint-bridge/tests/analyzer.test.ts
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestUtils.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Support TypeScript analysis in SonarLint context

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTestCustomNodeJS.java

This failure happens because we are running the analysis twice in the test, we cannot simply stop the engine, because the second analysis would fail. By using concurrent collection we can avoid `ConcurrentModificationException` even if logs are modified asynchronously.

Fix flaky test - SonarLintTestCustomNodeJS

---

sonar-javascript-plugin/src/main/resources/static/documentation.md

Add static analyzer documentation

---

javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomRuleRepository.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptChecks.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java

Deprecate custom rules

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptChecks.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java

Print deprecation warning only when custom rules are used

---

javascript-checks/src/main/java/org/sonar/javascript/checks/DeadStoreCheck.java
javascript-checks/src/test/resources/checks/DeadStore.js

Fix ClassCastException in DeadStoreCheck

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java

Support also TS property `sonar.typescript.exclusions`

---

.github/workflows/dogfood.yml

Add dogfood merge

---

.github/workflows/dogfood.yml

Point dogfood to dogfood-on-peach branch

---

eslint-bridge/src/analyzer.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/fixtures/js-project/fileWithBom.lint.js
its/plugin/projects/project-with-bom/fileWithBom.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithBOMTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java

Fix analysis of files with BOM character

---

eslint-bridge/package.json
eslint-bridge/yarn.lock
its/ruling/src/test/expected/js/js-project/javascript-S2814.json

Backport of #1635 for bugfix 6.0.1

Rely on eslint 5.16

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Backport of #1658 for bugfix 6.0.1

Mention possibility to install supported TypeScript version in logs

---

eslint-bridge/src/analyzer.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/fixtures/js-project/fileWithBom.lint.js
its/plugin/projects/project-with-bom/fileWithBom.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithBOMTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java

Backport of #1646 for bugfix release

Fix analysis of files with BOM character (#1649)

---

.cirrus/nodejs-12.Dockerfile
.cirrus/nodejs-lts.Dockerfile

See fix in the base image https://github.com/SonarSource/buildTools/commit/859762b55dd1a508ebdec406b6cdd9ae22e8fbde

Fix PR coverage

---

its/plugin/projects/(dir with paren)/eslint_based_rules/main.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java

Quote arguments when invoking node

---

eslint-bridge/src/runner/symbol-highlighter.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/runner/symbol-highlighter.test.ts

Highlight curly brackets

---

eslint-bridge/src/server.ts
eslint-bridge/src/tsconfig.ts
eslint-bridge/tests/server.test.ts
eslint-bridge/tests/tsconfig.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigFile.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigFileTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/missingTs.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/tsConfigError.js

Check for missing typescript error when getting files by tsconfig

---

eslint-bridge/package.json
eslint-bridge/yarn.lock
nodejs-utils/src/main/java/org/sonarsource/nodejs/BundlePathResolver.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilder.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
nodejs-utils/src/test/resources/package/node_modules/run-node/run-node
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BundleImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/resources/package/node_modules/run-node/run-node

Rely on run-node for MacOS

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Add UI warning if TypeScript is missing

---

eslint-bridge/src/rules/no-dead-store.ts
eslint-bridge/tests/rules/no-dead-store.test.ts
its/ruling/src/test/expected/ts/console/typescript-S1854.json
its/ruling/src/test/expected/ts/emission/typescript-S1854.json

Implement exception for destructuring pattern with rest

S1854 add destructuring exception to deadstore

---

eslint-bridge/src/rules/cyclomatic-complexity.ts
eslint-bridge/src/rules/deprecation.ts
eslint-bridge/src/rules/file-header.ts
eslint-bridge/src/rules/no-dead-store.ts
eslint-bridge/src/rules/no-parameter-reassignment.ts
eslint-bridge/src/rules/no-return-type-any.ts
eslint-bridge/src/rules/no-try-promise.ts
eslint-bridge/src/rules/no-undefined-argument.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/MissingTypeScriptException.java

Some files were using windows EOL which was fixed

Fix code smells

---

.cirrus.yml
.cirrus/nodejs-12.Dockerfile
.cirrus/nodejs-lts.Dockerfile

Fix maven cache issue

---

eslint-bridge/src/rules/eval-or-arguments-use.ts
eslint-bridge/tests/rules/eval-or-arguments-use.test.ts

Fix eval-or-arguments-use undefined foreach

---

eslint-bridge/src/server.ts
eslint-bridge/tests/server.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Implement close endpoint to request termination of eslint-bridge server

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/LCOVParser.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java
sonar-javascript-plugin/src/test/resources/coverage/reports/report_with_unresolved_path.lcov

Log in debug all unresolved paths in coverage report

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/EslintReportSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/TslintReportSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/EslintReportSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/TslintReportSensorTest.java

Add debug logs when importing external issues report

---

eslint-bridge/src/rules/nested-control-flow.ts
eslint-bridge/tests/rules/nested-control-flow.test.ts

Fix issue location for S134

---

eslint-bridge/src/rules/function-inside-loop.ts
eslint-bridge/tests/rules/function-inside-loop.test.ts

Allow "each" call back function in S1515

---

eslint-bridge/src/parser.ts
eslint-bridge/tests/parser.test.ts
its/plugin/projects/tsproject-no-typescript/file2.ts

Log warning about too new version of TypeScript only once

---

.cirrus.yml

Update github token

---

nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java

Always look for TypeScript in SonarLint context

---

.github/workflows/release.yml

Update release workflow [skip-ci]

---

eslint-bridge/src/rules/arrow-function-convention.ts
eslint-bridge/tests/rules/arrow-function-convention.test.ts
its/ruling/src/test/expected/ts/console/typescript-S3524.json
its/ruling/src/test/expected/ts/desktop/typescript-S3524.json

S3524 Fix FPs for arrow-function-convention: 'async' keyword, generics

---

nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Reduce noise of SCA reports

---

eslint-bridge/pom.xml
eslint-bridge/src/parser.ts
eslint-bridge/tests/parser.test.ts

Log used at analysis runtime TypeScript version

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CustomRulesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java
its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/resources/static/documentation.md

Remove dependency on SonarTS

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptChecks.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java

Avoid using SonarJS name

---

eslint-bridge/src/parser.ts
eslint-bridge/tests/parser.test.ts

Use babel-eslint when parsing VueJS

---

eslint-bridge/src/linter.ts
eslint-bridge/src/rules/no-unused-expressions-ignore-chai-assertions.ts
eslint-bridge/src/utils/decorators.ts
eslint-bridge/tests/rules/no-unused-expressions.test.ts
eslint-bridge/tests/utils/decorators.test.ts
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java

Fix S905 FP with optional chaining

---

eslint-bridge/src/linter.ts
eslint-bridge/src/rules/no-unused-expressions-decorator.ts
eslint-bridge/src/utils/decorators.ts
eslint-bridge/tests/rules/no-unused-expressions.test.ts
its/ruling/src/test/expected/js/p5.js/javascript-S905.json

Fix S905 FP with negated IIFE

---

eslint-bridge/src/rules/sonar-no-unused-vars.ts
eslint-bridge/tests/rules/sonar-no-unused-vars.test.ts

Fix FP S1481(no-unused-vars): jsx components

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java

Merge JavaScript and TypeScript settings in UI

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java

Fixes #2023 
needs #2028 to be merged before

Improve UX around language-specific exclusion property

---

eslint-bridge/src/analyzer.ts
eslint-bridge/src/linter.ts
eslint-bridge/src/server.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/linter.test.ts
eslint-bridge/tests/runner/symbol-highlighter.test.ts
eslint-bridge/tests/server.test.ts
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js

Initialize Linter only once

---

sonar-javascript-plugin/pom.xml

For me locally size of the plugin is slightly below min

Fix size limits of plugin

---

eslint-bridge/src/rules/file-uploads.ts
eslint-bridge/src/rules/utils.ts
eslint-bridge/tests/rules/file-uploads.test.ts

Rule S2598: support 'multer'

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/resources/static/documentation.md

Require Node 10

---

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/SizeAssessor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/SizeAssessorTest.java

Issue 2037: Exclude huge files from analysis

---

eslint-bridge/src/linter.ts
eslint-bridge/src/parser.ts
eslint-bridge/src/rules/bitwise-operators.ts
eslint-bridge/src/rules/deprecation.ts
eslint-bridge/src/rules/no-alphabetical-sort.ts
eslint-bridge/src/rules/no-implicit-dependencies.ts
eslint-bridge/src/rules/no-invalid-await.ts
eslint-bridge/src/rules/no-misleading-array-reverse.ts
eslint-bridge/src/rules/no-return-type-any.ts
eslint-bridge/src/rules/no-try-promise.ts
eslint-bridge/src/rules/no-undefined-argument.ts
eslint-bridge/src/rules/no-useless-intersection.ts

Issue 2070: Remove dynamic `require('typescript')`.

---

eslint-bridge/src/tsconfig.ts
eslint-bridge/tests/tsconfig.test.ts
its/plugin/projects/solution-tsconfig/package-lock.json
its/plugin/projects/solution-tsconfig/package.json
its/plugin/projects/solution-tsconfig/src/file.ts
its/plugin/projects/solution-tsconfig/src/unlisted.ts
its/plugin/projects/solution-tsconfig/tsconfig.app.json
its/plugin/projects/solution-tsconfig/tsconfig.json
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigFile.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigFileTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
sonar-javascript-plugin/src/test/resources/solution-tsconfig/src/tsconfig.app.json
sonar-javascript-plugin/src/test/resources/solution-tsconfig/src/tsconfig.app2.json
sonar-javascript-plugin/src/test/resources/solution-tsconfig/tsconfig.json

Support references in tsconfig

---

eslint-bridge/src/rules/no-implicit-dependencies.ts
eslint-bridge/src/server.ts
eslint-bridge/src/tsconfig.json

Use recommended settings in tsconfig for Node 10

---

eslint-bridge/pom.xml
its/plugin/plugins/custom-rules-plugin/pom.xml
its/plugin/plugins/deprecated-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Prepare for next development iteration (6.5.0)

Prepare for next development iteration

---

.github/workflows/release.yml

Update to release action workflow v2

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java

Apply the maximum size filter only to JS/TS files

---

eslint-bridge/pom.xml
its/plugin/plugins/custom-rules-plugin/pom.xml
its/plugin/plugins/deprecated-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Bugfix release 6.4.1

---

eslint-bridge/src/rules/main.ts
eslint-bridge/src/rules/void-use.ts
eslint-bridge/tests/rules/void-use.test.ts
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3735.json
javascript-checks/src/test/resources/checks/VoidUse.js

 Migrate S3735 to eslint based implementation

---

eslint-bridge/bin/server
eslint-bridge/src/context.ts
eslint-bridge/src/linter.ts
eslint-bridge/tests/context.test.ts
eslint-bridge/tests/linter.test.ts
its/plugin/plugins/eslint-custom-rules-plugin/bundle/rules.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintCustomRulesTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js

Provide context with work directory to rules

---

eslint-bridge/bin/server
eslint-bridge/src/server.ts
eslint-bridge/tests/server.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/badResponse.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/logging.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/missingTs.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/timeout.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/tsConfigError.js

Fix SSF-122

---

eslint-bridge/src/rules/unused-import.ts
eslint-bridge/tests/rules/unused-import.test.ts

Fix FP on S1128 for "jsx" import used in "Emotion" pragma

---

pom.xml
sonar-javascript-plugin/pom.xml

Add minimal supported Node.js version to plugin manifest for SonarLint

---

eslint-bridge/src/rules/sonar-no-fallthrough.ts
eslint-bridge/tests/rules/sonar-no-fallthrough.test.ts

Fix FP on S128 when 'process.exit' is called

---

nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java

Add warning when using EOL version of Node.js

---

.cirrus.yml

Increase 'CIRRUS_CLONE_DEPTH' for ITs

---

its/ruling/src/test/expected/js/es5-shim/javascript-S4619.json
javascript-checks/src/main/java/org/sonar/javascript/checks/NoInMisuseCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4619.json

Rule S4619: "in" operator should not be used on array

---

javascript-checks/src/main/java/org/sonar/javascript/checks/TryPromiseCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4822.json

Rule: Promise rejections should not be caught by 'try' block

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NetUtils.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/badResponse.js
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/logging.js

Use loopback host address also for requests

---

its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1451.json
its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3798.json
its/ruling/src/test/expected/js/javascript-test-sources/javascript-S4123.json
javascript-checks/src/main/java/org/sonar/javascript/checks/NoInvalidAwaitCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4123.json

RuleS4123 : await should only be used with promises

---

javascript-checks/src/main/java/org/sonar/javascript/checks/PreferPromiseShorthandCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4634.json

Add rule S4634 (prefer-promise-shorthand) for JS

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

In case of failure proper exception is raised by caller.

Remove noisy log from isAlive()

---

eslint-bridge/src/rules/no-require-or-define.ts
eslint-bridge/src/rules/utils.ts
eslint-bridge/tests/rules/no-require-or-define.test.ts
its/ruling/src/test/expected/js/jshint/javascript-S3533.json
javascript-checks/src/test/java/org/sonar/javascript/checks/CheckListTest.java

Enhance S3533 with type information

---

eslint-bridge/bin/server
eslint-bridge/src/context.ts
eslint-bridge/src/parser.ts
eslint-bridge/tests/context.test.ts
eslint-bridge/tests/linter.test.ts
eslint-bridge/tests/parser.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js

Add property to disable parsing JavaScript files with TS compiler

---

eslint-bridge/src/rules/in-operator-type-error.ts
eslint-bridge/src/rules/strings-comparison.ts
eslint-bridge/src/rules/unverified-certificate.ts

Fixes #2248
Fixes #2251
Fixes #2250

Set missing parameter for rules using secondary locations

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MetricsTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MinifiedFilesTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MultiTsconfigTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithBOMTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithDifferentEncodingTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/Tests.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java

ITs: Remove use of orchestrator.resetData()

---

eslint-bridge/src/rules/new-operator-misuse.ts

Fix FP on S2999 when instantiating 'this'

---

its/ruling/src/test/expected/js/angular.js/javascript-S3800.json

Consequence of merging #2253 before rebase.

Fix ruling expectations for JS

---

eslint-bridge/src/parser.ts
eslint-bridge/tests/parser.test.ts

Support parsing of non-standard JavaScript decorators

---

eslint-bridge/src/rules/prefer-promise-shorthand.ts
eslint-bridge/tests/rules/prefer-promise-shorthand.test.ts

Improve reporting for prefer-promise-shorthand(S4634)

---

eslint-bridge/src/rules/no-in-misuse.ts
eslint-bridge/tests/rules/no-in-misuse.test.ts

Add exception to S4619 when testing for presence of builtin methods on Array

---

pom.xml
sonar-javascript-plugin/pom.xml

To get rid of illegal reflective access.

Update SSLR to 1.24

---

eslint-bridge/src/rules/x-powered-by.ts
eslint-bridge/tests/rules/x-powered-by.test.ts
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5689.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5689.json

Rule S5689 should be changed to security-hotspot type of issue

---

eslint-bridge/src/rules/certificate-transparency.ts
eslint-bridge/src/rules/content-security-policy.ts
eslint-bridge/src/rules/main.ts
eslint-bridge/src/rules/no-mime-sniff.ts
eslint-bridge/src/rules/no-referrer-policy.ts
eslint-bridge/src/rules/strict-transport-security.ts
eslint-bridge/src/rules/utils-express.ts
eslint-bridge/tests/rules/strict-transport-security.test.ts
javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java
javascript-checks/src/main/java/org/sonar/javascript/checks/StrictTransportSecurityCheck.java
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5739.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5739.json

RSPEC-5739 Disabling Strict-Transport-Security policy is security-sensitive

---

eslint-bridge/src/rules/frame-ancestors.ts
eslint-bridge/tests/rules/frame-ancestors.test.ts

Tiny fix in quotes and a missing `s`.

Replace "directive" by "directives", "none" by "'none'"

---

eslint-bridge/src/rules/no-mixed-content.ts
eslint-bridge/tests/rules/no-mixed-content.test.ts

Fix S5730: Report on sensitive directives property instead of directive

---

eslint-bridge/src/rules/confidential-information-logging.ts
eslint-bridge/tests/rules/confidential-information-logging.test.ts
its/ruling/src/test/expected/js/file-for-rules/javascript-S113.json
its/ruling/src/test/expected/js/file-for-rules/javascript-S2611.json
its/ruling/src/test/expected/js/file-for-rules/javascript-S5757.json
its/sources/file-for-rules/S5757.js

Rule S5757: Ensure issue is raised correctly when no argument is passed to Signale

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java

Change log level to debug when adding security rules to default profile

---

eslint-bridge/src/rules/operation-returning-nan.ts
eslint-bridge/tests/rules/operation-returning-nan.test.ts

Fix highlighting for S3757

---

eslint-bridge/src/rules/operation-returning-nan.ts
eslint-bridge/tests/rules/operation-returning-nan.test.ts

Fix FP on S3757 when using Number wrapper

---

eslint-bridge/src/rules/no-built-in-override.ts
eslint-bridge/tests/rules/no-built-in-override.test.ts
its/ruling/src/test/expected/ts/TypeScript/typescript-S2424.json
its/ruling/src/test/expected/ts/desktop/typescript-S2424.json

Fix FP on S2424 with TypeScript Enum constants

---

eslint-bridge/src/rules/no-in-misuse.ts
eslint-bridge/src/rules/utils.ts
eslint-bridge/tests/rules/no-in-misuse.test.ts
its/plugin/projects/ts-rule-project/S4619.ts
its/ruling/src/test/expected/js/es5-shim/javascript-S4619.json

Improve S4619 to not raise when LHS is number

---

eslint-bridge/src/rules/no-hardcoded-ip.ts
eslint-bridge/tests/rules/no-hardcoded-ip.test.ts

S1313/no-hardcoded-ip: add exception for ipv6 addresses

---

eslint-bridge/src/rules/file-permissions.ts
eslint-bridge/tests/rules/file-permissions.test.ts

Fix rule S2612

---

eslint-bridge/src/rules/no-parameter-reassignment.ts
eslint-bridge/tests/rules/no-parameter-reassignment.test.ts

Fix FP on S1226 when using switch statements

---

eslint-bridge/src/rules/session-regeneration.ts
eslint-bridge/tests/rules/session-regeneration.test.ts

Add exception to S5876

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5042.html
sonarpedia.json

Update rule metadata

---

its/plugin/plugins/eslint-custom-rules-plugin/bundle/rules.js
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintCustomRulesTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/Bundle.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BundleImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/RulesBundles.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/BundleImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/RulesBundlesTest.java

Custom rules should share directory with eslint-bridge

---

its/plugin/projects/esm-project/file.mjs
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ECMAScriptModulesTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptLanguage.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptLanguageTest.java

Support .mjs by default

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java

Deprecate SonarWay Recommended quality profile

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java

This reverts commit 74753784bd368fc3ccebb7e197fd7265e6685841.

Revert "Deprecate SonarWay Recommended quality profile (#2478)"

---

eslint-bridge/pom.xml
its/plugin/plugins/custom-rules-plugin/pom.xml
its/plugin/plugins/deprecated-custom-rules-plugin/pom.xml
its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks-testkit/pom.xml
javascript-checks/pom.xml
javascript-frontend/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

 Update nodeJsMinVersion in manifest to 10.12.0

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java

Increase default eslint-bridge timeout to 5min

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Don't throw exception when missing tsconfig

---

.cirrus.yml
.cirrus/nodejs-15.Dockerfile
its/plugin/projects/tsproject/tsconfig.json
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java

Log warning when not running on LTS or latest version of Node.js

---

eslint-bridge/src/rules/insecure-jwt-token.ts
eslint-bridge/tests/rules/insecure-jwt-token.test.ts

Update S5659: add a message on secondary locations

---

eslint-bridge/src/rules/unverified-certificate.ts
eslint-bridge/src/utils/secondary-locations.ts
eslint-bridge/tests/rules/unverified-certificate.test.ts

Update S4830: add a message on secondary locations

---

eslint-bridge/src/rules/no-invariant-returns.ts
eslint-bridge/tests/rules/no-invariant-returns.test.ts

Update S3516: add a message on secondary locations

---

eslint-bridge/src/rules/use-type-alias.ts
eslint-bridge/tests/rules/use-type-alias.test.ts

Update S4323: add a message on secondary locations

---

eslint-bridge/src/rules/arguments-usage.ts
eslint-bridge/tests/rules/arguments-usage.test.ts

Update S3513: add a message on secondary locations

---

eslint-bridge/src/rules/unverified-hostname.ts
eslint-bridge/src/utils/secondary-locations.ts
eslint-bridge/tests/rules/unverified-hostname.test.ts

Update S5527: add a message on secondary locations

---

pom.xml

Update Guava to latest version (v.30.1.1)

---

eslint-bridge/src/rules/function-return-type.ts
eslint-bridge/tests/rules/function-return-type.test.ts

Fix highlighting on S3800 for FunctionLike declarations

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3353.html

Fix code sample in S3353 description

---

eslint-bridge/src/rules/function-inside-loop.ts
eslint-bridge/tests/rules/function-inside-loop.test.ts

Update S1515: update message and add secondary location

---

eslint-bridge/src/rules/switch-without-default.ts
eslint-bridge/tests/rules/switch-without-default.test.ts
its/ruling/src/test/expected/js/angular.js/javascript-S131.json
its/ruling/src/test/expected/js/javascript-test-sources/javascript-S131.json
its/ruling/src/test/expected/js/jshint/javascript-S131.json
its/ruling/src/test/expected/js/p5.js/javascript-S131.json

Adjust the behavior of S131 to not raise an issue when default is not at the correct position

---

javascript-checks/src/main/java/org/sonar/javascript/checks/NoMagicNumbersCheck.java
javascript-checks/src/test/java/org/sonar/javascript/checks/NoMagicNumbersCheckTest.java

Improve S109 by ignoring readonly class properties for TS

---

eslint-bridge/src/rules/xpath.ts
eslint-bridge/tests/rules/xpath.test.ts

FP on S4817: Do not raise issue on hardcoded strings

---

eslint-bridge/src/linter.ts
eslint-bridge/src/rules/accessor-pairs-decorator.ts
eslint-bridge/tests/rules/accessor-pairs-decorator.test.ts

Improve S2376 by ignoring setters decorated with Angular @Input() decorator

---

eslint-bridge/src/rules/insecure-jwt-token.ts
eslint-bridge/src/utils/ast-shape.ts
eslint-bridge/tests/rules/insecure-jwt-token.test.ts

S5659 should not raise when publicKey is defined and algorithms property is missing

---

eslint-bridge/src/rules/no-useless-intersection.ts
eslint-bridge/tests/rules/no-useless-intersection.test.ts

Fix FP on S4335 when interfaces have computed properties

---

eslint-bridge/src/rules/conditional-indentation.ts
eslint-bridge/tests/rules/conditional-indentation.test.ts

S3973 / conditional-indentation: FP on else statements with braces

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptExclusionsFileFilterTest.java

Ignore d.ts files from analysis

---

eslint-bridge/src/linter.ts
eslint-bridge/src/rules/no-redeclare-decorator.ts
eslint-bridge/tests/rules/no-redeclare.test.ts

S2814/no-redeclare: avoid FP on type declaration

---

eslint-bridge/src/rules/strings-comparison.ts
eslint-bridge/tests/rules/strings-comparison.test.ts
its/ruling/src/test/expected/ts/TypeScript/typescript-S3003.json
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3003.html

Fix FP on S3003 by not raising on lexicographic sort

---

sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLint.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLintTest.java

Generate static file with rule metadata for SonarLint

---

eslint-bridge/src/rules/no-inconsistent-returns.ts
eslint-bridge/tests/rules/no-inconsistent-returns.test.ts

S3801/no-inconstinent-return: avoid FP when functions returns never

---

eslint-bridge/bin/server
eslint-bridge/src/analyzer.ts
eslint-bridge/src/context.ts
eslint-bridge/src/runner/metrics.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/context.test.ts
eslint-bridge/tests/linter.test.ts
eslint-bridge/tests/parser.test.ts
eslint-bridge/tests/runner/symbol-highlighter.test.ts
eslint-bridge/tests/server.test.ts
its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBridgeIntegrationTest.java
pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/startServer.js

Add analysis option to not compute metrics for SonarLint

---

.cirrus.yml
.github/workflows/release.yml

Fix release v3 workflow

---

pom.xml

Update sslr-squid-bridge to 2.7.1

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

TypeScript sensor should skip analysis if no input files are found

---

sonar-javascript-plugin/src/main/resources/org/sonar/l10n/typescript/rules/tslint-sonarts/rules.json
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/TslintRulesDefinitionTest.java

Use permalinks for tslint-sonarts rule descriptions

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4784.html

Fix rule key in rule description for S4784

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java

Log deprecation when Node.JS 10 or 15 is used

---

eslint-bridge/package.json
eslint-bridge/yarn.lock

Fixes #2238 
Actual fix is provided by https://github.com/SonarSource/eslint-plugin-sonarjs/pull/219 as the rule is provided by eslint-plugin-sonarjs

Ignore React functional components for cognitive complexity rule

---

eslint-bridge/src/linter.ts
eslint-bridge/tests/linter.test.ts

Fail hard when issue message can't be decoded

---

eslint-bridge/src/runner/highlighter.ts
eslint-bridge/tests/runner/highlighter.test.ts

Add syntax highlighting for regex literals

---

eslint-bridge/src/rules/regex-rule-template.ts
eslint-bridge/src/utils/utils-regex.ts
eslint-bridge/src/utils/utils-string-literal.ts
eslint-bridge/tests/rules/no-empty-group.test.ts
eslint-bridge/tests/rules/regex-rule-template.test.ts
eslint-bridge/tests/utils/utils-string-literal.test.ts

Use precise issue location for string literals used as regexp

---

eslint-bridge/src/rules/unused-import.ts
eslint-bridge/tests/fixtures/unused-import/sample.lint.tsx
eslint-bridge/tests/fixtures/unused-import/tsconfig.json
eslint-bridge/tests/rules/unused-import.test.ts

FP S1128: ignore unused imported symbols denoting JSX factories and JSX fragment factories

---

eslint-bridge/src/rules/post-message.ts
eslint-bridge/tests/rules/post-message.test.ts
its/ruling/src/test/expected/js/jStorage/javascript-S2819.json
its/ruling/src/test/expected/js/javascript-test-sources/javascript-S2819.json
its/ruling/src/test/expected/js/qunit/javascript-S2819.json

Fix FP S2819: only raise on the message type of event

---

eslint-bridge/src/runner/cpd.ts
eslint-bridge/tests/runner/cpd.test.ts

Preserve string literals inside JSX attributes on CPD computation

---

eslint-bridge/package.json
eslint-bridge/src/parser.ts
eslint-bridge/tests/parser.test.ts
eslint-bridge/yarn.lock
sonar-javascript-plugin/pom.xml

Enable support of JavaScript experimental class properties with Babel parser

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/ProcessWrapper.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/ProcessWrapperImpl.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/StreamConsumer.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/ProcessWrapperImplTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java

Fix SSF-181

---

.github/workflows/release.yml

This reverts commit dd8dc959cf00cb2bcc5d2772f349218269ca12ee.

Revert "Temporarily disable release action (#2765)"

---

.cirrus.yml

see also https://jira.sonarsource.com/browse/BUILD-1104 for details

[CI] Use 15 cpu for build

---

eslint-bridge/src/rules/unused-named-groups.ts
eslint-bridge/src/utils/utils-ast.ts
eslint-bridge/tests/rules/unused-named-groups.test.ts

Fix FP S5860: consider group references through destructuring

---

eslint-bridge/src/rules/sonar-no-control-regex.ts
eslint-bridge/tests/rules/sonar-no-control-regex.test.ts

Improve S6324: include the control character in the issue message

---

eslint-bridge/src/rules/stateful-regex.ts
eslint-bridge/tests/rules/stateful-regex.test.ts

Fix FP S6351: reseting the regex with empty literal

---

eslint-bridge/pom.xml
eslint-bridge/tests/tsconfig.json

Analysis currently pick-ups tsconfig files from test folders. We should only use tsconfig file of the eslint-bridge project.
Before
```
[INFO] Sensor TypeScript analysis [javascript]
[INFO] Deploying custom rules bundle jar:file:/home/sonarsource/.sonar/cache/1f49fb4b8d2a6e35d7649f00d85269ed/sonar-securityjsfrontend-plugin.jar!/js-vulnerabilities-rules-1.0.0.tgz to /tmp/cirrus-ci-build/target/sonar/.sonartmp/eslint-bridge-bundle/package/custom-rules14275211187618126069
[INFO] Found 13 tsconfig.json file(s): [/tmp/cirrus-ci-build/eslint-bridge/tests/tsconfig.json, /tmp/cirrus-ci-build/eslint-bridge/tests/fixtures/vue-project-tsconfig-implicit/tsconfig.json, /tmp/cirrus-ci-build/eslint-bridge/tests/fixtures/unused-import/tsconfig.json, …
```

[CI] configure tsconfigPath explicitly

---

eslint-bridge/tests/analyzer.test.ts

Also fixing one test (one more token to highlight is `// nosonar` comment)

Remove '.only' from 'analyzer' test

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Disable TLS initialization in okhttp

---

eslint-bridge/src/rules/no-unused-expressions-decorator.ts
eslint-bridge/tests/rules/no-unused-expressions.test.ts

Fix FP S905: should not raise on Aura Lightning Components

---

eslint-bridge/src/linter.ts
eslint-bridge/src/rules/object-shorthand-decorator.ts
eslint-bridge/tests/rules/object-shorthand-decorator.test.ts

Improve S3498: fix FP for Aura Lightning Components and change location highlighting

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBridgeIntegrationTest.java
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Remove okhttp and use HttpClient from jdk

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/metrics/CssMetricSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CssRuleSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/metrics/CssMetricSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/CssRuleSensorTest.java

Declare CSS sensors as sensors processing files independently

---

eslint-bridge/tests/server.test.ts

we should really implement https://github.com/SonarSource/SonarJS/issues/2861 :)

Fix test - remove `only` and increase timeout

---

eslint-bridge/src/rules/no-try-promise.ts
eslint-bridge/src/rules/void-use.ts
eslint-bridge/src/utils/utils-type.ts
eslint-bridge/tests/rules/void-use.test.ts

Ignore promises in S3735 void-use

---

eslint-bridge/src/rules/null-dereference.ts
eslint-bridge/tests/rules/null-dereference.test.ts

FP S2259: Ignore optional chaining

---

eslint-bridge/src/linter.ts
eslint-bridge/src/quickfix.ts
eslint-bridge/tests/linter.test.ts
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java

Support quickfixes from ESLint suggestions

---

eslint-bridge/src/runner/cpd.ts
eslint-bridge/tests/analyzer.test.ts
eslint-bridge/tests/runner/cpd.test.ts

Exclude import statements from duplication computation

---

eslint-bridge/src/rules/post-message.ts
eslint-bridge/tests/rules/post-message.test.ts

Update message for S2819 ('post-message')

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java

Introduce back sonar.typescript.lcov.reportPaths as alias for sonar.javascript.lcov.reportPaths

---

.cirrus.yml
pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/CssRulesDefinition.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/metrics/CssMetricSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CssRuleSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/JavaScriptRulesDefinition.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/TypeScriptRulesDefinition.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLint.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/CssRulesDefinitionTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/metrics/CssMetricSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/CssRuleSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/JavaScriptRulesDefinitionTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/TypeScriptRulesDefinitionTest.java

There is no integration test, it was tested manually by checking the database

Update sonar-analyze-commons and sonar-plugin-api to support OWASP 2021

---

.github/workflows/release.yml

See https://github.com/SonarSource/gh-action_release

Update GitHub release workflow

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/no-redundant-parentheses.ts
eslint-bridge/tests/rules/no-redundant-parentheses.test.ts

Add quick fix for S1110 (no-redundant-parentheses)

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/no-alphabetical-sort.ts
eslint-bridge/tests/rules/no-alphabetical-sort.test.ts

Add quick fix for S2871 ('no-alphabetical-sort')

---

eslint-bridge/src/quickfix.ts

Enable quick fix for S6325 ('prefer-regex-literals')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/no-in-misuse.ts
eslint-bridge/tests/rules/no-in-misuse.test.ts

Add quick fix for S4619 ('no-in-misuse')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/prefer-type-guard.ts
eslint-bridge/tests/rules/prefer-type-guard.test.ts

Add quick fix for S4322 ('prefer-type-guard')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/different-types-comparison.ts
eslint-bridge/tests/rules/different-types-comparison.test.ts

Add quick fix for S3403 ('different-types-comparison')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/unused-import.ts
eslint-bridge/tests/rules/unused-import.test.ts

Add quick fix for S1128 (unused-import)

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/decorators/index.ts
eslint-bridge/src/rules/decorators/no-empty-decorator.ts
eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts
eslint-bridge/tests/rules/decorators/no-empty-decorator.test.ts

Add quick fix for S108 ('no-empty')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/decorators/index.ts
eslint-bridge/src/rules/decorators/use-isnan-decorator.ts
eslint-bridge/tests/rules/decorators/use-isnan-decorator.test.ts

Add quick fix for S2688 ('use-isnan')

---

eslint-bridge/src/linter.ts
eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/decorators/index.ts
eslint-bridge/src/rules/decorators/prefer-for-of-decorator.ts
eslint-bridge/tests/rules/decorators/no-redeclare-decorator.test.ts
eslint-bridge/tests/rules/decorators/prefer-for-of-decorator.test.ts
its/ruling/src/test/expected/ts/console/typescript-S2814.json

Add quick fix for S4138 ('prefer-for-of')

---

eslint-bridge/src/quickfix.ts
eslint-bridge/src/rules/decorators/index.ts
eslint-bridge/src/rules/decorators/no-duplicate-imports-decorator.ts
eslint-bridge/tests/rules/decorators/no-duplicate-imports-decorator.test.ts

Add quick fix for S3863 ('no-duplicate-imports-decorator')

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/rules/AtRuleNoUnknown.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/rules/CssRuleTest.java

Fixes https://github.com/SonarSource/sonar-css/issues/350
Fixes https://github.com/SonarSource/sonar-css/pull/363

Fix FP S4662 ('at-rule-no-unknown'): Ignore Sass @forward rule

---

nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommand.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilder.java
nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java
nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java

Require Node.js 12.22.0

---

javascript-checks/src/test/java/org/sonar/javascript/checks/EmptyFunctionCheckTest.java

Fix FP S1186 ('no-empty-function'): Ignore private constructors

---

eslint-bridge/src/rules/unused-import.ts
eslint-bridge/tests/rules/unused-import.test.ts

Fix FP S1128 ('unused-import'): Generalize imports matching kebab case references

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java

Fix default value of JavaScript execution environments

---

.cirrus.yml
.cirrus/nodejs-12.Dockerfile
.cirrus/nodejs-14.Dockerfile
.cirrus/nodejs-16.Dockerfile

BUILD-1577 migrate to new infra and BUILD-1551 update repox credentials

---

docs/DEV.md
eslint-bridge/package.json
eslint-bridge/tools/newRule.ts

Add `eslint` option to `new-rule` script in eslint-bridge

---

eslint-bridge/pom.xml
its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml

Prepare next development iteration

Prepare next development iteration

---

pom.xml

Upgrade analyzer-commons to 1.26.0.1029

---

eslint-bridge/src/rules/function-return-type.ts
eslint-bridge/tests/rules/function-return-type.test.ts
its/ruling/src/test/expected/js/angular.js/javascript-S3800.json
its/ruling/src/test/expected/js/p5.js/javascript-S3800.json

Rule S3800 should only report on built-in types

---

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1854.html
javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6435.html
sonarpedia.json

Update metadata before release

Update metadata before release

---

eslint-bridge/bin/server
eslint-bridge/src/helpers/index.ts
eslint-bridge/src/helpers/timeout.ts
eslint-bridge/src/server.ts
eslint-bridge/tests/routing/routing.test.ts
eslint-bridge/tests/server.test.ts
its/plugin/tests/src/test/resources/junit-platform.properties
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Add heartbeat keepalive request to eslint bridge

---

eslint-bridge/src/linting/eslint/rules/unused-named-groups.ts
eslint-bridge/tests/linting/eslint/rules/unused-named-groups.test.ts

Fix S5860: FP when regex is accessed with the non-null assertion operator

---

eslint-bridge/src/linting/eslint/rules/no-hardcoded-ip.ts
eslint-bridge/tests/linting/eslint/rules/no-hardcoded-ip.test.ts

Fix S1313: added exception for IP ranges reserved for documentation purposes

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java

There's literally the same test just above.

Remove duplicate test

---

its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/tests/pom.xml
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestCodeAnalysisTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestUtils.java
javascript-checks/pom.xml
nodejs-utils/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/metrics/CssMetricSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/CssRuleSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/QuickFixSupportTest.java

Update sonarqube version to latest and introduce dependency to sonar-plugin-api pointing to latest version.

Update versions of sonar dependencies

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java
its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Fix 'RULE' metric type for performance monitoring

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/Monitoring.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/MonitoringTest.java

Add information to perf monitoring if analysis can skip unchange

---

.cirrus.yml

- [BUILD-1854](https://sonarsource.atlassian.net/browse/BUILD-1854) improve Maven cache
Succesfully tested on this PR with a temp commit

BUILD-1854 Maven cache

---

eslint-bridge/jest.config.js
eslint-bridge/src/linting/eslint/linter/issues/decode.ts
eslint-bridge/src/linting/eslint/linter/issues/transform.ts
eslint-bridge/src/linting/eslint/linter/wrapper.ts
eslint-bridge/tests/linting/eslint/linter/issues/decode.test.ts
eslint-bridge/tests/linting/eslint/linter/issues/transform.test.ts
eslint-bridge/tests/routing/routing.test.ts

Need to merge the ignore of ucfg "issues" to have sonar-security pass QA testing
https://github.com/SonarSource/sonar-security/pull/3351

Extract ucfg paths from list of issues

---

its/plugin/projects/pr-analysis-cloudformation-branch/file1.yaml
its/plugin/projects/pr-analysis-cloudformation-branch/file2.yaml
its/plugin/projects/pr-analysis-cloudformation-main/file1.yaml
its/plugin/projects/pr-analysis-cloudformation-main/file2.yaml
its/plugin/projects/pr-analysis-js-branch/hello.js
its/plugin/projects/pr-analysis-js-branch/index.js
its/plugin/projects/pr-analysis-js-branch/package.json
its/plugin/projects/pr-analysis-js-main/hello.js
its/plugin/projects/pr-analysis-js-main/index.js
its/plugin/projects/pr-analysis-js-main/package.json
its/plugin/projects/pr-analysis-ts-branch/hello.ts
its/plugin/projects/pr-analysis-ts-branch/index.ts
its/plugin/projects/pr-analysis-ts-branch/package.json
its/plugin/projects/pr-analysis-ts-branch/tsconfig.json
its/plugin/projects/pr-analysis-ts-main/hello.ts
its/plugin/projects/pr-analysis-ts-main/index.ts
its/plugin/projects/pr-analysis-ts-main/package.json
its/plugin/projects/pr-analysis-ts-main/tsconfig.json
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestUtils.java
its/plugin/tests/src/test/resources/pr-analysis-cloudformation.xml

Add cloudformation test case to PR analysis integration tests

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java

Lower log level of heartbeat

---

.cirrus.yml
.cirrus/nodejs.Dockerfile
eslint-bridge/package-lock.json
eslint-bridge/package.json
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java
sonar-javascript-plugin/src/main/resources/static/documentation.md
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java

Fixes #3231 
Fixes #3357
Fixes #3356

Drop Node.js 12 support, deprecate Node.js 14 and recommend Node.js 18

---

eslint-bridge/package-lock.json
eslint-bridge/package.json
eslint-bridge/src/parsing/yaml/parser/parse.ts
eslint-bridge/tests/parsing/yaml/parser/format.test.ts

Replace forked yaml dependency with the original one

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithProgram.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/CssRuleSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/CssRuleSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/YamlSensorTest.java

Log in debug a path to the file being analyzed

---

eslint-bridge/tests/linting/eslint/rules/comment-based/sonar-jsx-no-leaked-render.tsx
eslint-bridge/tests/linting/eslint/rules/comment-based/tsconfig.json
eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts

Extend comment-based testing framework with JSX support

---

eslint-bridge/src/linting/eslint/linter/visitors/metrics/ncloc.ts
eslint-bridge/tests/linting/eslint/linter/visitors/metrics/fixtures/ncloc.vue
eslint-bridge/tests/linting/eslint/linter/visitors/metrics/ncloc.test.ts
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java

Count lines of code in `template` and `style` of `.vue` files

---

eslint-bridge/src/linting/eslint/rules/decorators/index.ts
eslint-bridge/src/linting/eslint/rules/decorators/no-this-alias-decorator.ts
eslint-bridge/tests/linting/eslint/rules/comment-based/no-this-alias.js

Fix FP S4327 ('no-this-alias'): Ignore alias references inside generators

---

eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts
eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts

Fix FP S107 ('sonar-max-params'): Ignore Angular component constructors

---

eslint-bridge/src/linting/eslint/rules/post-message.ts
eslint-bridge/tests/linting/eslint/rules/post-message.test.ts

Fix FP S2819 ('post-message'): Consider arrow functions

---

eslint-bridge/src/linting/eslint/rules/concise-regex.ts
eslint-bridge/tests/linting/eslint/rules/concise-regex.test.ts
its/ruling/src/test/expected/js/p5.js/javascript-S6353.json
its/ruling/src/test/expected/ts/desktop/typescript-S6353.json

Improve S6353 (`concise-regex`): Add special cases for zero or one repetition

---

eslint-bridge/src/linting/eslint/rules/no-redundant-parentheses.ts
eslint-bridge/tests/linting/eslint/rules/no-redundant-parentheses.test.ts

Fix FP S1110 (`no-redundant-parentheses`): Ignore sequence expressions

---

eslint-bridge/src/linting/eslint/rules/post-message.ts

While working on #3426, I noticed that we were visiting the body's AST of the event listener to check whether the event origin was validated. This part of the implementation can be simplified by relying on ESLint Scope API to look for the references of the event parameter and check if it is used to validate the origin. With this change, the rule performance can be improved, especially if it is processing a deep function tree.

Improve S2819 ('post-message'): Use ESLint Scope API instead of visiting the AST

---

eslint-bridge/src/linting/eslint/rules/constructor-for-side-effects.ts
eslint-bridge/tests/linting/eslint/rules/constructor-for-side-effects.test.ts
its/ruling/src/test/expected/ts/moose/typescript-S1848.json

Fix FP S1848 `constructor-for-side-effects`: Ignore standard APIs that produce side effects

---

eslint-bridge/src/linting/eslint/rules/no-infinite-loop.ts
eslint-bridge/tests/linting/eslint/rules/no-infinite-loop.test.ts

Improve S2189 (`no-infinite-loop`): Report one issue per variable

---

eslint-bridge/src/linting/eslint/rules/inverted-assertion-arguments.ts
eslint-bridge/tests/linting/eslint/rules/comment-based/inverted-assertion-arguments.js

Improve S3415 ('inverted-assertion-arguments'): Report consistent error message

---

eslint-bridge/src/linting/eslint/rules/no-clear-text-protocols.ts
eslint-bridge/tests/linting/eslint/rules/no-clear-text-protocols.test.ts

Fix FP S5332 ('no-clear-text-protocols'): Ignore SES communications

---

eslint-bridge/src/linting/eslint/rules/no-infinite-loop.ts
eslint-bridge/tests/linting/eslint/rules/no-infinite-loop.test.ts

Fixes #2866
I did a bit of refactoring before tackling the scope of the ticket. To help the review, I pushed two different commits: one for the refactoring and the other for the actual fix.

Fix FP S2189 ('no-infinite-loop'): Ignore condition variables called on or passed over

---

eslint-bridge/src/linting/eslint/rules/no-parameter-reassignment.ts
eslint-bridge/tests/linting/eslint/rules/no-parameter-reassignment.test.ts
its/ruling/src/test/expected/js/jquery/javascript-S1226.json
its/ruling/src/test/expected/js/p5.js/javascript-S1226.json
its/ruling/src/test/expected/js/paper.js/javascript-S1226.json
its/ruling/src/test/expected/js/sizzle/javascript-S1226.json

Fix FP S1226 (`no-parameter-reassignment`): Allow inside if statements

---

eslint-bridge/src/linting/eslint/rules/aws-s3-bucket-granted-access.ts
eslint-bridge/src/linting/eslint/rules/aws-s3-bucket-insecure-http.ts
eslint-bridge/src/linting/eslint/rules/aws-s3-bucket-public-access.ts
eslint-bridge/src/linting/eslint/rules/aws-s3-bucket-server-encryption.ts
eslint-bridge/src/linting/eslint/rules/aws-s3-bucket-versioning.ts
eslint-bridge/src/linting/eslint/rules/helpers/aws/cdk.ts
eslint-bridge/src/linting/eslint/rules/helpers/aws/index.ts
eslint-bridge/src/linting/eslint/rules/helpers/aws/s3.ts
eslint-bridge/src/linting/eslint/rules/helpers/module.ts
eslint-bridge/tests/linting/eslint/rules/helpers/aws/cdk.test.ts
eslint-bridge/tests/linting/eslint/rules/helpers/aws/s3.test.ts

Create a rule template for AWS CDK rules

---

eslint-bridge/src/linting/eslint/rules/unused-import.ts
eslint-bridge/tests/linting/eslint/rules/comment-based/tsconfig.json
eslint-bridge/tests/linting/eslint/rules/comment-based/unused-import.vue
eslint-bridge/tests/tools/testers/comment-based/framework.test.ts
eslint-bridge/tests/tools/testers/comment-based/framework.ts
eslint-bridge/tests/tools/testers/comment-based/helpers/comments.ts
eslint-bridge/tests/tools/testers/comment-based/helpers/file.ts
eslint-bridge/tests/tools/testers/comment-based/launcher.test.ts
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptFilePredicate.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptFilePredicateTest.java

Fix FP S1128 (`unused-imports`): Vue.js imports used in templates

---

eslint-bridge/src/linting/eslint/rules/post-message.ts
eslint-bridge/tests/linting/eslint/rules/post-message.test.ts

Fix FP S2819 (`post-message`): Consider origin validation through `event.originalEvent`

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java

Fixes #3431 
Tested manually. 
reproduced
fixed
Note that this is not the way VS Code recommends to work with WSL. Proper way to work with wsl is to use Remote development extension and to open project within WSL with SonarLint installed inside the WSL workspace.

Workaround for bug on WSL when discovering tsconfig

---

javascript-checks/src/main/java/org/sonar/plugins/javascript/api/RulesBundle.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/Monitoring.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/PluginInfo.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/RulesBundles.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheKey.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategies.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/RulesBundlesTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/cache/CacheKeyTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategyTest.java

Add bundle version to `RulesBundle` interface and use it for cache key

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/OrchestratorStarter.java
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java

Rename the test case branch to match the new SonarQube default branch naming.

Rename test case branch to match new SonarQube default branch naming

---

eslint-bridge/src/linting/eslint/rules/helpers/ast.ts
eslint-bridge/src/linting/eslint/rules/helpers/module.ts
eslint-bridge/tests/linting/eslint/rules/helpers/aws/cdk.test.ts

Support estree.Node and TSESTree.Node in new helpers
Support TSNonNullExpression and ChainExpression when traversing FQN

Normalize helper nodes

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/filter/BundleAssessor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilter.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java

Feature was introduced in #3499

Fix logging when bundled code is detected

---

eslint-bridge/src/linting/eslint/rules/helpers/ast.ts
eslint-bridge/src/linting/eslint/rules/helpers/module.ts

Look for variable definition in the proper scope, instead of always in the lower scope

Fix FQN helper

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestCodeAnalysisTest.java

Add `@Isolated` annotation to execute `TestCodeAnalysisTest` separately from other tests.

Execute `TestCodeAnalysisTest` in isolation to avoid flakiness

---

its/plugin/projects/css-sonarlint-project/file.css
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java

Support analysis of CSS in SonarLint

---

.gitignore

I'll try to update some YML templates.
This will make my life a bit easier

Add `.vs/` to .gitignore

---

.github/workflows/StartProgress.yml

Same as https://github.com/SonarSource/sonar-dotnet/pull/6329

GitHub workflow: Migrate StartProgress to shared action

---

.github/workflows/CreatePullRequest.yml

Same as https://github.com/SonarSource/sonar-dotnet/pull/6333

GitHub workflow: Migrate CreatePullRequest to shared action

---

its/plugin/projects/js-sonarlint-project/file.js
its/plugin/projects/js-sonarlint-project/file.vue
its/plugin/projects/ts-sonarlint-project/file.ts
its/plugin/projects/ts-sonarlint-project/file.vue
its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigProviderTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Create default tsconfig.json file when running in SonarLint

---

.cirrus.star
.cirrus.yml
.cirrus/nodejs.Dockerfile

BUILD-2334 Migrate to CirrusCI on AWS

---

eslint-bridge/src/linting/eslint/rules/helpers/globals.ts
eslint-bridge/tests/linting/eslint/rules/no-built-in-override.test.ts
its/ruling/src/test/expected/ts/TypeScript/typescript-S2424.json

Fix FP S2424 (`no-built-in-override`): Remove System from globals

---

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLint.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLintTest.java

Include CSS rules in SonarLint metadata

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithProgram.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/YamlSensor.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheAnalysisSerialization.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheKey.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategies.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategy.java
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/FileMetadata.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TestUtils.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategyTest.java

Verify cached data with file hash

---

eslint-bridge/src/linting/eslint/rules/helpers/module.ts
eslint-bridge/tests/linting/eslint/rules/helpers/aws/cdk.test.ts

Add support for `import = require`

---

eslint-bridge/src/linting/eslint/rules/sonar-max-lines-per-function.ts
eslint-bridge/tests/linting/eslint/rules/sonar-max-lines-per-function.test.ts

Fix FP S128 (sonar-max-lines-per-function): Improve React functional components detection

---

eslint-bridge/src/linting/eslint/rules/weak-ssl.aws.ts
eslint-bridge/src/linting/eslint/rules/weak-ssl.lib.ts
eslint-bridge/tests/linting/eslint/rules/comment-based/weak-ssl.js

Update S4423 (`weak-ssl`): Change issue message when omitting tlsSecurityPolicy

---

eslint-bridge/pom.xml
its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
javascript-checks/pom.xml
pom.xml
sonar-javascript-plugin/pom.xml
sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/HtmlSensor.java

Fix Html Sensor: Use absolute paths instead of relatives

---

docs/DEV.md
tools/newRule.ts

Following changes in https://github.com/SonarSource/SonarJS/pull/3713, adapt remaining stuff.

Adapt `docs/DEV.md` and `new-rule` script to new folder structure

---

pom.xml
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1481.html

Fixes https://github.com/SonarSource/SonarJS/issues/3718
Fixes https://github.com/SonarSource/SonarJS/issues/3735

SonarJS loads new education rules format with s1481 update

---

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java

Remove node_modules from root of the project when running ruling locally

---

its/ruling/src/test/expected/js/react-cloud-music/javascript-S1472.json
its/ruling/src/test/expected/ts/ag-grid/typescript-S1472.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1472.html
src/linting/eslint/rules/call-argument-line.ts
tests/linting/eslint/rules/call-argument-line.test.ts

Improve S1472 (`call-argument-line`): Template tag should be on the same line as the literal

---

its/ruling/src/test/expected/js/javascript-test-sources/javascript-S4275.json
its/ruling/src/test/expected/js/ocanvas/javascript-S4275.json
its/ruling/src/test/expected/ts/eigen/typescript-S4275.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4275.html
src/linting/eslint/rules/no-accessor-field-mismatch.ts
tests/linting/eslint/rules/no-accessor-field-mismatch.test.ts

Fixes #3702 
RSPEC: SonarSource/RSPEC#1643

Update rule S4275 (no-accessor-field-mismatch): cover cases from ESLint's getter-return

---

its/ruling/src/test/expected/js/jshint/javascript-S2260.json
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractAnalysis.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithProgram.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithWatchProgram.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigFile.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java

Use AnalysisWithProgram and AnalysisWithWatchProgram also in JS sensor

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4326.json
src/linting/eslint/linter/quickfixes/rules.ts
tests/linting/eslint/linter/fixtures/wrapper/quickfixes/no-return-await.js

Improve S4326 (`no-return-await`): Add quickfix support

---

pom.xml

inspired by https://github.com/SonarSource/sonar-cobol/commit/a344e35ae814f74d3a38b2fc140c0bd7b899709f

Upgrade sonar and sonar-plugin-api dependencies (to fix ruling tests for SQ 10 release)

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4043.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4043.json
src/linting/eslint/linter/quickfixes/rules.ts
src/linting/eslint/rules/no-misleading-array-reverse.ts
tests/linting/eslint/linter/fixtures/wrapper/quickfixes/no-misleading-array-reverse.js
tests/linting/eslint/rules/no-misleading-array-reverse.test.ts

Update S4043 (`no-misleading-array-reverse`): Add quickfix support

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1528.json
src/linting/eslint/linter/quickfixes/rules.ts
src/linting/eslint/rules/array-constructor.ts
tests/linting/eslint/linter/fixtures/wrapper/quickfixes/array-constructor.js
tests/linting/eslint/rules/array-constructor.test.ts

Update S1528 (`array-constructor`): add quickfix

---

src/linting/eslint/rules/unused-import.ts
tests/linting/eslint/rules/unused-import.test.ts

Fix FP S1128 (`unused-import`): Support usage in JSDoc comments

---

src/helpers/tsconfigs.ts
tests/helpers/tsconfigs.test.ts

After 3 attempts with found tsconfig.js, try already with fallback tsconfig

Limit tsconfigs lookup

---

src/errors/error.ts
src/helpers/escape.ts
tests/helpers/escape.test.ts

Escape non-ascii characters in error message

---

its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
pom.xml
sonar-plugin/css/pom.xml
sonar-plugin/javascript-checks/pom.xml
sonar-plugin/pom.xml
sonar-plugin/sonar-javascript-plugin/pom.xml

Prepare bugfix release 10.3.1

---

typedoc/typedoc.js

Fix typedoc after moving folders

Fix typedoc - new folder locations

---

.cirrus.yml

BUILD-2428 Use c6id.2xlarge machines for windows tasks

---

packages/jsts/tests/tools/sonar-runtime/rule/no-missing-sonar-runtime.test.ts
packages/jsts/tests/tools/sonar-runtime/rule/no-missing-sonar-runtime.ts
packages/jsts/tests/tools/sonar-runtime/sonar-runtime.test.ts

Fix sonar-runtime test

---

packages/jsts/src/rules/S2871/rule.ts
packages/jsts/src/rules/S2871/unit.test.ts

Fix QF S2871: Remove the lexicographic suggestion for string arrays

---

packages/jsts/src/rules/S4721/rule.ts
packages/jsts/src/rules/S4721/unit.test.ts

Fix FP S4721: Ignore static template literals

---

packages/jsts/src/rules/S4123/rule.ts
packages/jsts/src/rules/S4123/unit.test.ts

Fix FP S4123 (`no-invalid-await`): do not raise issue for `unknown` type

---

its/ruling/src/test/expected/ts/TypeScript/typescript-S107.json
packages/jsts/src/rules/S107/rule.ts
packages/jsts/src/rules/S107/unit.test.ts
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S107.html

Modify rule S107: Do not count TypeScript parameter properties

---

its/ruling/src/test/expected/js/amplify/javascript-S6557.json
its/ruling/src/test/expected/js/angular.js/javascript-S6557.json
its/ruling/src/test/expected/js/javascript-test-sources/javascript-S6557.json
its/ruling/src/test/expected/js/jquery/javascript-S6557.json
package-lock.json
package.json

Fixes #4071 
I updated babel/core to [the version after the bump of semver](https://github.com/babel/babel/commits/05c408998bd83336e2ae2e8b4dff164e575747b9/packages/babel-core/package.json)
Upgrade to version semver: 
- 5.7.2
- 6.3.1
- 7.5.2
```bash
$ npm ls semver
sonarjs@1.0.0 /Users/ilia.kebets/Dev/Sonar/SonarJS
├─┬ @babel/core@7.22.9
│ ├─┬ @babel/helper-compilation-targets@7.22.10
│ │ └── semver@6.3.1 deduped
│ └── semver@6.3.1
├─┬ @babel/eslint-parser@7.21.8
│ └── semver@6.3.1 deduped
├─┬ @babel/plugin-proposal-decorators@7.22.3
│ └─┬ @babel/helper-create-class-features-plugin@7.22.10
│   └── semver@6.3.1 deduped
├─┬ @babel/preset-env@7.22.4
│ ├─┬ @babel/plugin-syntax-unicode-sets-regex@7.18.6
│ │ └─┬ @babel/helper-create-regexp-features-plugin@7.22.9
│ │   └── semver@6.3.1 deduped
│ …
```

Fix CVE-2022-25883 by updating semver

---

packages/jsts/src/rules/S3827/cb.fixture.vue
packages/jsts/src/rules/S3827/cb.test.ts
packages/jsts/src/rules/S3827/rule.ts
packages/jsts/src/rules/helpers/vue.ts

Fix FP S3827 (`no-reference-error`): Ignore Vue3 compiler macros

---

pom.xml

replace src, tests with packages

Fix references to srs and tests folders in main pom.xml

---

packages/jsts/src/rules/S2068/rule.ts
packages/jsts/src/rules/S2068/unit.test.ts

Improve S2068: Ignore linted files from l10n folders

---

packages/jsts/src/rules/S4123/rule.ts
packages/jsts/src/rules/S4123/unit.test.ts

Fix FP S4123 (`no-invalid-await`): Improve thenable type detection

---

its/ruling/src/test/expected/js/fireact/javascript-S6749.json
its/ruling/src/test/expected/ts/courselit/typescript-S6749.json
its/ruling/src/test/expected/ts/eigen/typescript-S6749.json
packages/jsts/src/rules/S6749/decorator.ts
packages/jsts/src/rules/S6749/index.ts
packages/jsts/src/rules/S6749/unit.test.ts
packages/jsts/src/rules/index.ts

Fix FP S6749 (`jsx-no-useless-fragment`): Ignore empty React fragments

---

docs/windows.md

Configure symlinks permissions and git line endings processing (see https://github.com/SonarSource/SonarJS/issues/3997)

Add config tips for windows users

---

packages/jsts/tests/tools/testers/comment-based/helpers/quickfixes.ts
pom.xml

Fix unescaped regexp chars and remove SQ exclusion

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
packages/bridge/src/server.ts
packages/bridge/tests/server.test.ts
packages/shared/src/helpers/debug.ts
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommandBuilderImpl.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/nodejs/NodeCommandTest.java

Log memory configuration when bridge starts

---

package-lock.json
package.json

Update babel to 7.23.2 to fix babel/traverse vulnerability

---

.cirrus.yml
its/plugin/sonarlint-tests/pom.xml
its/plugin/sonarlint-tests/src/test/java/TestUtils.java
its/plugin/sonarlint-tests/src/test/resources/TestUtils.txt

Use nvme storage for windows jobs

---

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/SonarLintJavaScriptProjectChecker.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/SonarLintJavaScriptProjectCheckerTest.java

Improve logging of JavaScript files type-checking in SonarLint context

---

sonar-plugin/css/src/main/java/org/sonar/css/rules/AtRuleNoUnknown.java
sonar-plugin/css/src/test/java/org/sonar/css/rules/CssRuleTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLintTest.java

Fix FP S4662 (`at-rule-no-unknown`): Ignore "@contain" by default

---

packages/jsts/src/rules/S4156/cb.fixture.ts
packages/jsts/src/rules/S4156/cb.test.ts
packages/jsts/src/rules/S4156/decorator.ts
packages/jsts/src/rules/S4156/index.ts

Improve S4156 (`prefer-namespace-keyword`): Report on the "module" keyword

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5869.html

Improve S5869 (`duplicates-in-character-class`): Mention character class escapes

---

.cirrus.yml
tools/fetch-node/node-distros.mjs
tools/fetch-node/scripts/copy-to-plugin.mjs
tools/fetch-node/scripts/directories.mjs
tools/fetch-node/scripts/fetch-node.mjs
tools/fetch-node/src/main/java/org/sonarsource/javascript/XZ.java
tools/fetch-node/src/test/java/org/sonarsource/javascript/XZTest.java

prerequisite for https://github.com/SonarSource/SonarJS/pull/4333

Fix `fetch-node` scripts for fresh machine, especially Windows

---

packages/jsts/src/rules/index.ts

Forgot to apply the decorator in https://github.com/SonarSource/SonarJS/pull/4329

Apply decoration for S4156 (`prefer-namespace-keyword`)

---

packages/bridge/src/memory.ts

Remove `node:` protocol from import

---

bin/server
package-lock.json
package.json

Update eslint-plugin-sonarjs to v0.22.0

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintCustomRulesTest.java
package-lock.json
package.json

- Update TypeScript 5.3
- Update eslint

Upgrade TS 5.3 and ESLint 

---

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AbstractBridgeSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/CssRuleSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/HtmlSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/JsTsSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/YamlSensor.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/HtmlSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JavaScriptEslintBasedSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/YamlSensorTest.java

Do not fail silently

---

packages/bridge/src/errors/middleware.ts
packages/bridge/tests/errors/middleware.test.ts
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java
sonar-plugin/sonar-javascript-plugin/src/test/resources/mock-bridge/startServer.js

This reverts commit cd866c37d595fe19633067022dc7b15d5fef04d3.
I am reverting the change because it's more complicated than originally though. We will do the work in issue #4478

Revert "Bridge should return error status on unexpected errors (#4474)"

---

packages/jsts/src/rules/S4123/unit.test.ts
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4123.html

Improve S4123 (`no-invalid-await`): Improve documentation about edge cases and add test to confirm that S4123 honours JSDoc directives

---

.github/workflows/typedoc.yml

@saberduck You can verify the checks of the pre-last commit. In particular the [typedoc action run](https://github.com/SonarSource/SonarJS/actions/runs/7707366376/job/21004426072).

Fix typedoc

---

package-lock.json

From https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#packages
> registry.npmjs.org is a magic value meaning "the currently configured registry".

Use registry.npmjs.org for resolved packages

---

pom.xml

* Fix CVE-2024-26308
* Fix CVE-2024-25710

Fix vulnerabilities: bump `commons-compress` version to 1.26

---

packages/jsts/src/rules/S5332/rule.lib.ts
packages/jsts/src/rules/S5332/unit.test.ts

Fix S5332: Add reserved domain patterns to EXCEPTION_TOP_HOSTS list

---

.cirrus/nodejs.Dockerfile
sonar-plugin/sonar-javascript-plugin/pom.xml
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java

Remove support for Node.JS 16

---

its/ruling/src/test/expected/jsts/file-for-rules/javascript-S2699.json
its/sources/jsts/custom/tests/S2699.js
packages/jsts/src/rules/S2699/rule.ts
packages/jsts/src/rules/S2699/supertest.fixture.js
packages/jsts/src/rules/helpers/supertest.ts

Resolve issue #4631: Fix FP S2699 (`assertions-in-tests`): Add support for `supertest`

---

packages/jsts/src/rules/S2699/assertion.fixture.js
packages/jsts/src/rules/S2699/vitest.fixture.js

Issue 4459 - Improve the global expect tests

---

docs/DEV.md

Update readme DEV.md with correct path to temporary ruling results

---

packages/jsts/src/rules/S109/rule.ts
packages/jsts/src/rules/S6544/rule.ts
packages/jsts/src/rules/S6957/rule.ts
packages/shared/src/types/rule.ts
sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/ContentLengthCheck.java
sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/HardcodedCredentialsCheck.java
sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/ImplicitDependenciesCheck.java
sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/IntrusivePermissionsCheck.java

Resolve JS-151 - Add explicit `meta.schema` to the configurable rules that are missing it 

---

packages/jsts/src/dbd/frontend/expressions/call-expression.ts
packages/jsts/src/dbd/frontend/ir-generator.ts
packages/jsts/src/dbd/frontend/scope-translator.ts
packages/jsts/src/dbd/ir-gen/ir_pb.ts
packages/jsts/src/dbd/proto/ir.proto

Function as variable

---

packages/jsts/src/dbd/frontend/ir-generator.ts
packages/jsts/src/dbd/frontend/scope-translator.ts
packages/jsts/src/rules/S99999/rule.ts
snippet.js

Add support for HOF calls

---

packages/jsts/src/dbd/gen-ir.ts

Fix -O option

---

packages/jsts/tests/parsers/ast.test.ts
tools/estree/output/estree.proto

implement ast compare

---

README.md

Ran `npm run count-rules` script

Update rules count

---

.cirrus.yml
.github/workflows/.npmrc
.github/workflows/release_eslint_plugin.yml
packages/jsts/src/rules/README.md
packages/jsts/src/rules/package.json

Fixes https://sonarsource.atlassian.net/browse/JS-229

JS-229 Fix eslint-plugin-sonarjs release action

---

packages/jsts/src/rules/index.ts

From https://github.com/SonarSource/eslint-plugin-sonarjs/pull/476

Add name to ESLint recommended config

---

sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/TestFileCheck.java

Fixes SonarQube [9eccec63](https://next.sonarqube.com/sonarqube/project/issues?issues=9eccec63-22b9-407d-91c7-c8db66957287&open=9eccec63-22b9-407d-91c7-c8db66957287&id=org.sonarsource.javascript%3Ajavascript).

Fix SonarQube issue 9eccec63

---

packages/jsts/src/rules/package-lock.json
packages/jsts/src/rules/package.json

Fixes [ESLINTJS-47](https://sonarsource.atlassian.net/browse/ESLINTJS-47)
[ESLINTJS-47]: https://sonarsource.atlassian.net/browse/ESLINTJS-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Resolve ESLINTJS-47

---

packages/jsts/src/rules/index.ts
packages/jsts/tests/rules/index.test.ts

Resolve ESLINTJS-46

---

package.json
packages/jsts/src/rules/index.ts
tools/generate-rules-list.js

Fixes https://sonarsource.atlassian.net/browse/JS-295

JS-295 List of rules is created automatically

---

its/plugin/sonarlint-tests/pom.xml
packages/jsts/src/analysis/analyzer.ts
packages/jsts/src/parsers/ast.ts
packages/jsts/tests/parsers/ast.test.ts

JS-299 List nodes that need to be supported in TS

---

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptFilePredicate.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/TsConfigCache.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/TsConfigCacheImpl.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/TsConfigProvider.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/TsConfigCacheTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/TsConfigProviderTest.java

SonarLint caching of tsconfigs v2

---

packages/jsts/src/rules/S125/unit.test.ts

[JS-403](https://sonarsource.atlassian.net/browse/JS-403)
[JS-403]: https://sonarsource.atlassian.net/browse/JS-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-403 Improve S125 test: Cover decorators and JSX

---

packages/jsts/src/parsers/options.ts

[JS-401](https://sonarsource.atlassian.net/browse/JS-401)
[JS-401]: https://sonarsource.atlassian.net/browse/JS-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-401 Revert change on Babel paths

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/schemas/S2068-schema.json

[JS-431](https://sonarsource.atlassian.net/browse/JS-431)
[JS-431]: https://sonarsource.atlassian.net/browse/JS-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-431 Update S2068 (no-hardcoded-passwords): Fix schema

---

its/perf/pom.xml
its/plugin/plugins/consumer-plugin/pom.xml
its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/sonarlint-tests/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
pom.xml
sonar-plugin/api/pom.xml
sonar-plugin/bridge/pom.xml
sonar-plugin/css/pom.xml
sonar-plugin/javascript-checks/pom.xml
sonar-plugin/pom.xml
sonar-plugin/sonar-javascript-plugin/pom.xml
sonar-plugin/standalone/pom.xml
tools/fetch-node/pom.xml
tools/pom.xml

[JS-463](https://sonarsource.atlassian.net/browse/JS-463)
[JS-463]: https://sonarsource.atlassian.net/browse/JS-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-463 Prepare next development iteration

---

generate-eslint-package-json.mjs

ESLINTJS-61 Allow for wider margin of Typescript versions

---

.git-blame-ignore-revs

[JS-476](https://sonarsource.atlassian.net/browse/JS-476)
[JS-476]: https://sonarsource.atlassian.net/browse/JS-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-476 Add prettier sha to blame-ignore-revs

---

.cirrus.yml

[JS-477](https://sonarsource.atlassian.net/browse/JS-477)
[JS-477]: https://sonarsource.atlassian.net/browse/JS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-477 Remove obsolete comment

---

its/perf/pom.xml
its/plugin/plugins/consumer-plugin/pom.xml
its/plugin/plugins/eslint-custom-rules-plugin/pom.xml
its/plugin/plugins/pom.xml
its/plugin/pom.xml
its/plugin/sonarlint-tests/pom.xml
its/plugin/tests/pom.xml
its/pom.xml
its/ruling/pom.xml
pom.xml
sonar-plugin/api/pom.xml
sonar-plugin/bridge/pom.xml
sonar-plugin/css/pom.xml
sonar-plugin/javascript-checks/pom.xml
sonar-plugin/pom.xml
sonar-plugin/sonar-javascript-plugin/pom.xml
sonar-plugin/standalone/pom.xml
tools/fetch-node/pom.xml
tools/pom.xml

[JS-488](https://sonarsource.atlassian.net/browse/JS-488)
[JS-488]: https://sonarsource.atlassian.net/browse/JS-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-488 Prepare next development iteration

---

.husky/pre-commit

[JS-480](https://sonarsource.atlassian.net/browse/JS-480)
[JS-480]: https://sonarsource.atlassian.net/browse/JS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-480 Fix husky deprecation

---

packages/jsts/src/rules/README.md

[ESLINTJS-66](https://sonarsource.atlassian.net/browse/ESLINTJS-66)
[ESLINTJS-66]: https://sonarsource.atlassian.net/browse/ESLINTJS-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ESLINTJS-66 Fix link to CHANGELOG

---

sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/TsConfigProviderTest.java

[JS-499](https://sonarsource.atlassian.net/browse/JS-499)
[JS-499]: https://sonarsource.atlassian.net/browse/JS-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-499 Fix unit test

---

packages/jsts/src/linter/wrapper.ts

[JS-512](https://sonarsource.atlassian.net/browse/JS-512)

JS-512 Fix special characters in filenames

---

.cirrus.yml

[BUILD-7042](https://sonarsource.atlassian.net/browse/BUILD-7042)
Fix maven cache fingerprint script.
[BUILD-7042]: https://sonarsource.atlassian.net/browse/BUILD-7042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-7042: fix maven cache fingerprint script

---

packages/jsts/src/rules/CHANGELOG.md

[JS-556](https://sonarsource.atlassian.net/browse/JS-556)
[JS-556]: https://sonarsource.atlassian.net/browse/JS-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-556 Update ESLint plugin CHANGELOG.md for version 3.0.2

---

packages/jsts/src/linter/linter.ts

[JS-569](https://sonarsource.atlassian.net/browse/JS-569)
[JS-569]: https://sonarsource.atlassian.net/browse/JS-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-569 Do not crash when unknown environments are provided in the config

---

packages/bridge/tests/errors/middleware.test.ts
packages/bridge/tests/memory.test.ts
packages/bridge/tests/router.test.ts
packages/bridge/tests/server.test.ts
packages/bridge/tests/timeout/timeout.test.ts
packages/css/tests/linter/issues/transform.test.ts
packages/jsts/tests/builders/build.test.ts
packages/jsts/tests/linter/index.test.ts
packages/jsts/tests/program/program.test.ts
packages/jsts/tests/rules/helpers/find-up.test.ts
packages/shared/tests/helpers/logging.test.ts

[JS-574](https://sonarsource.atlassian.net/browse/JS-574)
[JS-574]: https://sonarsource.atlassian.net/browse/JS-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-574 Fix flaky test

---

tools/helpers.ts
tools/new-rule.mts
tools/templates/ts/meta.template
tools/templates/ts/rule.cbtest.template
tools/templates/ts/rule.decorated.template
tools/templates/ts/rule.template

[JS-580](https://sonarsource.atlassian.net/browse/JS-580)
Cleaned up the script. Now the generated comment based test can be ran :)
[JS-580]: https://sonarsource.atlassian.net/browse/JS-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-580 Update new rule script

---

packages/jsts/src/rules/helpers/generate-meta.ts
tools/new-rule.mts
tools/templates/ts/rule.cbtest.template

[JS-611](https://sonarsource.atlassian.net/browse/JS-611)
[JS-611]: https://sonarsource.atlassian.net/browse/JS-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-611 Fix comment-based test template

---

.github/workflows/PullRequestClosed.yml

[JS-607](https://sonarsource.atlassian.net/browse/JS-607)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[JS-607]: https://sonarsource.atlassian.net/browse/JS-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-607 Autoclose issues created by Jira integration

---

package-lock.json

[JS-655](https://sonarsource.atlassian.net/browse/JS-655)
[JS-655]: https://sonarsource.atlassian.net/browse/JS-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-655 Revert "Update dependency one-double-zero to v1.1.0 (#5234)"

---

sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/estree/ESTree.java
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/ESTreeFactory.java

https://sonarsource.atlassian.net/browse/SONARARMOR-852

SONARARMOR-852 Fix ESTree.java hierarchy

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/dogfood.yml
.github/workflows/releasability.yml
.github/workflows/release_eslint_plugin.yml
.github/workflows/typedoc.yml

[JS-663](https://sonarsource.atlassian.net/browse/JS-663)
[JS-663]: https://sonarsource.atlassian.net/browse/JS-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-663 GitHub workflows migration to self hosted runners

---

pom.xml

[JS-671](https://sonarsource.atlassian.net/browse/JS-671)
[JS-671]: https://sonarsource.atlassian.net/browse/JS-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-671 Prepare next development iteration

---

sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/EslintBasedCheck.java
sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/EslintHook.java
sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/EslintHookRegistrar.java
sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/ProfileRegistrar.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/HtmlSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsChecks.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/YamlSensor.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JavaScriptEslintBasedSensorTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsChecksTest.java

[SONARCH-631](https://sonarsource.atlassian.net/browse/SONARCH-631)
[SONARCH-631]: https://sonarsource.atlassian.net/browse/SONARCH-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARCH-631 Replace delegator stub per rule with single delegator in JS frontend

---

packages/shared/src/helpers/configuration.ts
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/TsConfigProviderTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java

[JS-702](https://sonarsource.atlassian.net/browse/JS-702)
Copied from https://github.com/SonarSource/SonarJS/pull/5261

JS-702 Ignore git folder

---

packages/css/src/analysis/analyzer.ts

[JS-153](https://sonarsource.atlassian.net/browse/JS-153)
[JS-153]: https://sonarsource.atlassian.net/browse/JS-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-153 Capture parsing errors in CSS

---

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2092.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2612.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2755.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3330.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4502.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4830.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5332.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5443.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5527.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5547.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S5876.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6270.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6281.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6303.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6308.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6319.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6327.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6329.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6330.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6333.html
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6767.html

[JS-708](https://sonarsource.atlassian.net/browse/JS-708)
Part of 
[JS-708]: https://sonarsource.atlassian.net/browse/JS-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-708 Update rule descriptions

---

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java

[JS-729](https://sonarsource.atlassian.net/browse/JS-729)
[JS-729]: https://sonarsource.atlassian.net/browse/JS-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-729 Consume HTTP response with a StreamReader

---

packages/jsts/src/analysis/projectAnalysis/files-finder.ts
packages/jsts/src/analysis/projectAnalysis/files.ts
packages/jsts/src/analysis/projectAnalysis/package-jsons.ts
packages/jsts/src/analysis/projectAnalysis/projectAnalyzer.ts
packages/jsts/src/analysis/projectAnalysis/tsconfigs.ts
packages/jsts/src/rules/helpers/package-json.ts
packages/jsts/tests/analysis/fixtures/package-json-malformed/package.json
packages/jsts/tests/analysis/package-jsons.test.ts

[JS-734](https://sonarsource.atlassian.net/browse/JS-734)
[JS-734]: https://sonarsource.atlassian.net/browse/JS-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-734 Search for package.json files during project lookup

---

sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/JsAnalysisConsumer.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisConsumers.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsContext.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/AnalysisConsumersTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java

[JS-731](https://sonarsource.atlassian.net/browse/JS-731)
[JS-731]: https://sonarsource.atlassian.net/browse/JS-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-731 AST consumers can be disabled

---

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/TsConfigCacheImpl.java

[JS-745](https://sonarsource.atlassian.net/browse/JS-745)
[JS-745]: https://sonarsource.atlassian.net/browse/JS-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-745 Fix SQ before release

---

sonar-plugin/javascript-checks/pom.xml

[JS-753](https://sonarsource.atlassian.net/browse/JS-753)
[JS-753]: https://sonarsource.atlassian.net/browse/JS-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-753 Change branch for rspec generation

---

packages/jsts/src/rules/helpers/package-json.ts
packages/jsts/tests/rules/helpers/fixtures/package.json
packages/jsts/tests/rules/helpers/package-json.test.ts

[JS-765](https://sonarsource.atlassian.net/browse/JS-765)
[JS-765]: https://sonarsource.atlassian.net/browse/JS-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-765 Fix package-json parsing with weird versions

---

packages/jsts/src/analysis/projectAnalysis/analyzeWithWatchProgram.ts
packages/jsts/src/analysis/projectAnalysis/file-stores/tsconfigs.ts
packages/jsts/src/analysis/projectAnalysis/tsconfigCache.ts
packages/jsts/tests/analysis/fixtures/referenced-tsconfigs/tsconfig.fake.pathref.json
packages/jsts/tests/analysis/fixtures/referenced-tsconfigs/tsconfig.pathref.json
packages/jsts/tests/analysis/tsconfigs.test.ts

[JS-772](https://sonarsource.atlassian.net/browse/JS-772)
[JS-772]: https://sonarsource.atlassian.net/browse/JS-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-772 Fix references

---

generate-eslint-package-json.mjs

[ESLINTJS-74](https://sonarsource.atlassian.net/browse/ESLINTJS-74)
[JS-778](https://sonarsource.atlassian.net/browse/JS-778)
[ESLINTJS-74]: https://sonarsource.atlassian.net/browse/ESLINTJS-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JS-778]: https://sonarsource.atlassian.net/browse/JS-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ESLINTJS-74 JS-778 Add lodash.merge to ESLint plugin dependencies

---

.cirrus.yml
its/ruling/src/test/expected/jsts/console/typescript-S107.json
package-lock.json
package.json
packages/jsts/src/rules/S107/rule.ts
packages/jsts/src/rules/S107/unit.test.ts
patches/eslint+9.29.0.patch

[JS-779](https://sonarsource.atlassian.net/browse/JS-779)
[JS-779]: https://sonarsource.atlassian.net/browse/JS-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-779 Update dependency eslint to v9.29.0

---

packages/jsts/src/analysis/projectAnalysis/file-stores/index.ts
packages/jsts/src/analysis/projectAnalysis/file-stores/package-jsons.ts
packages/jsts/src/analysis/projectAnalysis/file-stores/source-files.ts
packages/jsts/src/analysis/projectAnalysis/file-stores/store-type.ts
packages/jsts/src/analysis/projectAnalysis/file-stores/tsconfigs.ts
packages/shared/src/helpers/filter/filter-path.ts
packages/shared/src/helpers/find-files.ts
packages/shared/tests/helpers/filter-path.test.ts

[JS-780](https://sonarsource.atlassian.net/browse/JS-780)
[JS-780]: https://sonarsource.atlassian.net/browse/JS-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-780 Do not apply analysis scope exclusions/inclusions to tsconfig.json and package.json files

---

packages/jsts/src/rules/CHANGELOG.md
tools/update-changelog.js

[JS-783](https://sonarsource.atlassian.net/browse/JS-783)
[JS-783]: https://sonarsource.atlassian.net/browse/JS-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-783 Update ESLint plugin changelog

---

tools/generate-java-rule-classes.ts

[JS-784](https://sonarsource.atlassian.net/browse/JS-784)
[JS-784]: https://sonarsource.atlassian.net/browse/JS-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-784 S1451 (`file-header`): Input should be textarea instead of input

---

sonar-plugin/javascript-checks/pom.xml

[JS-785](https://sonarsource.atlassian.net/browse/JS-785)

JS-785 Update RSPEC Maven plugin

---

packages/jsts/src/rules/S4036/cb.fixture.js
packages/jsts/src/rules/S4036/rule.ts

[JS-789](https://sonarsource.atlassian.net/browse/JS-789)
Part of

JS-789 Improve S4036 message for users

---

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/JSWebSocketClient.java

[JS-790](https://sonarsource.atlassian.net/browse/JS-790)

JS-790 Remove WS client connection timeout

---

pom.xml

[JS-795](https://sonarsource.atlassian.net/browse/JS-795)
As there have been major changes to the infrastructure of the Plugin, let us reflect that by incrementing the major version.

JS-795 Bump to version 11.0.0

---

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/PluginInfo.java
sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1121.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1143.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S128.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S131.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1763.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1854.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1874.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2486.json
sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S905.json
sonar-plugin/sonar-javascript-plugin/pom.xml

[JS-801](https://sonarsource.atlassian.net/browse/JS-801)
[JS-801]: https://sonarsource.atlassian.net/browse/JS-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-801 Update node.js min required versions

---

.gitignore
package-lock.json
package.json
sonar-plugin/bridge/pom.xml
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java
sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
sonar-plugin/sonar-javascript-plugin/pom.xml
tools/sync-nodejs-versions.mjs

[JS-802](https://sonarsource.atlassian.net/browse/JS-802)
We keep getting into trouble when we update versions and don't always remember to manage the properties correctly.
[JS-802]: https://sonarsource.atlassian.net/browse/JS-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-802 Automagically keep node versions in sync between package.json, pom.xml and NodeDeprecationWarnings

---

packages/jsts/src/rules/S2187/rule.ts
packages/jsts/src/rules/S2187/unit.test.ts

[JS-804](https://sonarsource.atlassian.net/browse/JS-804)
Part of 
[JS-804]: https://sonarsource.atlassian.net/browse/JS-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-804 Add a few more test fqns

---

packages/shared/src/helpers/configuration.ts
packages/shared/src/helpers/filter/filter.ts
sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsExclusionsFilter.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsExclusionsFilterTest.java

[JS-807](https://sonarsource.atlassian.net/browse/JS-807)
[JS-807]: https://sonarsource.atlassian.net/browse/JS-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-807 Add JS/TS exclusions filter in Java

---

.github/renovate.json

[JS-812](https://sonarsource.atlassian.net/browse/JS-812)
[JS-812]: https://sonarsource.atlassian.net/browse/JS-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-812 Enable config migration for renovate

---

pom.xml

[JS-813](https://sonarsource.atlassian.net/browse/JS-813)
[JS-813]: https://sonarsource.atlassian.net/browse/JS-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-813 Prepare next development iteration

---

its/plugin/plugins/consumer-plugin/src/main/java/org/sonar/samples/javascript/consumer/Consumer.java
its/plugin/plugins/consumer-plugin/src/test/java/org/sonar/samples/javascript/consumer/ConsumerTest.java
sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/JsAnalysisConsumer.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisConsumers.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/AnalysisConsumersTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java

[JS-793](https://sonarsource.atlassian.net/browse/JS-793)
[JS-793]: https://sonarsource.atlassian.net/browse/JS-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-793 Add SensorContext as parameter to JsAnalysisConsumer::doneAnalysis

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java
packages/jsts/src/analysis/projectAnalysis/file-stores/tsconfigs.ts
packages/jsts/tests/analysis/tsconfigs.test.ts
packages/shared/src/helpers/configuration.ts

[JS-818](https://sonarsource.atlassian.net/browse/JS-818)
[JS-818]: https://sonarsource.atlassian.net/browse/JS-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-818 tsconfigPaths should accept absolute paths

---

its/plugin/sonarlint-tests/src/test/java/com/sonar/javascript/it/plugin/sonarlint/tests/TestUtils.java
sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/AstProtoUtilsTest.java
sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/ProgressReportTest.java

[JS-825](https://sonarsource.atlassian.net/browse/JS-825)
[JS-825]: https://sonarsource.atlassian.net/browse/JS-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-825 Remove unused imports

---

pom.xml

[JS-842](https://sonarsource.atlassian.net/browse/JS-842)
Part of 
[JS-842]: https://sonarsource.atlassian.net/browse/JS-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-842 Update Apache commons lang3 version

---

packages/jsts/src/rules/CHANGELOG.md
pom.xml

[JS-843](https://sonarsource.atlassian.net/browse/JS-843)
[JS-843]: https://sonarsource.atlassian.net/browse/JS-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-843 Prepare next development iteration

---

its/ruling/src/test/expected/jsts/eigen/typescript-S2301.json
package-lock.json
packages/jsts/src/rules/S2301/rule.ts
packages/jsts/src/rules/S2301/unit.test.ts

[JS-854](https://sonarsource.atlassian.net/browse/JS-854)
See community report - https://community.sonarsource.com/t/typescript-s2301-false-positive/147981
This rule shouldn't raise when this isn't a callable methods from outside.
[JS-854]: https://sonarsource.atlassian.net/browse/JS-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-854 Dont raise on arrow function as lambda argument

---

pom.xml

[JS-866](https://sonarsource.atlassian.net/browse/JS-866)
[JS-866]: https://sonarsource.atlassian.net/browse/JS-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JS-866 NOJIRA new iteration

---

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java
sonar-plugin/css/src/main/java/org/sonar/css/StylelintReportSensor.java
sonar-plugin/css/src/main/java/org/sonar/css/metrics/CssMetricSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/CssRuleSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/HtmlSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/YamlSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/AbstractExternalIssuesSensor.java
sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java

[JS-794](https://sonarsource.atlassian.net/browse/JS-794)
[JS-794]: https://sonarsource.atlassian.net/browse/JS-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "JS-794 Make all Sensors global (#5523)"

---

packages/bridge/src/server.ts
packages/bridge/tests/server.test.ts

Sync close
