sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/cpd/JavaScriptCpdMapping.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/cpd/JavaScriptCpdMappingTest.java
Just a small fix.
We should replace the deprecated classes, is it right?
=> org.sonar.api.resources.ProjectFileSystem was deprecated.

its/performancing/pom.xml, its/plugin/tests/pom.xml, its/ruling/pom.xml, its/type-inference/tests/pom.xml, pom.xml
Build fails if oracle jdbc is not present.
=> Factorize orchestrator version and exclude oracle jdbc dependency from orchestrator which is not needed

javascript-checks/src/main/java/org/sonar/javascript/checks/AbstractFunctionSizeCheck.java, javascript-checks/src/test/resources/checks/tooManyLinesInFunction.js
If a function is called on an Angular module, and the last parameter of
that function is an empty array, analysis previously failed with an
IndexOutOfBoundsException.
=> Prevent IndexOutOfBoundsException on analysis

javascript-frontend/src/main/java/org/sonar/javascript/tree/symbols/GlobalVariableNames.java, javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/GlobalVariableNamesTest.java
Remove from default value of 'sonar.javascript.globals' names duplicated by default of 'sonar.javascript.environments'
=> SONARJS-907 Clean default value of 'sonar.javascript.globals'

its/performancing/src/test/java/JavaScriptPerformanceTest.java
Since we've started parsing Flow, parsing time slightly increased (around 2-3 seconds more).
Also it looks like when in previous  sprint (for 3.1) we added new files for Vue and new metric computation, parsing time increased, and expectation was updated only for parsing test (see commit 7df6fc71b6f481dce2739843db3e2e8e5a908efc mistakenly naming this change only for new metric). That's why update of SE Perf test is bigger.
=> Increase expectations for Performance IT

javascript-frontend/src/main/java/org/sonar/javascript/lexer/JavaScriptRegexpChannel.java, javascript-frontend/src/test/java/org/sonar/javascript/parser/lexical/RegularExpressionLiteralTest.java
This is required due to https://bugs.openjdk.java.net/browse/JDK-8189343
Fixes #801
=> Fix parsing of regular expression literals for JDK 9

javascript-checks/src/test/resources/checks/unusedVariable.js, javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java, javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/TemplateLiteralTreeModelTest.java, javascript-frontend/src/test/java/org/sonar/javascript/tree/symbols/UsageTest.java, javascript-frontend/src/test/resources/ast/resolve/usage.js
=> Fix parsing of template literal with escaped '\', '$' and '`'

check-license-compliance.sh, pom.xml, third-party-licenses.sh, travis.sh
Upgrading to parent 45 allows to improve the verification of
license compliance of third-party dependencies.
The new script check-license-compliance.sh fails if a dependency
has a license that is not compatible with SonarSource policy.
See https://xtranet.sonarsource.com/display/DEV/Open+Source+Licenses
for more details.
Fixes #
=> Check license compliance on Travis

javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomJavaScriptRulesDefinition.java
Fixes compatibility of custom rules with SQ 7.3 (to be released)
In SQ 7.3 a lot of deprecated API will be removed, including annotation `BatchSide`.
Note that with SQ >=7.3 and SonarJS <4.2 custom rules will not work due to the usage of deprecated `@BatchSide`.
=> Stop using deprecared @BatchSide

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/LCOVParser.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java
=> Improve logging for lcov parser when coverage report is inconsistent

eslint-bridge/src/linter.ts, eslint-bridge/tests/linter.test.ts
=> Add internal parameter 'sonar-runtime' for rules to enable/disable secondary locations

eslint-bridge/src/parser.ts, eslint-bridge/tests/parser.test.ts
=> Use babel parser when not parsed with espree

javascript-checks/src/main/java/org/sonar/javascript/checks/UntrustedContentCheck.java
The current description make it unclear if dots are considered as litteral or special characters.
Since the source code consider that every piece of the list is a regex, litteral dots should be escaped.
=> Fix UntrustedContentCheck (S2611) rule parameter description

javascript-frontend/src/main/java/org/sonar/javascript/parser/EcmaScriptLexer.java, javascript-frontend/src/test/java/org/sonar/javascript/tree/impl/expression/jsx/JsxElementTreeModelTest.java
=> Fix parsing of jsx tag name containing hyphen, colon and dot

javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S3523.html
javascript:S1523 is not a rule key in SonarJS -- it is actually javascript:Eval. This should fix the link within a user's SonarQube instance
=> Fix link to S3523 replacement

its/ruling/src/test/expected/ts/ag-grid/typescript-S1862.json, javascript-checks/src/main/java/org/sonar/javascript/checks/CheckList.java, javascript-checks/src/main/java/org/sonar/javascript/checks/DuplicateConditionIfCheck.java, javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1862.html, javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1862.json
Fixes #1430 
* We no longer report duplicate switch cases for TypeScript.
(The spec was outdated with regard to handling duplicate switch cases.)
=> Add rule S1862 (based on 'eslint-plugin-sonarjs/no-identical-conditions') for TS

its/plugin/projects/missing-tsconfig/package-lock.json, its/plugin/projects/missing-tsconfig/package.json, its/plugin/projects/missing-tsconfig/src/main.ts, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigProviderTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
Fixes #1392 
I refactored logic around tsconfig to separate class to make unit testing easier and also to simplify TypeScriptSensor
=> Create default configuration if no tsconfig file is found

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigFile.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigFileTest.java
Fixing the NPE:
```
ERROR: Failed to load tsconfig file from /tmp/cirrus-ci-build/kibana/workspace/test/tsconfig.json. It will be ignored!
java.lang.NullPointerException: null
at org.sonar.plugins.javascript.eslint.TsConfigFile$GlobMatcher.defaultGlobPattern(TsConfigFile.java:110)
at org.sonar.plugins.javascript.eslint.TsConfigFile$GlobMatcher.lambda$new$0(TsConfigFile.java:93)
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[...]
```
and omit to print the stacktrace of the exception.
=> Remove null elements in ts config lists

.cirrus.yml
QA was not executed on dogfood branches because condition didn't contain the right pattern
=> Fix build for dogfood branch

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/CancellationException.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TypeScriptSensor.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
Fix #1738 
Fix #1736 
In addition, this PR also adds support for cancellation of analysis (used mostly in SonarLint)
=> Run Java frontend and Java based rules in single sensor

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BundleImpl.java
`java.nio.Files` API should provide a better error message in case of failure. This will also improve code coverage.
=> Use java.nio when extracting the bundle instead of File.mkdirs

eslint-bridge/src/rules/no-variable-usage-before-declaration.ts
We miss `sonar-runtime` parameter, to indicate that error message should be parsed as JSON to provide secondary locations.
=> Fix secondary locations in S1526

sonarpedia.json
Replaces #1758 
Job updating Coverage Languages in RSPEC jira project will work due to https://jira.sonarsource.com/browse/RCOV-24 and https://jira.sonarsource.com/browse/RCOV-25 (release of RCOV project is required before SonarJS release)
=> Add 'languagesToCover' to sonarpedia file

eslint-bridge/src/parser.ts
This seems to improve perf, together with the upgrade done earlier.
Tested on vscode project
```
6.1
Sensor TypeScript analysis [javascript] (done) | time=473269ms
6.2
INFO: Sensor TypeScript analysis [javascript] (done) | time=165577ms
```
=> Clear cache instead of unloading module

eslint-bridge/src/rules/sonar-no-fallthrough.ts, eslint-bridge/tests/rules/sonar-no-fallthrough.test.ts
Currently we are reporting on entire `case` clause
=> Report only on 'case' keyword for S128

javascript-checks/pom.xml, javascript-checks/src/main/java/org/sonar/javascript/checks/utils/CheckUtils.java, javascript-checks/src/test/java/org/sonar/javascript/checks/utils/CheckUtilsTest.java
=> Use file URI when throwing exception reading file content

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintReportTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/AbstractExternalIssuesSensor.java
Fixes #1985 
I didn't add any unit test as anyway in unit test test implementation of FileSystem will be used which does not prove to work in real environment.
=> Fix detection of input file when absolute paths are used in eslint report

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BundleImpl.java
Vulnerability is theoretical, because we control the bundle which is being extracted.
=> Normalize path from bundle to fix theoretical vulnerability

eslint-bridge/src/rules/cors.ts, eslint-bridge/src/rules/utils.ts, eslint-bridge/tests/rules/cors.test.ts, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S4790.json
Two small enhancements in utils.ts, specifically of the methods that search for module names of expressions:
1. Inlined requires are now supported:
```
app.use(require('middleware')());
```
now works without requiring intermediate variables. This is a common enough way to instantiate middleware ([example from DVNA](https://github.com/appsecco/dvna/blob/c637437d6515bd4c732e91c58e62d38e88260d3c/server.js#L35))
2. Default export aliases are supported in import clauses (no need for `* as foo` - `foo` is enough):
```
import serveStatic from 'serve-static'
```
This is important, because middleware-modules usually don't have any other useful functions in the namespace: it's often just the middleware, so the `* as middlewareName` doesn't make much sense. [Example …
=> Support default imports and inlined requires in 'utils'

eslint-bridge/src/analyzer.ts, its/plugin/plugins/eslint-custom-rules-plugin/bundle/rules.js, its/plugin/plugins/eslint-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/CustomRule.java, its/plugin/plugins/eslint-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/EslintCustomRulesPlugin.java, its/plugin/plugins/eslint-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/RuleRepository.java, its/plugin/plugins/eslint-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/TsRepository.java, its/plugin/plugins/eslint-custom-rules-plugin/src/main/java/org/sonar/samples/javascript/TsRule.java, its/plugin/projects/custom_rules/src/dir/file.ts, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CustomRulesTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintCustomRulesTest.java, its/plugin/tests/src/test/resources/profile-typescript-custom-rules.xml, javascript-frontend/src/main/java/org/sonar/plugins/javascript/api/CustomRuleRepository.java, javascript-frontend/src/test/java/org/sonar/plugins/javascript/api/CustomRuleRepositoryTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/AbstractChecks.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptChecks.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/TypeScriptChecks.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TypeScriptChecksTest.java
We need to distinguish custom rule repository by language, otherwise, we instantiate rules from repository for incorrect language. Missing coverage is due to tests being located in another module (`sonar-javascript-plugin`)
=> Add language to CustomRuleRepository definition

.cirrus.yml, .cirrus/nodejs-10.Dockerfile, .cirrus/nodejs-8.Dockerfile, eslint-bridge/package.json, eslint-bridge/yarn.lock, its/ruling/src/test/expected/js/angular.js/javascript-S2432.json, its/ruling/src/test/expected/ts/ag-grid/typescript-S1874.json, its/ruling/src/test/expected/ts/postgraphql/typescript-S121.json, javascript-checks/src/main/java/org/sonar/javascript/checks/ReturnInSetterCheck.java, javascript-checks/src/test/java/org/sonar/javascript/checks/ReturnInSetterCheckTest.java, javascript-checks/src/test/resources/checks/returnInSetter.js, sonar-javascript-plugin/pom.xml, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java
Fix #2156 
It was necessary to revert S2432 back to Java implementation because ESLint rule is available only from v7.5.0
=> Downgrade eslint @typescript-eslint/parser dependencies to allow Node.js v8

eslint-bridge/src/parser.ts, eslint-bridge/tests/parser.test.ts
Fixes #
--
I don't see any time improvements for JavaScript ruling...
=> Log JavaScript parsing failure with TypeScript compiler at debug level

eslint-bridge/src/analyzer.ts, eslint-bridge/src/parser.ts, eslint-bridge/tests/analyzer.test.ts, eslint-bridge/tests/fixtures/failing-typescript/sample.lint.js, eslint-bridge/tests/fixtures/failing-typescript/tsconfig.json, eslint-bridge/tests/parser.test.ts, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServer.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
Fixes #
--
Failures from TypeScript compiler raised in eslint-bridge are communicated to ESLint sensor as "parsing" errors. The sensor then logs these errors, but does not abort the analysis.
=> Log failures from TypeScript compiler without analysis abort

its/ruling/src/test/expected/js/angular.js/javascript-S3525.json, its/ruling/src/test/expected/js/prototype/javascript-S3525.json, its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java
A TSConfig file is now generated per analysed JavaScript source file. Furthermore, each JavaScript analysis requests clearing the cache of typescript-eslint parser. And even though the impact is minimal here, the changes in ruling show a positive impact for rules relying on type information. Type inference was incorrect for these cases leading to FPs, which now are no longer reported.
=> Generate TSConfig file per analyzed JavaScript file

eslint-bridge/tests/parser.test.ts
`it.only` was accidentally merged in a previous PR which led to skipping all tests but the one decorated with `only`.
=> Fix accidentally skipped tests

eslint-bridge/package.json, eslint-bridge/src/analyzer.ts, eslint-bridge/src/parser.ts, eslint-bridge/tests/analyzer.test.ts, eslint-bridge/tests/fixtures/vue-project/sample.lint.vue, eslint-bridge/tests/fixtures/vue-project/tsconfig.json, eslint-bridge/tests/parser.test.ts, eslint-bridge/yarn.lock, its/plugin/projects/vue-js-project/file.vue, its/plugin/projects/vue-js-project/tsconfig.json, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptLanguage.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/TypeScriptLanguage.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptLanguageTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptSensorTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/TypeScriptLanguageTest.java
=> Analyze TypeScript code inside Vue.js single file components

eslint-bridge/src/runner/symbol-highlighter.ts, eslint-bridge/tests/runner/symbol-highlighter.test.ts
`Variable#identifiers` doesn't containt ASTNode for TS enums. This will result in trying to find location for undefined value. 
As per https://eslint.org/docs/developer-guide/scope-manager-interface#identifiers is planned to be deprecated. Replacement is `Definition#name` which is generic ASTNode (although typings in `.d.ts` are incorrect) and contains `Literal` node for TS enum.
This PR has a fix on two levels 
- we use `Definition#name` instead of `Variable#identifiers`, which works correctly for TS enums
- we defensively check if there is at least one AST node for each variable instance before creating highlighting
=> Fix symbol highlighting for TS enums

eslint-bridge/src/linter.ts, eslint-bridge/tests/linter.test.ts, eslint-bridge/typings/typescript-eslint/index.d.ts
Fixes #2483 
--
To sanitize TypeScript ESLint rules, we basically decorate the rules; each decorated rule now checks on creation whether it requires type information and if type information is available. If both conditions are met, then the original behaviour of the rule is preserved, otherwise the rule does nothing.
=> Sanitize TypeScript ESLint rules requiring type information

eslint-bridge/src/rules/post-message.ts, eslint-bridge/src/utils/utils-ast.ts, eslint-bridge/tests/rules/post-message.test.ts, its/ruling/src/test/expected/js/jStorage/javascript-S2819.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S2819.json, its/ruling/src/test/expected/js/qunit/javascript-S2819.json
Fixes #1772 
--
Note that part of the ticket scope was already implemented by #2243. The issue message and catching vulnerabilities when origin is not checked on the receiver side are the missing parts which are introduced with this PR.
=> Rule S2819: update implementation

pom.xml
Address CVE-2021-29425, although vulnerable method is not used.
=> Update commons-io to 2.8

its/plugin/projects/lcov-jsx/conditions-on-non-executable-lines.lcov, its/plugin/projects/lcov-jsx/file.jsx, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/LCOVParser.java
Fixes #2558 
--
Using the code snippet provided by the community, here is what we get on SonarQube UI before/after the changes introduced by this pull request.
**Before**
There is an uncovered condition at line 5. The metrics do say that there are two conditions and that one of them is actually uncovered. However, there is no partial coverage highlighting on the line.
**After**
The metrics regarding condition coverage remain the same: there are two conditions and one of the two is uncovered. However, there is now one more executable line, which is line 5. Furthermore, the very same line is now highlighted with a red marker denoting a partially covered line. And finally, the overall code coverage changes since executable lines are considered in the computation.
=> Fix code coverage reporting of conditions on non-executable lines

eslint-bridge/src/runner/highlighter.ts, eslint-bridge/src/runner/symbol-highlighter.ts, eslint-bridge/src/runner/utils-token.ts, eslint-bridge/tests/runner/highlighter.test.ts, eslint-bridge/tests/runner/symbol-highlighter.test.ts
Fixes #2668 
Syntax highlighting for the template section of Vue Single File Components takes inspiration from [sonar-html](https://github.com/SonarSource/sonar-html/blob/dbfc23fa354db91c784786c6a45baf054e612521/sonar-html-plugin/src/main/java/org/sonar/plugins/html/core/HtmlTokensVisitor.java#L73-L92) and how it implements such highlighting. 
Below is a table that summarises how Vue.js ESLint represents HTML in terms of AST nodes and how such nodes will be highlighted:
| HTML  |  Vue ESLint Node    | Highlighting |
|---|------|----|
| `<tag`  |   `HTMLTagOpen `   | `KEYWORD`  |
|  `>` |   `HTMLTagClose `   | `KEYWORD`  |
| `</tag`  | `HTMLEndTagOpen ` | `KEYWORD`  |
|  `/>` |   `HTMLSelfClosingTagClose `  | `KEYWORD`  |
|  `` |   `HTMLComment `   | `COMMENT`  |
|  `<!DOCTYPE ->` | …
=> Support syntax highlighting for Vue.js Single File Components templates

eslint-bridge/pom.xml
I suggest to hide logging when executing jest tests in MVN build. They are many and decrease readability of logs greatly
=> Do not show logs when running jest tests during mvn build

.cirrus.yml
Using c2 machines speeds up windows ITs by around 4 minutes. 
Using caching of plugins speeds up analysis for Next by 30 sec
=> Use c2 for windows ITs and cache plugins during Next analysis

eslint-bridge/src/rules/no-invalid-await.ts, eslint-bridge/tests/rules/no-invalid-await.test.ts
=> Improve S4123 (no-invalid-await): allow Pick<Promise> type

eslint-bridge/package.json, eslint-bridge/yarn.lock, its/ruling/src/test/expected/ts/TypeScript/typescript-S1488.json, its/ruling/src/test/expected/ts/ag-grid/typescript-S1488.json, its/ruling/src/test/expected/ts/desktop/typescript-S1488.json
The ruling differences are due to [#274](https://github.com/SonarSource/eslint-plugin-sonarjs/issues/274).
=> Upgrade eslint-plugin-sonarjs to 0.10.0

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CoverageTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java, nodejs-utils/src/main/java/org/sonarsource/nodejs/NodeCommandBuilderImpl.java, nodejs-utils/src/test/java/org/sonarsource/nodejs/NodeCommandTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/CoverageSensor.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/lcov/CoverageSensorTest.java
=> Drop deprecated TypeScript properties: `sonar.typescript.lcov.reportPaths`, `sonar.typescript.node`, `sonar.typescript.eslint.reportPaths`

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java, sonar-javascript-plugin/src/main/resources/static/documentation.md
Fix #2771 
I moved all constants to NodeDeprecationWarning, so they are in one place.
=> Require Node.js v10 and update documentation about supported Node.js versions

eslint-bridge/src/rules/regex-complexity.ts, eslint-bridge/src/utils/utils-regex.ts, eslint-bridge/src/utils/utils-string-literal.ts, eslint-bridge/tests/rules/regex-complexity.test.ts, eslint-bridge/tests/utils/utils-regex.test.ts
Fixes #2788 
The improvement makes two changes
- in string tokenizer, when we process `/` we insert an additional token to correct for the implicit escape
- when computing offsets for secondary locations, this should be done in the coordinates of the regexp, which will account for / thanks to the previous point
Computation of offsets will not work if the regexp spans multiple lines. I believe we can ignore such corner case.
=> Fix handling of forward slash when parsing regexp

css-sonarpedia/sonarpedia.json
Fixes the failure when running rule-api:
```
SonarJS/css-sonarpedia $ java -jar ../../sonar-rule-api/target/rule-api-2.2.0-SNAPSHOT.jar generate -rule S5362
NOTE: the rules are generated based on GitHub "rspec" repository from branch 'master'.
Exception in thread "main" java.lang.IllegalArgumentException: directory does not exist
at com.sonarsource.ruleapi.utilities.Utilities.assertBaseDir(Utilities.java:68)
at com.sonarsource.ruleapi.services.RuleFilesService.create(RuleFilesService.java:76)
at com.sonarsource.ruleapi.services.SonarPediaFileService.lambda$create$0(SonarPediaFileService.java:69)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at …
```
=> Fix rule-specs path in CSS sonarpedia

eslint-bridge/package.json
This is to make sure that we avoid loading code with ESM. See https://nodejs.org/api/packages.html#determining-module-system
=> Explicitly specify that we use commonjs modules

eslint-bridge/package-lock.json, eslint-bridge/package.json, eslint-bridge/src/rules/unused-import.ts, eslint-bridge/tests/rules/unused-import.test.ts
Fixes #2818
vue-eslint-parsing supports the new feature [<script setup>](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md) only on the syntactic level. There is no changes regarding scope information, especially for variable references between `<script>` and `<template>` sections of Vue.js Single File components. Therefore, and as a workaround, we consider any identifiers in the `<template>` section as possible references of imported symbols in the `<script>` section as well as tag names.
=> FP S1128 (unused-import): consider imported symbols used in Vue.js SFC templates

its/plugin/tests/pom.xml, its/ruling/pom.xml, pom.xml
I had this small change locally and it was annoying me :) It's for WhiteSource to not consider this dependency, because we don't actually ship it.
=> Fix scope for sonar-ws

eslint-bridge/src/rules/todo-tag.ts, eslint-bridge/tests/rules/todo-tag.test.ts
=> FP S1135: surrounding accented characters should be considered

eslint-bridge/src/rules/no-try-promise.ts, eslint-bridge/tests/rules/no-try-promise.test.ts
=> Fix FP ('no-try-promise'): consider yield as an alternative to await

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarning.java, sonar-javascript-plugin/src/main/resources/static/documentation.md, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/NodeDeprecationWarningTest.java
=> Improve warning messages for Node.js deprecation

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java, sonar-javascript-plugin/src/test/resources/mock-eslint-bridge/logging.js
Fixes #2803 
Tested manually by changing the date on local machine 1 year in future.
=> Set BROWSERSLIST_IGNORE_OLD_DATA to true to avoid error logs

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/decorators/index.ts, eslint-bridge/src/rules/decorators/no-unreachable-decorator.ts, eslint-bridge/tests/rules/decorators/no-unreachable-decorator.test.ts
=> Add quick fix for S1763 ('no-unreachable')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/decorators/index.ts, eslint-bridge/src/rules/decorators/no-throw-literal-decorator.ts, eslint-bridge/tests/rules/decorators/no-throw-literal-decorator.test.ts
=> Add quick fix for S3696 ('no-throw-literal')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/no-unused-function-argument.ts, eslint-bridge/tests/rules/no-unused-function-argument.test.ts
=> Add quick fix for S1172 ('no-unused-function-argument')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/inverted-assertion-arguments.ts, eslint-bridge/tests/rules/inverted-assertion-arguments.test.ts
=> Add quick fix for S3415 ('inverted-assertion-arguments')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/no-global-this.ts, eslint-bridge/tests/rules/no-global-this.test.ts
=> Add quick fix for S2990 ('no-global-this')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/decorators/index.ts, eslint-bridge/src/rules/decorators/no-empty-function-decorator.ts, eslint-bridge/tests/rules/decorators/no-empty-function-decorator.test.ts
=> Add quick fix for S1186 ('no-empty-function')

eslint-bridge/src/quickfix.ts
Fixes #3016
Depends on https://github.com/SonarSource/eslint-plugin-sonarjs/pull/338
=> Enable quick fix for S3626 ('no-redundant-jump')

eslint-bridge/src/quickfix.ts
Fixes #3021
Depends on https://github.com/SonarSource/eslint-plugin-sonarjs/pull/340
=> Enable quick fix for S3981 ('no-collection-size-mischeck')

eslint-bridge/src/quickfix.ts
Fixes #3003
Depends on https://github.com/SonarSource/eslint-plugin-sonarjs/pull/337
=> Enable quick fix for S1126 ('prefer-single-boolean-return')

eslint-bridge/src/quickfix.ts
Fixes #3010
Depends on https://github.com/SonarSource/eslint-plugin-sonarjs/pull/336
=> Enable quick fix for S2757 ('non-existent-operator')

eslint-bridge/src/quickfix.ts, eslint-bridge/src/rules/no-duplicate-in-composite.ts, eslint-bridge/tests/rules/no-duplicate-in-composite.test.ts
=> Add quick fix for S4621 ('no-duplicate-in-composite')

sonar-javascript-plugin/src/main/resources/static/documentation.md
Due to this empty line (introduced in SonarJS 9.0 https://github.com/SonarSource/SonarJS/blob/d53e654f102f8ef106bbaee34d82da3c3ba67585/sonar-javascript-plugin/src/main/resources/static/documentation.md?plain=1#L1) the documentation is badly displayed at docs.sonarqube.org
=> Remove empty leading line from documentation.md

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/css/rules/SelectorPseudoElementNoUnknown.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/css/rules/CssRuleTest.java
Fixes https://github.com/SonarSource/sonar-css/issues/373
Fixes https://github.com/SonarSource/sonar-css/pull/361
=> Fix FP S4660 ('selector-pseudo-element-no-unknown'): Ignore Blazor '::deep' combinator

eslint-bridge/src/rules/stylelint/function-calc-no-invalid.ts, eslint-bridge/tests/rules/stylint/function-calc-no-invalid.test.ts
While rewriting S5362 ('function-calc-no-invalid') as part of #3089, the detection of a division by zero assumed that the division operator could be represented by one of the two forms:
- a `word` node with a `/` value
- a `div` node
The latter turns out to be not accurate enough because such a node can actually be used for other contexts than divisions (see ['div' semantics](https://github.com/TrySound/postcss-value-parser#div)). This wrong assumption leads to false positives like [this one](https://peach.sonarsource.com/project/issues?id=directus_nodev14&issues=AYAghd7-CAMBr5DXUslu&open=AYAghd7-CAMBr5DXUslu).
To sum up, the division operator is either represented with: a `word` node _or_ a `div` node, _with_ a `/` value.
=> Fix css:S5362 ('function-calc-no-invalid'): Correctly detect the division operator

eslint-bridge/src/rules/sonar-max-lines-per-function.ts, eslint-bridge/tests/rules/sonar-max-lines-per-function.test.ts
=> Improve S138 ('sonar-max-lines-per-function'): Ignore React Functional Components

eslint-bridge/src/runner/cpd.ts, eslint-bridge/tests/runner/cpd.test.ts
=> Exclude JavaScript require statements from copy-paste detection

eslint-bridge/src/rules/different-types-comparison.ts, eslint-bridge/tests/rules/different-types-comparison.test.ts, its/ruling/src/test/expected/js/p5.js/javascript-S3403.json, its/ruling/src/test/expected/js/paper.js/javascript-S3403.json, its/ruling/src/test/expected/js/sizzle/javascript-S3403.json
=> Fix FP S3403 ('different-types-comparison'): Symbols should be comparable

sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
basePath contained tilde path (C:\Users\VICTOR~1.DIE\AppData\...) instead of full path (C:/Users/victor.diez/AppData/...)
Using `baseDir.toRealPath()` fixes the issue, but to seems it actually checks FS
=> fix tests on Windows

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
We are including the list of default JavaScript execution environments in the JavaScript analyzer's description on SonarQube (see [Peach(internal link)](https://peach.sonarsource.com/admin/settings?category=JavaScript+%2F+TypeScript)). It seems that there is a CSS issue on the SonarQube UI that we need to dogfood. Still, it does not make sense to include this list of defaults in the description itself as SQ will take care displaying it if user changed to a non-default.
=> Fix JavaScript execution environments description

docs/DEV.md
The refactoring done in https://github.com/SonarSource/SonarJS/pull/3171 moved some files. The new directory structure is not up to date in the docs.
=> Fix dev docs: Point to the correct comment-based fixtures path

javascript-checks/src/main/java/org/sonar/javascript/checks/DuplicatePropertyNameCheck.java, javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S1534.json
S1534 does not cover Typescript due to TS compiler proactively reporting it on JS objects. Now that the rule covers JSX, Typescript should also be added
=> Add rule S1534 (`no-dupe-keys`) for TypeScript

its/ruling/src/test/expected/ts/moose/typescript-S1441.json, its/ruling/src/test/expected/ts/moose/typescript-S1451.json, its/ruling/src/test/expected/ts/moose/typescript-S1537.json
4 missing issues on the file 'CastDeviceType.ts' which is not seems to
be used
relates to #3194
=> Fix project structure for 'moose' in TS Ruling

sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TypeScriptSensorTest.java
Fixes #3175 
The test was failing because the following line was returning false: 
https://github.com/SonarSource/SonarJS/blob/ecafd2e7faf96dc708f16495edf5d5334926866c/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithProgram.java#L121
A better fix would be:
1. finding a way to express file paths that works for all OSes
2. applying it in all the codebase
I suggest leaving this for a deeper refactoring sprint.
=> Fix integration unit tests failing for OS-dependent paths format

.cirrus.yml, its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java, its/ruling/src/test/resources/empty-kubernetes-profile.xml
Testing with LTS is no longer required, since current plugin version is never going to be part of LTS
=> Remove latest SonarQube 8.9 testing from QA

eslint-bridge/src/utils/s3-rule-template.ts
A rule's metadata needs to be parameterizable. Otherwise, if we were to force the support of secondary locations, rules that don't it would still have to use the secondary location API when reporting issues, that is, calling `toEncodedMessage`.
=> Improve S3 Bucket rule template: make rule metadata parameterizable

.cirrus.yml, its/plugin/tests/pom.xml, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CssIssuesTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CssNonStandardPathTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CssTestsUtils.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ECMAScriptModulesTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintCustomRulesTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/MultiTsconfigTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/NoSonarTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/OrchestratorStarter.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProfileGenerator.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithBOMTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ProjectWithDifferentEncodingTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestCodeAnalysisTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptAnalysisTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TypeScriptRuleTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/VueAnalysisTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlAnalysisTest.java, its/plugin/tests/src/test/resources/junit-platform.properties, pom.xml
This was a bit complicated mostly because I needed to workaround couple of race conditions in orchestrator and scanner, which are not really ready to be run in parallel:
- Installation of SQ before the test suite needs to be synchronized 
- I explicitly set scanner version to a fixed version (4.7) and this is also installed before tests are executed to avoid race condition
- Creation of profile for tests needs to be adjusted to create unique profile for each test
Unrelated changes is fix for Windows maven cache.
It seems that capturing stdout/stderr is not working really well between JUnit 5 and maven surefire. In case we will need it we would need to disable parallel execution.
=> Run plugin QA in parallel

eslint-bridge/src/linter.ts, eslint-bridge/src/utils/utils-location.ts, eslint-bridge/tests/rules/rule-test-launcher.test.ts, eslint-bridge/tests/testing-framework/assertions.ts, eslint-bridge/tests/testing-framework/fixtures/missing_secondary.js, eslint-bridge/tests/testing-framework/testing-framework.test.ts
When a rule enables the support of secondary locations with the internal `sonar-runtime` parameter, it forces the encoding of issue messages even if an issue does not always include secondary locations. On the other hand, the comment-based testing framework only considers local comments in test files when extracting issue expectations. Therefore, if an issue expectation does not include secondary locations, the extraction process considers it a regular issue and bypasses the encoding of the issue message. This prevents the comment-based testing framework from correctly testing issues without secondary locations reported by a rule enabling the support of secondary locations.
=> Update comment-based testing framework: fix secondary location encoding

eslint-bridge/package.json
Fixes Windows build. Needs cygwin to have higher precedence over Windows binaries (ie. sort)
=> Fix Windows build

eslint-bridge/src/linting/eslint/rules/no-hardcoded-ip.ts, eslint-bridge/tests/linting/eslint/rules/no-hardcoded-ip.test.ts
=> Fix S1313: Consider IPv4 addresses mapped to IPv6 with the ::ffff:0: prefix

pom.xml, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/RulesMetadataForSonarLintTest.java
=> Update sonar-analyzer-commons to get rule scopes from JSON files.

eslint-bridge/src/linting/eslint/rules/sonar-max-params.ts, eslint-bridge/tests/linting/eslint/rules/sonar-max-params.test.ts
Cirrus jobs for TypeScript and material2 projects are failing when trying to save an issue:
> 16:14:12.368 ERROR: Failure during analysis, Node.js command to start eslint-bridge was:/some/long/path
java.lang.IllegalArgumentException: Start pointer [line=1305, lineOffset=19] should be before end pointer [line=1305, lineOffset=19]
...
at org.sonar.plugins.javascript.eslint.AnalysisProcessor.saveIssue(AnalysisProcessor.java:224)
This is caused by the recent extension of S107 ('sonar-max-params'), which now considers function signatures as well. For example, given the definition:
```typescript
class C {
constructor(/* too many parameters */);
}
```
the rule is currently raising an issue at a location where the starting and ending columns overlap, which causes the failure:
> …
=> Fix S107 ('sonar-max-params'): Fix location reporting of empty functions

its/ruling/src/test/expected/ts/ant-design/typescript-S109.json, javascript-checks/src/main/java/org/sonar/javascript/checks/NoMagicNumbersCheck.java, javascript-checks/src/test/java/org/sonar/javascript/checks/NoMagicNumbersCheckTest.java
=> Fix FP S109 ('no-magic-numbers'): Ignore numeric literal types

eslint-bridge/tests/linting/eslint/rules/no-unused-function-argument.test.ts
Fixes #3117 
The false positive originally reported is no longer raised. Upgrading ESLint at some points probably included a bugfix in the scope analysis, but I was not able to identify which release fixed it. In any case, I added a test case to track any regression.
=> Fix FP S1172 ('no-unused-function-argument'): Ignore parameters referenced as JSX identifiers

eslint-bridge/src/linting/eslint/rules/no-implicit-dependencies.ts, eslint-bridge/tests/linting/eslint/rules/no-implicit-dependencies.test.ts
=> Fix FP S4328: Ignore `node:` imports

eslint-bridge/src/linting/eslint/rules/no-misleading-array-reverse.ts, eslint-bridge/tests/linting/eslint/rules/no-misleading-array-reverse.test.ts
=> Fix FP S4043 (`no-misleading-array-reverse`): Consider optional chaining

eslint-bridge/tests/server.test.ts
It fails often: https://gist.github.com/ilia-kebets-sonarsource/557cbdfa09d496c2dd28251b97336423#build_win
=> Increase timeout so test won't fail in `build_win` CI check

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestCodeAnalysisTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/TestUtils.java, pom.xml
Clean-up and small improvements to SonarLint integration tests. We avoid writing to filesystem when not required. Motivation is to fix spurious failures, however I failed to find the root cause of failure.
=> Improve SonarLint integration test

eslint-bridge/src/linting/eslint/rules/decorators/index.ts, eslint-bridge/src/linting/eslint/rules/decorators/no-var-decorator.ts, eslint-bridge/tests/linting/eslint/rules/comment-based/no-var.js
=> Improve S3504 (`no-var`): Highlight only `var` keyword and identifier.

.github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
Same as https://github.com/SonarSource/sonar-dotnet/pull/6362
Uses these actions, see sample yml:
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardToReview
https://github.com/SonarSource/gh-action-lt-backlog/tree/v1/MoveCardAfterReview
=> GitHub workflow: Migrate RequestReview and SubmitReview to shared action

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/SonarLintTest.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptProjectChecker.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectChecker.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/TsConfigProvider.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/SonarLintJavaScriptProjectCheckerTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/TsConfigProviderTest.java
Fixes #3562
This PR generates temporary `tsconfig.json` files for every project for files analyzed with the JavaScript sensor. It also uses the SonarLint API `ModuleFileSystem` to determine if the project is not exceeding a configured limit by setting the max number of lines with `sonar.javascript.sonarlint.type.maxlines`.
=> Generate wildcard TSConfig for JavaScript in SonarLint

eslint-bridge/src/linting/eslint/rules/helpers/lva.ts, eslint-bridge/src/linting/eslint/rules/no-dead-store.ts
There are two main changes to the rule implementation
- avoid creating intermediate arrays
- limit recursion when looking up variables in the scope
It improves ± 30%, on some projects even ± 50%
=> Improve performance of S1854 `no-dead-store`

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensor.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java
SonarCloud is failing to load the SonarJS plugin because the JavaScript sensor depends on an interface that only has an implementation in SonarLint. Currently, the sensor receives null for the missing implementation class in our integration tests. But on SonarCloud, it raises an exception. The solution here is to provide a second constructor to the JavaScript sensor without this dependency. SonarCloud doesn't throw an exception if there's a constructor that it can invoke.
=> Fix dependency injection of JavaScriptProjectChecker for SonarCloud

.cirrus.yml, .github/workflows/release.yml
Nothing to do for
* `.github/workflows/CreatePullRequest.yml`
* `.github/workflows/RequestReview.yml`
* `.github/workflows/StartProgress.yml`
* `.github/workflows/SubmitReview.yml`
=> BUILD-2178 Use Vault

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/BuildResultAssert.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java
* use `DEV` alias for sonar-security to discover such issues earlier
* adjust the asserts to use new `.ucfgs` files instead of `.ucfg`
=> Fix QA due to changes introduced in SONARSEC-3437

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/SonarLintProjectChecker.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/utils/PathWalker.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/SonarLintProjectCheckerTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/utils/PathWalkerTest.java
The PR uses the Java API to count the analyzed project JS/TS files. This metric is used to determine if the default generation of a tsconfig.json file specifying the project files with a general wildcard expression will be fast enough for SonarLint. The use of the Java API is best suited for this use case as it counts the same files that the TypeScript compiler will parse.
=> Count JS/TS files using java API to determine if project is beyond limit

eslint-bridge/src/linting/eslint/rules/helpers/module.ts, eslint-bridge/tests/linting/eslint/rules/encryption-secure-mode.test.ts, eslint-bridge/tests/linting/eslint/rules/file-permissions.test.ts, eslint-bridge/tests/linting/eslint/rules/no-weak-cipher.test.ts, eslint-bridge/tests/linting/eslint/rules/unverified-certificate.test.ts, eslint-bridge/tests/linting/eslint/rules/unverified-hostname.test.ts, eslint-bridge/tests/linting/eslint/rules/weak-ssl.test.ts, eslint-bridge/tests/tools/sonar-runtime/rule/no-missing-sonar-runtime.ts
Fixes https://github.com/SonarSource/SonarJS/issues/3605
=> Fix FNs caused by `node:` imports in several rules using `getFullyQualifiedName()`

eslint-bridge/src/linting/eslint/rules/no-hook-setter-in-body.ts, eslint-bridge/tests/linting/eslint/rules/comment-based/no-hook-setter-in-body.js
=> Fix FP S6442 (`no-hook-setter-in-body`): Shouldn't raise when used conditionally

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java, sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/TypeScriptRulesDefinition.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/TypeScriptRulesDefinitionTest.java
Fixes #3580 
Note: we failed to add `Deprecated` section to the rule description
=> Deprecate S2814 (`no-redeclare`) for TypeScript

eslint-bridge/src/linting/eslint/rules/helpers/module.ts
=> Fix recursion in FQN resolution

sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/cache/FileMetadata.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/cache/CacheStrategyTest.java, sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/cache/FileMetadataTest.java
I am still not 100% happy with it because of extended usage of mocks, we would need to refactor the code to make it more testable
=> Improve test coverage for file hash in cache

.cirrus.yml
The Windows EC2 image is using Java 11 while SonarQube now requires Java 17. The image should be upgraded.
=> Update windows base image to get Java 17

eslint-bridge/src/linting/eslint/rules/helpers/ast.ts, eslint-bridge/src/linting/eslint/rules/unused-named-groups.ts, eslint-bridge/tests/linting/eslint/rules/unused-named-groups.test.ts
=> Fix FP S5860 (`unused-named-groups`): Consider accesses via the index syntax

src/linting/eslint/rules/sonar-no-empty-character-class.ts, tests/linting/eslint/rules/comment-based/sonar-no-empty-character-class.js
While validating the rule on Peach, there are many false positives for this specific pattern `[^]` which matches any character. Unfortunately, this was not detected with the projects we use on ruling.
=> Fix FP S2639 (`sonar-no-empty-character-class`): Ignore `[^]` matching any character

src/services/program/program.ts
It can only work with watchProgram. This reverts https://github.com/SonarSource/SonarJS/pull/3743
=> Remove compilerHost to handle vue files in program creation

src/linting/eslint/rules/helpers/type.ts, src/linting/eslint/rules/no-alphabetical-sort.ts, src/linting/eslint/rules/no-for-in-iterable.ts, tests/linting/eslint/rules/no-alphabetical-sort.test.ts, tests/linting/eslint/rules/no-for-in-iterable.test.ts
This PR reuses the logic from `no-alphabetical-sort` which is now shared in `type.ts` to cover cases where the array is a union type or a generic parameter extending an array type as in:
```typescript
const fn = (arr: number[] | string[]) => {
for (const x in arr) {
console.log(x);
}
};
```
and 
```typescript
const fn = <T extends any[]>(arr: T) => {
for (const x in arr) {
console.log(x);
}
};
```
Fixes #3796
=> Update S4139 (`no-for-in-array`): Cover cases from TypeScript ESLint implementation

src/linting/eslint/rules/decorators/no-redundant-type-constituents.ts, tests/linting/eslint/rules/comment-based/no-redundant-type-constituents.ts
I noticed that we already reduced the scope of the rule for `any` to simple cases. I did the same for the case of `unknown` since we are facing the same issue as François did when he first implemented the rule and limited the scope.
=> Update S6571 (`no-redundant-type-constituents`): Limit unknown detection to the `unknown` type annotation

its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractEslintSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithWatchProgram.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JsTsSensorTest.java, src/helpers/context.ts, src/services/program/program.ts, tests/parsing/jsts/builders/build.test.ts
- `ProjectTsConfigs` need to be initialized lazily
- Analyze files without tsconfig also when using analysis with watch program
Fixes #3883
=> Analyze files without tsconfig also when using AnalysisWithWatchProgram

tests/services/program/program.test.ts
Skipping this tests as it very undeterministic. When running it alone locally is always passes, but on heavy load sometimes it failt due to FinalizationRegistry behaving in a 'best-effort' strategy. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry#avoid_where_possible
=> Skip garbage collection test

docs/DEV.md, its/ruling/src/test/java/org/sonar/javascript/it/JavaScriptRulingTest.java, src/services/program/program.ts
SONARJS_LIMIT_DEPS_RESOLUTION was available to limit TS resolution to current baseDir. However, this does not apply when we rely on typescript-eslint to create watchPrograms. If we are ever able to provide our own compilerHost to typescript-eslint, we can generalize for all projects and avoid removing node_modules for ruling tests
=> Remove again node_modules on ruling tests

src/parsing/jsts/parsers/options.ts
As mentioned in https://babeljs.io/docs/babel-preset-env#browserslist-integration:
> By default @babel/preset-env will use [browserslist config sources](https://github.com/ai/browserslist#queries) unless either the [targets](https://babeljs.io/docs/babel-preset-env#targets) or [ignoreBrowserslistConfig](https://babeljs.io/docs/babel-preset-env#ignorebrowserslistconfig) options are set.
Babel will walk the tree looking for browserlist files. Some external browserlists will make babel fail, as Python squad saw with django-cms peach analysis.
This will avoid babel to look for those files.
=> Do not rely on external browserlists files

.github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
When merged, we would need to change the branches to @V1 like:
```yaml
- uses: sonarsource/gh-action-lt-backlog/MoveCardToReview@V1
```
instead of 
```yaml
- uses: sonarsource/gh-action-lt-backlog/MoveCardToReview@ use-until-merged
```
=> Update "submit review" and "request review" actions to work for projectsV2

packages/jsts/src/rules/S3758/rule.ts, packages/jsts/src/rules/S3758/unit.test.ts
=> Update S3758 (`values-not-convertible-to-numbers`): Allow ES2020 BigInt

packages/jsts/src/rules/S1128/cb.fixture.vue, packages/jsts/src/rules/S1128/rule.ts
=> Fix FP S1128 (`unused-import`): Consider all names of Vue.js elements

packages/jsts/src/linter/visitors/syntax-highlighting.ts, packages/jsts/tests/linter/visitors/fixtures/syntax-highlighting/typescript.ts, packages/jsts/tests/linter/visitors/syntax-highlighting.test.ts
While working on #4078, I noticed on SonarCloud that TypeScript keywords `as` and `any` were not highlighted as keywords. The corresponding tokens processed by the bridge and coming from TypeScript ESLint are wrongly described as "identifier" tokens for some obscure reason. After further investigation, I am not entirely sure whether the cause is coming from TypeScript ESLint or TypeScript itself.
__Before__
__After__
I double-checked all other TypeScript-specific keywords, and only `as` and `any` were not properly highlighted.
=> Add syntax highlighting for TypeScript "as" and "type" keywords

packages/jsts/src/rules/S1128/cb.fixture.vue, packages/jsts/src/rules/S1128/rule.ts
add one more case to #4047 - Vue component names like `library.item`
=> Fix FP S1128 (`unused-import`): Cover Vue elements with dot in the name

packages/jsts/src/rules/S5689/rule.ts, packages/jsts/src/rules/S5689/unit.test.ts
=> Improve S5689: Use different messages if sensitive header is set explicitely or by default

its/ruling/src/test/expected/js/javascript-test-sources/javascript-S106.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S109.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1117.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1314.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S139.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1441.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1451.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1541.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1774.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S2260.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3504.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3512.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3533.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S3723.json, its/ruling/src/test/expected/js/javascript-test-sources/javascript-S6657.json, its/ruling/src/test/expected/js/jshint/javascript-S2260.json, its/ruling/src/test/expected/js/mootools-core/javascript-S2260.json, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithProgram.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisWithWatchProgram.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BridgeServer.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/BridgeServerImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JavaScriptEslintBasedSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JsTsSensorTest.java
Babel fallback is only used in SonarLint or in Vue projects at the moment. Always fallback to it for JS files when TypeScript fails to parse the file.
=> Fix Babel fallback for JS files

packages/jsts/src/rules/S6535/cb.fixture.js, packages/jsts/src/rules/S6535/rule.ts
Fixes #3987 
S6535 implementation consists of merging ESLint rules `no-useless-escape` and `no-nonoctal-decimal-escape`. However, both share a common message id `escapeBackslash` with a different description for their respective suggestions. Because this wasn't noticed at the time of merging the rules, the message id `escapeBackslash` from `no-nonoctal-decimal-escape` used to overwrite the one from `no-useless-escape`. This is why not only the suggestion messages were sometimes confusing but also why the data interpolation of some suggestions didn't occur.
=> Fix S6535 (unnecessary-character-escapes): Disambiguate conflicting message ids

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/AnalysisProcessor.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/eslint/JsTsSensorTest.java
=> Log the filename for which an issue is saved

its/plugin/projects/eslint_report/.eslintrc.json, its/plugin/projects/eslint_report/package-lock.json, its/plugin/projects/eslint_report/package.json, its/plugin/projects/eslint_report/report.json, its/plugin/projects/eslint_report/src/file.ts, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintReportTest.java, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/@angular-eslint-template.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/@angular-eslint.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/@angular-eslint_template.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/@typescript-eslint.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/core.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/ember.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/import.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/jsx-a11y.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/node.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/react-hooks.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/react.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/readme, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/sonarjs.json, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/eslint/vue.json, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/rules/EslintRulesDefinition.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/rules/EslintRulesDefinitionTest.java, tools/external-rules-metadata.js
=> Update metadata for the external rules

its/ruling/src/test/expected/js/javascript-test-sources/javascript-S1874.json, its/ruling/src/test/expected/js/p5.js/javascript-S1874.json, its/ruling/src/test/expected/ts/ant-design/typescript-S1874.json, its/ruling/src/test/expected/ts/eigen/typescript-S1874.json, its/ruling/src/test/expected/ts/vuetify/typescript-S1874.json, packages/jsts/src/rules/S1874/cb.fixture.ts, packages/jsts/src/rules/S1874/rule.ts
Fixes #4008 
Building from #4064, it turns out quite tricky to cover every single case of deprecated symbols that are used. In fact, after looking at TypeScript's codebase, there are many places where usages of deprecated APIs are detected and reported. This is due to several edge cases. Instead of replicating the logic for every single one, we propose to extract and propagate deprecation suggestions emitted by TypeScript's type checker. There are minor functional differences compared to our current implementation, like the fact that TypeScript reports on import statements. However, with these changes, we behave precisely like TypeScript compilers, thus reducing false positives and negatives.
=> Improve S1874 (`deprecation`): Report deprecations from TypeScript compiler

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommandBuilderImpl.java
=> Change run-node error message when Node.js is not found

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommand.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommandBuilderImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/EmbeddedNodeTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/nodejs/NodeCommandTest.java, tools/fetch-node/src/test/java/org/sonarsource/javascript/XZTest.java
=> Improve coverage & fix code smells

README.md
The updated numbers are based on those on Peach, i.e., the current master. Those from [rules.sonarsource.com](rules.sonarsource.com) will be updated once SonarJS is released.
=> Update rule count

package-lock.json, package.json, tools/fetch-node/scripts/fetch-node.mjs
Mend reports [CVE-2020-12265](https://www.mend.io/vulnerability-database/CVE-2020-12265) for `decompress-targz` because it has "vulnerable" version 4.1.1 . `decompress-targz` is not needed directly, it's included transitively by `decompress` which has "non-vulnerable" version `4.2.1`
=> Remove unneeded direct dependency `decompress-targz`

package.json
the checks on the [`master`](https://github.com/SonarSource/SonarJS/commits/master) branch fail since I broke the script by replacing characters in https://github.com/SonarSource/SonarJS/pull/4203. This fixes it.
=> Fix typedoc script

packages/bridge/src/server.ts
This is an addition to #4255 to improve logging when running in a Docker container, where `os.totalMem` would report the memory of the whole host machine. We try to read the memory configuration from cgroup parameters exposed in `sys`.
Additionally, I fixed the computation of size in MB by using binary Mega 1024*1024.
Unfortunately, there is no easy way to unit test.
=> Improve memory configuration message when running in Docker

bin/server, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java, package.json, packages/bridge/src/memory.ts, packages/bridge/src/server.ts, packages/bridge/src/worker.js, packages/bridge/tests/server.test.ts, packages/shared/src/helpers/context.ts, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/test/resources/mock-bridge/startServer.js
=> Report heap usage status with `sonar.javascript.node.debugMemory`

packages/jsts/src/rules/S6544/cb.fixture.ts, packages/jsts/src/rules/S6544/rule.ts
=> Improve S6544 (`no-misused-promises`): Report on the function's main token

sonar-plugin/sonar-javascript-plugin/pom.xml
Fixes #4223 
For information sonar-javascript-plugin doesn't honor the rule that the property defining the files of the language has the form `sonar.{language_key}.file.suffix`, that's why there is hardcoded mapping on SonarCloud side here 
https://github.com/SonarSource/sonarcloud-core/blob/ec30b0f6d37e33a31eb04da7bcec098826f4bb05/sonar-scanner-engine/src/main/java/org/sonar/scanner/repository/language/DefaultLanguagesRepository.java#L30 
We don't have a way to test it automatically. We can contact SonarCloud team (Cody) after the release to validate it manually.
=> Optimize plugin download on SonarCloud

its/ruling/src/test/expected/jsts/ace/javascript-S3800.json, its/ruling/src/test/expected/jsts/angular.js/javascript-S3800.json, its/ruling/src/test/expected/jsts/jshint/javascript-S3800.json, packages/jsts/src/rules/S3800/cb.fixture.js, packages/jsts/src/rules/S3800/cb.test.ts, packages/jsts/src/rules/S3800/rule.ts
=> Fix FP S3800 (`function-return-type`): Make the exception of returning at least one `this` instead of all `this`

its/ruling/src/test/expected/jsts/eigen/typescript-S6478.json, packages/jsts/src/rules/S6478/cb.fixture.jsx, packages/jsts/src/rules/S6478/decorator.ts
=> Improve S6478 (`no-unstable-nested-components`): Replace message and refine location

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
Fixes #4109
Node.js 16 was eol-ed 11th of September. https://nodejs.org/en/blog/announcements/nodejs16-eol
=> Deprecate Node.js 16

packages/jsts/src/rules/S5843/rule.ts, packages/jsts/src/rules/S5843/unit.test.ts, packages/jsts/src/rules/S5860/rule.ts, packages/jsts/src/rules/S5867/rule.ts, packages/jsts/src/rules/S5869/rule.ts, packages/jsts/src/rules/helpers/regex/location.ts, packages/jsts/src/rules/helpers/regex/rule-template.ts
=> Fix regex-related rules: Skip issues with inconsistent locations

.cirrus.yml
Tested by https://github.com/SonarSource/SonarJS/pull/4342
=> Fix CI: bring back Java coverage

.cirrus.yml
Now that we have the [JFrog CLI available on the image used in Windows](https://github.com/SonarSource/re-ci-images/pull/386), we can perform authentication as well.
This is done as REs will disable unauthenticated downloads from the JFrog NPM repository some time.
It aligns what [is done for the Linux build](https://github.com/SonarSource/SonarJS/blob/502e047758d17b4333d1f2d57931973dcfbb0f56/.cirrus.yml#L114).
=> Authenticate by Repox on Windows as well

.github/workflows/dogfood.yml
* Adapt the  dogfood pipeline
That way this secret can be rotated easily as it comes from Vault
* https://github.com/SonarSource/re-terraform-aws-vault/pull/823
=> BUILD-4131 use GitHub token from vault instead of sonartech api token

.cirrus.yml
Fixes #4402 
Before:
```
[INFO] User cache: /home/sonarsource/.sonar/cache
[INFO] Load/download plugins
[INFO] Load plugins index
[INFO] Load plugins index (done) | time=84ms
[INFO] Load/download plugins (done) | time=3826ms
```
After:
```
[INFO] Load/download plugins
[INFO] Load plugins index
[INFO] Load plugins index (done) | time=81ms
[INFO] Load/download plugins (done) | time=5605ms
```
Cache is not functioning anymore, as feature was already removed. Anyway, it's not worth to optimize 5 second download, because fetching the cache would take similar amount of time.
=> Remove cache for `.sonar` dir

.cirrus/nodejs.Dockerfile, package.json, sonar-plugin/sonar-javascript-plugin/pom.xml, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java, sonar-plugin/sonar-javascript-plugin/src/main/resources/static/documentation.md, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
=> Drop support for Node.js 14

packages/bridge/src/errors/middleware.ts, packages/bridge/tests/errors/middleware.test.ts, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/test/resources/mock-bridge/startServer.js
Bridge should return error status on unexpected errors and plugin should fail interrupting the analysis.
=> Bridge should return error status on unexpected errors

its/ruling/src/test/expected/jsts/desktop/typescript-S6594.json, its/ruling/src/test/expected/jsts/reddit-mobile/javascript-S6594.json, packages/jsts/src/rules/S6594/cb.fixture.js, packages/jsts/src/rules/S6594/rule.ts
=> Fix FP S6594 (`sonar-prefer-regexp-exec`): Ignore match count use case

packages/jsts/src/rules/S1472/rule.ts
Running fast ruling emits a huge amount of the following deprecation warning:
```
(node:24845) DeprecationWarning: The 'typeParameters' property is deprecated on CallExpression nodes.
Use 'typeArguments' instead. See https://typescript-eslint.io/linting/troubleshooting#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings.
```
We can safely replace "CallExpression#typeParameters" with "CallExpression# typeArguments".
=> Replace deprecated "CallExpression#typeParameters" with "typeArguments"

packages/jsts/src/rules/S2871/rule.ts, packages/jsts/src/rules/S2871/unit.test.ts, packages/jsts/src/rules/helpers/type.ts, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S2871.html
=> Fix FP S2871 (`no-alphabetical-sort`): Rework the rule to emit a dedicated message for arrays of strings

its/ruling/src/test/expected/jsts/eigen/typescript-S4323.json, its/ruling/src/test/expected/jsts/postgraphql/typescript-S4323.json, packages/jsts/src/rules/S4323/rule.ts, packages/jsts/src/rules/S4323/unit.test.ts
=> Fix FP S4323 (`use-type-alias`): Ignore nullable types

.prettierignore
While there is nothing worth prettifying, prettier is unnecessarily wasting time considering all generated files from fast ruling:
```
packages/ruling/tests/actual/jsts/ace/javascript-CommentRegexTest.json 3ms
packages/ruling/tests/actual/jsts/ace/javascript-S100.json 10ms
packages/ruling/tests/actual/jsts/ace/javascript-S103.json 3ms
packages/ruling/tests/actual/jsts/ace/javascript-S104.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S105.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S106.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S1066.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S1067.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S107.json 1ms
packages/ruling/tests/actual/jsts/ace/javascript-S108.json 0ms …
```
=> Ignore fast ruling generated files on prettifying

its/ruling/src/test/expected/jsts/desktop/typescript-S4123.json, packages/jsts/src/rules/S4123/rule.ts, packages/jsts/src/rules/S4123/unit.test.ts, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S4123.html
=> Fix FP S4123 (`no-invalid-await`): Ignore function calls for functions whose definition have JSdoc with a `returns` tag

its/ruling/src/test/expected/jsts/vuetify/javascript-S3800.json, packages/jsts/src/rules/S3800/rule.ts, packages/jsts/src/rules/S3800/unit.test.ts, packages/jsts/src/rules/helpers/type.ts
=> Fix FP S3800 (`function-return-type`): Exception for sanitation functions

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6582.html, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6582.json
=> Fix FP S6582 (`prefer-optional-chain`): Update description and severity

its/ruling/src/test/expected/jsts/ant-design/typescript-S6606.json, its/ruling/src/test/expected/jsts/courselit/typescript-S6606.json, its/ruling/src/test/expected/jsts/desktop/typescript-S6606.json, its/ruling/src/test/expected/jsts/eigen/typescript-S6606.json, its/ruling/src/test/expected/jsts/postgraphql/typescript-S6606.json, its/ruling/src/test/expected/jsts/react-cloud-music/typescript-S6606.json, its/ruling/src/test/expected/jsts/vuetify/typescript-S6606.json, packages/jsts/src/rules/S6606/fixtures/index.ts, packages/jsts/src/rules/S6606/fixtures/tsconfig.json, packages/jsts/src/rules/S6606/index.ts, packages/jsts/src/rules/S6606/rule.ts, packages/jsts/src/rules/S6606/unit.test.ts, packages/jsts/src/rules/helpers/type.ts, packages/jsts/src/rules/index.ts
Also when first argument is `string | undefined` and `number | undefined`
Fixes #3936
=> Fix FP S6606 (`prefer-nullish-coalescing`): When the first argument s boolean | undefined

.cirrus.yml, package.json
Until now, we were formatting the source code during build task, so we were not able to detect unformatted code. This adds back the format check before building the plugin
=> Check format with `prettier` before build

.cirrus.yml, package.json
When using the % in the Jest `maxWorkers` parameters, it computes the number of cores from an unknown number, **not the one we provide to the Cirrus node**!
So we decided for 4GB of RAM per core as that's the default RAM per node process and set the jest maxWorkers to: `#cores-2 = 8`
=> Use more memory for the CI: 10cores/40GB and set the Jest maxWorkers to 8 (#cores-2)

sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6850.html, sonar-plugin/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/S6850.json
The RSPEC documentation of rule S6850 use the term "heading" instead of the term "header". This PR aligns the plugin documentation of the rule accordingly.
=> Align S6850 documentation with the RSPEC one

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/CssIssuesTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AnalysisProcessor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/CssRuleSensor.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/HtmlSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JavaScriptEslintBasedSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JsTsSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/YamlSensorTest.java
=> Change log level of line `Failed to parse file ...` from `error` to `warn`

packages/jsts/src/rules/S2598/rule.ts, packages/jsts/src/rules/S2755/rule.ts, packages/jsts/src/rules/S4423/rule.lib.ts, packages/jsts/src/rules/S4426/rule.ts, packages/jsts/src/rules/S4502/rule.ts, packages/jsts/src/rules/S5122/rule.ts, packages/jsts/src/rules/S5332/rule.lib.ts, packages/jsts/src/rules/S5527/rule.ts, packages/jsts/src/rules/S5659/rule.ts, packages/jsts/src/rules/S5691/rule.ts, packages/jsts/src/rules/S5693/rule.ts, packages/jsts/src/rules/S5730/rule.ts, packages/jsts/src/rules/S5732/rule.ts, packages/jsts/src/rules/S5736/rule.ts, packages/jsts/src/rules/S5739/rule.ts, packages/jsts/src/rules/S5757/rule.ts, packages/jsts/src/rules/S5759/rule.ts, packages/jsts/src/rules/helpers/ast.ts, packages/jsts/src/rules/helpers/cookie-flag-check.ts, packages/jsts/tests/rules/helpers/ast.test.ts, packages/jsts/tests/rules/helpers/express.test.ts, packages/jsts/tests/rules/helpers/fixtures/normalObject.js, packages/jsts/tests/rules/helpers/fixtures/objectWithSpread.js, packages/jsts/tests/tools/sonar-runtime/rule/no-missing-sonar-runtime.ts
Fixes #4271
Simple refactor. Augmented the accepted type of getProperty to not change too much in the places getObjectExpressionProperty was actually used.
=> Remove getObjectExpressionProperty in favor of getProperty

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AnalysisProcessor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/AnalysisProcessorTest.java
=> Analysis should not fail when highlighting has invalid text range

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/YamlSensor.java
=> Use previously implemented YAML predicate to ignore Helm Chart YAML files

packages/css/src/analysis/analyzer.ts, packages/css/tests/analysis/analyzer.test.ts
=> Resolve issue #3667 - CSS parser error on invisible character <0x200b>

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AbstractBridgeSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommandBuilderImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/CssRuleSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/EmbeddedNodeTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/JavaScriptEslintBasedSensorTest.java
Fixes #4563 
As described in the task, we add the following logs:
1) Debug information, that the user platform is not supported
2) When the version of Node.js is unsupported, mention the possibility of setting it via the sonar.nodejs.executable property
Testing:
1) Augmented unit tests to verify that the logs get triggered
2) Manual test
- Build SonarJS
- Download SonarQube and copy the produced .jar into SonarQube extensions folder
- Change local Node version to 16
- Run Scanner on small JS project and observe in logs:
- 15:12:24.947 DEBUG: Your platform is unsupported for embedded Node.js. Falling back to host Node.js.
- 15:12:28.081 ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Error while running Node.js. A supported version of Node.js is required for …
=> Add additional logs when embedded Node.js is not available

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/EslintReportSensor.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/EslintReportSensorTest.java
Fixes #1986 
The user's recommendation to log at the info-level might hide real problems that could be overlooked. Therefore, I advocate for logging at the warn-level to ensure it won't go unnoticed. This approach mirrors our handling of unfound LCOV reports.
=> Reduce log severity to warning for unfound ESLint reports

packages/jsts/src/rules/S2699/rule.ts, packages/jsts/src/rules/S2699/vitest.fixture.js
=> Resolve issue #4459: Fix FP S2699 (`Tests should include assertions`): global `expect()` aren't detected

packages/jsts/src/rules/S2699/vitest.fixture.js
Fixes #4507.
More accurately, #4507 is fixed by the fix provided to #4459, and this PR only adds a test to cover the specific case of using `describe.concurrrent`.
=> Resolve issue #4507

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/HtmlSecurityTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/YamlSecurityTest.java, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/assertj/BuildResultAssert.java, its/plugin/tests/src/test/resources/html-security-profile.xml, its/plugin/tests/src/test/resources/yaml-security-profile.xml, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/AnalysisMode.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/AnalysisModeTest.java
=> Disable ucfg rule for JS embedded in HTML files

its/ruling/src/test/expected/jsts/courselit/typescript-S6754.json, its/ruling/src/test/expected/jsts/eigen/typescript-S6754.json, its/ruling/src/test/expected/jsts/searchkit/javascript-S6754.json, packages/jsts/src/rules/S6754/decorator.ts, packages/jsts/src/rules/S6754/index.ts, packages/jsts/src/rules/S6754/unit.test.ts, packages/jsts/src/rules/index.ts
=> Fix FP S6754 (`hook-use-state`): Ignore state variables without a setter

its/ruling/src/test/expected/jsts/ace/javascript-S4030.json, package-lock.json, package.json, packages/jsts/src/rules/S2004/rule.ts
In preparation for release, let us update the eslint-plugin-sonarjs. 1 FP went away.
=> Update eslint-plugin-sonarjs version

package-lock.json, package.json, sonar-plugin/sonar-javascript-plugin/pom.xml, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
=> Change min required Node.JS version to 18.17.0

its/ruling/src/test/expected/jsts/ant-design/typescript-S5256.json, its/ruling/src/test/expected/jsts/sonar-web/javascript-S5256.json, packages/jsts/src/rules/S5260/cb.fixture.jsx, packages/jsts/src/rules/helpers/table.ts
Talking with @vdiez - we figured out that the tr's aren't checking for custom other tags. Let us be very strict and only perform a check if under a `<tr>` we have `<td>` or `<th>`
=> Check for unknown tags in tr's

.cirrus.yml
Unfortunately current infra doesn't allow to have stable enough results for meaningful perf regression testing. To avoid having alarm on the wallboard I will "disable" the task by setting it to manual execution only.
=> Change trigger type of perf task to `manual`

packages/jsts/src/dbd/frontend/expressions/call-expression.ts, packages/jsts/src/dbd/frontend/scope-translator.ts
If we have a CallExpression in the form <obj>.<meth>() and obj is an identifier and we can find it in the variableMap, let us mark this as an instanceMethod
=> Simple inference of InstanceMethod

.cirrus.yml
To avoid traffic to repox when dowloading SQ for ITs we will cache the dir where orchestrator keeps downloads
=> Use Cirrus cache for Orchestrator

packages/jsts/src/dbd/js-to-dbd/core/expressions/array-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/instructions/call-instruction.ts, packages/jsts/src/dbd/js-to-dbd/core/instructions/phi-instruction.ts, packages/jsts/src/dbd/js-to-dbd/core/instructions/value-instruction.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/variable-declaration.ts, packages/jsts/src/dbd/js-to-dbd/core/type-info.ts, packages/jsts/src/dbd/js-to-dbd/core/value.ts, packages/jsts/src/dbd/js-to-dbd/core/values/constant.ts, packages/jsts/src/dbd/js-to-dbd/core/values/parameter.ts, packages/jsts/src/dbd/js-to-dbd/core/values/reference.ts, packages/jsts/src/dbd/js-to-dbd/core/values/type-name.ts, snippet.ts
I would like to have better types when creating objects. Let us put the TypeInfo to the root of the Value
=> Add typeinfo to the lower levels

packages/jsts/src/dbd/js-to-dbd/core/context-manager.ts, packages/jsts/src/dbd/js-to-dbd/core/expression-handler.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/array-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/arrow-function-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/assignment-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/binary-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/call-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/conditional-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/identifier.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/index.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/literal.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/logical-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/member-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/object-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/unary-expression.ts, packages/jsts/src/dbd/js-to-dbd/core/expressions/variable-declarator.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/block-statement.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/expression-statement.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/function-declaration.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/if-statement.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/return-statement.ts, packages/jsts/src/dbd/js-to-dbd/core/statements/variable-declaration.ts
As part of the ExpressionHandler we used to return the Instructions that later needed to be added to the current block. Let us push this responsibility on the ExpressionHandler themselves.
=> Remove-instructions

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/EmbeddedNodeTest.java, sonar-plugin/sonar-javascript-plugin/pom.xml, tools/fetch-node/node-distros.mjs, tools/fetch-node/pom.xml
Took inspiration from https://github.com/SonarSource/SonarJS/pull/4194
=> JS-170 Bundle SonarJS with Node.js Runtime on Linux ARM Platform

packages/jsts/src/analysis/analyzer.ts
With this change, we skip the AST serialization, not just the sending of the AST in the response.
=> Do not serialize the AST if the `skipAst` flag is set

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisProcessor.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/AnalysisProcessorTest.java
Seems illegal state is used for overlapping, and illegal argument for invalid offsets. 
We need to catch both
Fixes https://sonarsource.atlassian.net/browse/JS-209
=> JS-209 Catch IllegalStateException when saving highlights and cpd tokens

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinitionTest.java
This PR only makes sense with https://github.com/SonarSource/sonar-armor/pull/176, and should be merged first.
=> SONARARMOR-98 SonarArmor JS/TS rules should be in Sonar Way profile

NOTICE.txt, README.md, jest-resolver.js, packages/bridge/src/worker.js, packages/jsts/src/rules/S5973/fixtures/with-jest/cb.test.ts, packages/jsts/src/rules/S5973/fixtures/without-jest/cb.test.ts, packages/jsts/src/rules/helpers/find-files.ts, packages/jsts/tests/parsers/fixtures/ast/base.js, sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/estree/ESTree.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/SizeAssessorTest.java, tools/check-distribution-filepath-length.js, tools/estree/generate-java-ast.ts, tools/estree/generate-proto-file.ts, tools/estree/load-proto.ts, tools/estree/main.ts, tools/external-rules-metadata.js, tools/fetch-node/scripts/copy-to-plugin.mjs, tools/fetch-node/scripts/directories.mjs, tools/fetch-node/scripts/fetch-node.mjs, tools/fetch-node/scripts/wrapper.mjs, tools/newRule.ts
Used the following regex to find mismatch: `Copyright.+20\d\d-20((1\d)|(2([0-3,5-9])))`
=> Update license headers to include 2024

package.json
Should we update it to community or [JIRA](https://sonarsource.atlassian.net/browse/JS/)? The "[open issue](https://github.com/SonarSource/SonarJS/issues/new/choose)" link on GitHub points to both.
=> Update the package.json bugs URL

packages/jsts/src/parsers/ast.ts, packages/jsts/tests/parsers/ast.test.ts, packages/jsts/tests/parsers/fixtures/ast/unknownNode.ts
=> JS-304 Support TSAsExpression nodes

packages/jsts/src/parsers/ast.ts, packages/jsts/src/parsers/estree.proto, packages/jsts/tests/parsers/ast.test.ts, sonar-plugin/api/src/main/java/org/sonar/plugins/javascript/api/estree/ESTree.java, sonar-plugin/api/src/test/java/org/sonar/plugins/javascript/api/estree/ESTreeTest.java, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/ESTreeFactory.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/ESTreeFactoryTest.java
For the AST, you can use this in [ASTexplorer](https://astexplorer.net/):
```js
export = TAINT_SOURCE();
```
which yields:
```json
{
"type": "Program",
"body": [
{
"type": "TSExportAssignment",
"expression": {
"type": "CallExpression",
"callee": {
"type": "Identifier",
"name": "TAINT_SOURCE",
"range": [
9,
21
]
},
"arguments": [],
"optional": false,
"range": [
9,
23
]
},
"range": [
0,
24
]
}
],
"sourceType": "module",
"range": [
0,
24
]
}
```
=> JS-327 Support TSExportAssignment nodes

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/nodejs/NodeCommandBuilderImpl.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/nodejs/NodeCommandTest.java
This branch depends on #4820, which should be reviewed first.
=> JS-231 Deprecate the analyzer property sonar.nodejs.forceHost

packages/jsts/src/rules/S4782/fixtures/index.ts, packages/jsts/src/rules/S4782/fixtures/tsconfig.json, packages/jsts/src/rules/S4782/rule.ts, packages/jsts/src/rules/S4782/unit.test.ts
Please have a look also at this [RSPEC change](https://github.com/SonarSource/rspec/pull/4275), where I mention the behavior of the rule if `exactOptionalPropertyTypes` is enabled.
Note that I leave the update of the HTML rule description for when we run the rule-api tool before the next release.
=> JS-67 Fix FP S4782 (`no-redundant-optional`): Ignore when "exactOptionalPropertyTypes" is enabled

its/eslint8-plugin-sonarjs/eslint.config.cjs, its/eslint8-plugin-sonarjs/eslint.config.mjs, its/eslint8-plugin-sonarjs/file.js, its/eslint9-plugin-sonarjs/eslint.config.cjs, its/eslint9-plugin-sonarjs/eslint.config.mjs, packages/bridge/src/worker.js, packages/jsts/src/analysis/projectAnalysis/projectAnalyzer.ts, packages/jsts/src/linter/linters.ts, packages/jsts/src/linter/wrapper.ts, packages/jsts/src/rules/S4328/rule.ts, packages/jsts/src/rules/S4328/unit.test.ts, packages/jsts/src/rules/helpers/package-json.ts, packages/jsts/tests/analysis/analyzer.test.ts, packages/ruling/tests/tools/testProject.ts
=> ESLINTJS-49 Rule `no-implicit-dependencies` doesn't work

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/Environment.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/EmbeddedNodeTest.java
Hopefully, this allows the user to optimally set the location of the node deployment in their project. This isn't documented in the docs, so maybe the logs will help.
=> JS-70 More descriptive log when extracting node fails

package-lock.json, package.json, packages/jsts/src/program/program.ts, packages/jsts/src/rules/helpers/files.ts, packages/jsts/src/rules/helpers/find-up.ts, packages/jsts/src/rules/helpers/package-json.ts, packages/jsts/src/rules/package-lock.json, packages/jsts/src/rules/package.json, packages/jsts/tests/program/program.test.ts, packages/jsts/tests/rules/helpers/find-up.test.ts
=> ESLINTJS-56 Improve the performances of package manifest search

packages/jsts/src/rules/package.json
Fixes https://sonarsource.atlassian.net/browse/ESLINTJS-58
=> ESLINTJS-58 Change homepage URL for eslint-plugin-sonarjs npm package

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/ContextUtils.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java
I suggest we move forward with this change for now. There is no reason for JaRED to depend on Armor.
However, let's raise the topic of the relevance of these properties on the next weekly.
=> JS-362 Enable SonarJaRED to consume SonarJS ASTs without SonarArmor

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ConsumerPluginTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptProfilesDefinition.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/ContextUtils.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java
This PR should be merged very shortly before https://github.com/SonarSource/sonar-armor/pull/328 is merged.
=> SONARARMOR-458 Fix end-to-end tests for Jasmin

.cirrus.yml
BUILD-6666: Remove deprecated variables from Cirrus
=> BUILD-6666: Remove deprecated variables from Cirrus

packages/jsts/src/rules/S5693/rule.ts, packages/jsts/src/rules/S5693/unit.test.ts
Copied from https://github.com/SonarSource/SonarJS/pull/4851
=> Fix S5693: Resolve false positive for multer storage engine init

.cirrus.star, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/EslintBasedRulesTest.java
[BUILD-6583](https://sonarsource.atlassian.net/browse/BUILD-6583)
As the Development Infrastructure Squad has migrated all the workload out of the Docker In Docker implementation now we are getting rid of the CirrusCI-8 build Cluster (it will be decommissioned). As the Cirrus Modules v3 is pointing to the latest up-to-date Cluster, we are requesting all users to update!
This repository CirrusCI tasks has been specifically pinned to the CirrusCI-8 Cluster, removing the specification, defaults to the latest settings.
[BUILD-6583]: https://sonarsource.atlassian.net/browse/BUILD-6583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-6583: migrate from CirrusCI-8 cluster

packages/jsts/src/parsers/options.ts, packages/jsts/tests/parsers/fixtures/parse/valid.js, packages/jsts/tests/parsers/parse.test.ts
[JS-391](https://sonarsource.atlassian.net/browse/JS-391)
[JS-391]: https://sonarsource.atlassian.net/browse/JS-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-391 Babel presets as package names instead of paths

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/assertj/BuildResultAssert.java
[JS-402](https://sonarsource.atlassian.net/browse/JS-402)
[JS-402]: https://sonarsource.atlassian.net/browse/JS-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-402 Fix PRAnalysisTest

pom.xml, sonar-plugin/bridge/pom.xml, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/Http.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java, sonar-plugin/standalone/src/main/java/org/sonar/plugins/javascript/standalone/StandaloneParser.java
[JS-390](https://sonarsource.atlassian.net/browse/JS-390)
I cleaned-up the signatures of Bridge which declared `throws IOException` although this could never happen because `IOException` is catched in `BridgeServerImpl#request`
See also change in https://github.com/SonarSource/sonar-armor/pull/394
[JS-390]: https://sonarsource.atlassian.net/browse/JS-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-390 Refactor HTTP layer in BridgeServerImpl

.cirrus.yml, generate-eslint-package-json.mjs, its/eslint8-plugin-sonarjs/package.json, its/eslint9-plugin-sonarjs/package.json
[JS-420](https://sonarsource.atlassian.net/browse/JS-420)
[JS-420]: https://sonarsource.atlassian.net/browse/JS-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-420 [DO NOT SQUASH] Fix ITs: plugin_qa_sq_dev & eslint_plugin_test

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/JavaScriptPluginTest.java
[JS-363](https://sonarsource.atlassian.net/browse/JS-363)
[JS-363]: https://sonarsource.atlassian.net/browse/JS-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-363 - Support environment variable for setting `skipNodeProvisioning`

.github/workflows/releasability.yml
[JS-417](https://sonarsource.atlassian.net/browse/JS-417)
[JS-417]: https://sonarsource.atlassian.net/browse/JS-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
We will only see that this works after it lands in master. It needs the promote to run and will only happen on master. This PR is same as on SONARPHP - https://github.com/SonarSource/sonar-php/pull/1259
=> JS-417 Add releasability check

.github/renovate.json
[JS-416](https://sonarsource.atlassian.net/browse/JS-416)
[JS-416]: https://sonarsource.atlassian.net/browse/JS-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-416 Add renovate config

README.md, docs/DEV.md, package.json, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarning.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/NodeDeprecationWarningTest.java
[JS-371](https://sonarsource.atlassian.net/browse/JS-371)
[JS-371]: https://sonarsource.atlassian.net/browse/JS-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-371 - Deprecate Node.js 18

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisProcessor.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/AnalysisProcessorTest.java
[JS-367](https://sonarsource.atlassian.net/browse/JS-367)
[JS-367]: https://sonarsource.atlassian.net/browse/JS-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-367 Survive runtime failures on saving malformed issues

packages/jsts/src/analysis/analysis.ts, packages/jsts/src/analysis/analyzer.ts, packages/jsts/src/rules/helpers/package-json.ts, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithProgram.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithWatchProgram.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/HtmlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/YamlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/TsConfigCache.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/sonarlint/TsConfigCacheImpl.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/TsConfigCacheTest.java, sonar-plugin/standalone/src/main/java/org/sonar/plugins/javascript/standalone/StandaloneParser.java
[JS-435](https://sonarsource.atlassian.net/browse/JS-435)
As it might happen when the package.json is changed, we should dirty the cache.
I've tested, building the jar, copying it into the plugins and verifying that the 2 logs I've added are being triggered. I will add tests once the integration tests for SonarIDE are available.
I've verified, that opening a file from node_modules directory, does not trigger this event:
```
Trigger: EDITOR_OPEN
[EDITOR_OPEN] 1 file(s) submitted
File 'package.json' excluded: file is excluded or ignored in project structure
```
[JS-435]: https://sonarsource.atlassian.net/browse/JS-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-435 Clear dependencies cache when a package.json is modified.

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithWatchProgram.java
[JS-458](https://sonarsource.atlassian.net/browse/JS-458)
This fails with SonarQube cloud, because it uses PicoContainer and doesn't support @Nullable for constructor dependency injection
[JS-458]: https://sonarsource.atlassian.net/browse/JS-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-458 Fix missing constructor for nullable argument

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java
[JS-100](https://sonarsource.atlassian.net/browse/JS-100)
Tested by hand with killing the node processes and waiting a minute to see that the server actually gets respawned. See logs:
```
[2024-12-04T16:52:13.064] [sonarlint-analysis-engine] DEBUG sonarlint - Skipping the start of the bridge server as it failed to start during the first analysis or it's not answering anymore
..
[2024-12-04T16:52:23.924] [sonarlint-analysis-engine] DEBUG sonarlint - Skipping the start of the bridge server as it failed to start during the first analysis or it's not answering anymore
..
[2024-12-04T16:52:30.923] [sonarlint-analysis-engine] DEBUG sonarlint - Skipping the start of the bridge server as it failed to start during the first analysis or it's not answering anymore
..
[2024-12-04T16:52:36.868] …
```
=> JS-100 Allow the server to restart after failed status

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
[JS-517](https://sonarsource.atlassian.net/browse/JS-517)
Noticed this was missing. We print this at some point and it probably should be in sync.
[JS-517]: https://sonarsource.atlassian.net/browse/JS-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-517 Simple update typescript version

packages/ruling/tests/tools/testProject.ts, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/filter/JavaScriptExclusionsFileFilterTest.java
[JS-558](https://sonarsource.atlassian.net/browse/JS-558)
[JS-558]: https://sonarsource.atlassian.net/browse/JS-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-558 Add `contrib` folder name to default exclusions

sonar-plugin/standalone/src/main/java/org/sonar/plugins/javascript/standalone/StandaloneParser.java, sonar-plugin/standalone/src/test/java/org/sonar/plugins/javascript/standalone/StandaloneParserTest.java
[SONARARMOR-680](https://sonarsource.atlassian.net/browse/SONARARMOR-680)
In Sonar Jasmin, 
we have some `its` failing because typescript files are parsed as JS files.
During `its` We would like to have the option to send the actual filename to the wonderful `StandaloneParser` 🤩 
[SONARARMOR-680]: https://sonarsource.atlassian.net/browse/SONARARMOR-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARARMOR-680 StandaloneParser supports filename usage.

.cirrus.yml
[JS-598](https://sonarsource.atlassian.net/browse/JS-598)
[JS-598]: https://sonarsource.atlassian.net/browse/JS-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-598 Cache `node_modules/` folder in CI

packages/jsts/src/program/program.ts, packages/jsts/tests/program/program.test.ts
The sixth argument of `ts.parseJsonConfigFileContent` is wrongly set to the passed path. The method expect a _resolved path_. Passing a non-resolved path makes the program unable to resolve the included files.
Note that this is not the fix to COMMUNITY-129686. It is a fix required to debug the issue.
=> COMMUNITY-129686 - Update program.ts

.cirrus.yml
[BUILD-7754](https://sonarsource.atlassian.net/browse/BUILD-7754)
Part of BUILD-7754: Use monthly cache for orchestrator
This PR changes the cache logic to invalidate only on a monthly basis for tasks which rely on latest releases. For the task which uses `dev` version, it will continue to use the existing logic to invalidate daily
[BUILD-7754]: https://sonarsource.atlassian.net/browse/BUILD-7754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-7754: Use monthly cache for orchestrator

package.json
[JS-658](https://sonarsource.atlassian.net/browse/JS-658)
It was broken by hasty commit https://github.com/SonarSource/SonarJS/pull/5236
[JS-658]: https://sonarsource.atlassian.net/browse/JS-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-658 Fix CI

.cirrus.yml, its/plugin/plugins/eslint-custom-rules-plugin/pom.xml, its/plugin/sonarlint-tests/pom.xml, its/plugin/tests/pom.xml, its/pom.xml, its/ruling/pom.xml, pom.xml
[JS-654](https://sonarsource.atlassian.net/browse/JS-654)
[JS-654]: https://sonarsource.atlassian.net/browse/JS-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-654 Don't use maven profile for ITS

.cirrus.yml
Relaunch ruling task to keep track of results, we need scanner engine to accept S1291 as a valid `nosonar` rule key:
https://github.com/SonarSource/sonarqube/pull/3382
@zglicz - I think it's this pr that addressed it - https://github.com/SonarSource/sonar-enterprise/pull/13208
=> JS-643 Enable Java ruling

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java
[JS-690](https://sonarsource.atlassian.net/browse/JS-690)
This will happen again every time renovate updates TS version. We should get rid of this TS hardcoded version in Java side
[JS-690]: https://sonarsource.atlassian.net/browse/JS-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-690 Update message on latest supported Typescript

its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/ConsumerPluginTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsContext.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java
[JS-701](https://sonarsource.atlassian.net/browse/JS-701)
For the moment we want to keep a possibility to fallback to SonarSecurity when setting `sonar.jasmin.internal.disabled` to `true`.
Please do not merge yet. Has to be coordinated with some other PRs 
[JS-701]: https://sonarsource.atlassian.net/browse/JS-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-701 Consider SonarJasmin active by default

packages/jsts/src/rules/README.md
[JS-703](https://sonarsource.atlassian.net/browse/JS-703)
Copied from https://github.com/SonarSource/SonarJS/pull/5315
[JS-703]: https://sonarsource.atlassian.net/browse/JS-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-703 Update README to rename SonarLint to SonarQube for IDE

packages/bridge/src/delegate.ts, packages/jsts/src/analysis/analysis.ts, packages/jsts/src/analysis/analyzer.ts, packages/jsts/src/analysis/projectAnalysis/projectAnalysis.ts, packages/jsts/tests/analysis/analyzer.test.ts
[JS-711](https://sonarsource.atlassian.net/browse/JS-711)
Trying to dig into the ast code. Noticed that 'ast' was defined in the output, where there is a separate interface to denote the type with the ast. Let us use it.
[JS-711]: https://sonarsource.atlassian.net/browse/JS-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-711 NOJIRA small type change for ast in output analysis

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/dogfood.yml, .github/workflows/releasability.yml, .github/workflows/release_eslint_plugin.yml, .github/workflows/typedoc.yml
[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-8073 Migrate public repositories workflows to large runners

its/ruling/src/test/java/org/sonar/javascript/it/CssRulingTest.java, sonar-plugin/css/src/test/java/org/sonar/css/TestActiveRules.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AnalysisWithWatchProgram.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/TsConfigProvider.java
[JS-725](https://sonarsource.atlassian.net/browse/JS-725)
Fixes current SQ releasability. As well, incorporating changes from https://github.com/SonarSource/SonarJS/pull/5368
[JS-725]: https://sonarsource.atlassian.net/browse/JS-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-725 remove unused imports

its/plugin/plugins/consumer-plugin/pom.xml, its/plugin/tests/src/test/java/com/sonar/javascript/it/plugin/PRAnalysisTest.java, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/AstProtoUtils.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/AstProtoUtilsTest.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/HtmlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/YamlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/AstProtobufSerialization.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheAnalysis.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheAnalysisSerialization.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/cache/CacheKey.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheKeyTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheReporterTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheStrategyTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/cache/CacheTestUtils.java
[JS-716](https://sonarsource.atlassian.net/browse/JS-716)
[JS-716]: https://sonarsource.atlassian.net/browse/JS-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-716 AST consumers should get all ASTs in PR analysis context

sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/AbstractBridgeSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/CssRuleSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/HtmlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/JsTsSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/analysis/YamlSensor.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/EslintReportImporter.java, sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/external/ExternalIssueRepository.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/YamlSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/external/EslintReportImporterTest.java
[JS-749](https://sonarsource.atlassian.net/browse/JS-749)
We are moving the issues downstream to be handled within the analyzeFiles. We do not need to return the issues from this method. It should decrease amount of memory necessary.
[JS-749]: https://sonarsource.atlassian.net/browse/JS-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-749 Changing AbstractBridgeSensor::analyzeFiles to not return issues.

packages/bridge/src/handle-request.ts, packages/bridge/src/request.ts, packages/bridge/src/router.ts, packages/bridge/tests/router.test.ts, packages/bridge/tests/worker.test.ts, packages/jsts/src/analysis/analyzer.ts, packages/jsts/src/rules/helpers/package-json.ts, packages/jsts/tests/analysis/analyzer.test.ts, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServer.java, sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java, sonar-plugin/bridge/src/test/java/org/sonar/plugins/javascript/bridge/BridgeServerImplTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/JsTsSensorTest.java, sonar-plugin/sonar-javascript-plugin/src/test/java/org/sonar/plugins/javascript/analysis/PluginTelemetryTest.java
[JS-786](https://sonarsource.atlassian.net/browse/JS-786)
While trying to understand why kibana is failing on peachee, it turned out it was due to the Telemetry gathering of all dependencies. With the existing implemnetaiton, the dependencies gathering would take multiple hours.
The numbers are:
> cache size: 21736
> total number of dependency per base_dir: 40499493
No wonder with this implementation we were timing out.
That being said, we currently don't log the telemetry data and we don't use it during the analysis. It had a brief period in the end of 2024, where we logged it and benefitted from the data.
When we want to re-enable this ,we should be mindful about the time complexity of it.
[JS-786]: https://sonarsource.atlassian.net/browse/JS-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> JS-786 Remove get-all-dependencies

.cirrus.yml
[JS-787](https://sonarsource.atlassian.net/browse/JS-787)
Often windows tasks are the latest to finish, let us cache the npm modules on windows
[JS-787]: https://sonarsource.atlassian.net/browse/JS-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-787 Add win cache for build task

packages/jsts/src/analysis/projectAnalysis/tsconfigCache.ts, packages/jsts/tests/analysis/tsconfigs.test.ts
[JS-805](https://sonarsource.atlassian.net/browse/JS-805)
Trying to get into debugging SonarLint, started with running on SonarJS. What I found is:
If we try to go through a file that is not a part of any tsconfig, we will try to construct all of these tsconfig program's and receive the files that they cover. However, if any of these Typescript Program creation throws an exception (with SonarJS I got reasons like: invalid option in tsconfig, tsconfig doesn't match any files), then we don't get to the end of the request as we didn't have any catch in the process.
wdyt?
[JS-805]: https://sonarsource.atlassian.net/browse/JS-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-805 Catch tsconfig processing errors

sonar-plugin/bridge/src/main/java/org/sonar/plugins/javascript/bridge/EmbeddedNode.java
Greetings,
I noticed that our Sonar scans were showing the following debug logs
```
20:52:16.795 DEBUG Currently installed Node.js version: . Available version in analyzer: v22.11.0
20:52:16.795 DEBUG Lock acquired for extraction
20:52:16.803 DEBUG Extracting embedded node to /path/to/our/.sonar/js/node-runtime/node
```
As you can see the currently installed version seems to be empty and the scanner consequently doing the extraction of the node runtime. Unfortunately it does so for each scan.
On closer inspection, this seems to be caused by the `js/node-runtime/version.txt` file being empty. This is caused by the `InputStream` of the file from the JAR being already fully consumed in `EmbeddedNode::isDifferent` through `readAllBytes`. When the file should be then written via …
=> Avoid repeated extractions of embedded node runtime

its/ruling/src/test/expected/jsts/vuetify/typescript-S2301.json, packages/jsts/src/rules/S2301/rule.ts, packages/jsts/src/rules/S2301/unit.test.ts
[JS-685](https://sonarsource.atlassian.net/browse/JS-685)
[JS-685]: https://sonarsource.atlassian.net/browse/JS-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-685 Modify S2301 (`no-selector-parameter`): Add exception when selector parameter is an object property

its/plugin/plugins/consumer-plugin/pom.xml, its/plugin/plugins/eslint-custom-rules-plugin/pom.xml, its/plugin/sonarlint-tests/pom.xml, its/plugin/tests/pom.xml, its/ruling/pom.xml, its/ruling/src/test/java/org/sonar/javascript/it/JsTsRulingTest.java, pom.xml, sonar-plugin/api/pom.xml, sonar-plugin/bridge/pom.xml, sonar-plugin/css/pom.xml, sonar-plugin/css/src/test/java/org/sonar/css/metrics/TokenizerTest.java, sonar-plugin/javascript-checks/pom.xml, sonar-plugin/sonar-javascript-plugin/pom.xml, sonar-plugin/standalone/pom.xml
[JS-839](https://sonarsource.atlassian.net/browse/JS-839)
we were only using Apache commons lang in tests and there was a [CVE](https://sonarsource.atlassian.net/browse/SSF-863). For the usage we need I think we better don't have this dependency
Making sure that running `mvn dependency:analyze` now does not show any "used and undeclared" or "unused and declared" dependencies in any of the maven modules of the project.
Apache lang3 is not explicitly mentioned in our pom files any more. Using `mvn dependency:tree -Dverbose` it was visible which version of lang3 was picked up, and ordering of dependency declaration matters in Maven.
[JS-839]: https://sonarsource.atlassian.net/browse/JS-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-839 Clean up Maven dependencies

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml, .github/workflows/dogfood.yml, .github/workflows/releasability.yml, .github/workflows/release_eslint_plugin.yml, .github/workflows/typedoc.yml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
=> BUILD-8875: Migrate to standardized GitHub runner names

packages/jsts/src/rules/CHANGELOG.md
[JS-844](https://sonarsource.atlassian.net/browse/JS-844)
We forgot to add the issues from the ESLINTJS Jira project as point out [here](https://github.com/SonarSource/SonarJS/pull/5576#discussion_r2297836022)
[JS-844]: https://sonarsource.atlassian.net/browse/JS-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-844 Update changelog for eslint-plugin-sonarjs

pom.xml
[JS-868](https://sonarsource.atlassian.net/browse/JS-868)
The accepting of issues on SonarCloud doesn't carry over to Next - https://next.sonarqube.com/sonarqube/dashboard?id=org.sonarsource.javascript%3Ajavascript&codeScope=overall. Therefore, adding these exclusions in the pom.xml to avoid the fixtures.
[JS-868]: https://sonarsource.atlassian.net/browse/JS-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-868 remove fixtures from sca analysis

packages/jsts/src/rules/S6957/package.json
[JS-870](https://sonarsource.atlassian.net/browse/JS-870)
This was introducing a dependency vulnertability. Perhaps it's not needed.
[JS-870]: https://sonarsource.atlassian.net/browse/JS-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-870 remove unnecessary package.json

.github/workflows/releasability.yml, .github/workflows/release.yml
[JS-880](https://sonarsource.atlassian.net/browse/JS-880)
Now that ws is removed, we need to migrate to the newest release actions
[JS-880]: https://sonarsource.atlassian.net/browse/JS-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS-880 update gh release actions
